import { and, asc, eq, gte, lt } from "drizzle-orm";
import { db } from "@/db/client";
import { documentHistory, documentTypes, employeeDocuments, employees } from "@/db/schema";
import { recordAudit } from "@/lib/audit";
import { AppError } from "@/lib/errors";
import { getStorageProvider } from "@/lib/storage";
import { authorize } from "@/modules/tenancy/authorization";

const allowedTypes = new Set(["application/pdf", "image/jpeg", "image/png"]);
export function validateDocumentFile(file: { type: string; size: number }) { if (!allowedTypes.has(file.type)) throw new AppError("VALIDATION_ERROR", "Only PDF, JPEG, and PNG documents are supported.", 400); if (file.size > 10 * 1024 * 1024) throw new AppError("VALIDATION_ERROR", "Documents must be 10 MB or smaller.", 400); }
export function classifyDocumentExpiry(expiresAt: string | null | undefined, now = new Date(), expiringWithinDays = 30) { if (!expiresAt) return "active" as const; const expiry = new Date(`${expiresAt}T23:59:59Z`); if (expiry < now) return "expired" as const; const threshold = new Date(now); threshold.setUTCDate(threshold.getUTCDate() + expiringWithinDays); return expiry <= threshold ? "expiring" as const : "active" as const; }
async function employeeForUser(organizationId: string, userId: string) { const [employee] = await db.select().from(employees).where(and(eq(employees.organizationId, organizationId), eq(employees.userId, userId))); if (!employee) throw new AppError("NOT_FOUND", "Your employee profile is not linked.", 404); return employee; }
export async function listEmployeeDocuments(input: { organizationId: string; userId: string }) { await authorize({ organizationId: input.organizationId, permission: "document.read" }); const employee = await employeeForUser(input.organizationId, input.userId); return db.select().from(employeeDocuments).where(and(eq(employeeDocuments.organizationId, input.organizationId), eq(employeeDocuments.employeeId, employee.id), eq(employeeDocuments.lifecycleStatus, "active"))).orderBy(asc(employeeDocuments.uploadedAt)); }
export async function getExpiringDocuments(organizationId: string, days: number) { const until = new Date(); until.setDate(until.getDate() + Math.max(0, Math.min(days, 365))); return db.select().from(employeeDocuments).where(and(eq(employeeDocuments.organizationId, organizationId), gte(employeeDocuments.expiresAt, new Date().toISOString().slice(0, 10)), lt(employeeDocuments.expiresAt, until.toISOString().slice(0, 10)))); }
export async function createEmployeeDocument(input: { organizationId: string; userId: string; documentTypeId: string; fileName: string; mimeType: string; bytes: Uint8Array; expiresAt?: string; replacedDocumentId?: string }) { await authorize({ organizationId: input.organizationId, permission: "document.upload" }); validateDocumentFile({ type: input.mimeType, size: input.bytes.byteLength }); const employee = await employeeForUser(input.organizationId, input.userId); const [type] = await db.select().from(documentTypes).where(and(eq(documentTypes.id, input.documentTypeId), eq(documentTypes.organizationId, input.organizationId), eq(documentTypes.active, true))); if (!type) throw new AppError("NOT_FOUND", "Document type was not found or is inactive.", 404); const version = input.replacedDocumentId ? ((await db.select().from(employeeDocuments).where(and(eq(employeeDocuments.id, input.replacedDocumentId), eq(employeeDocuments.organizationId, input.organizationId), eq(employeeDocuments.employeeId, employee.id))))[0]?.version ?? 0) + 1 : 1; const storageKey = `${input.organizationId}/employees/${employee.id}/documents/${crypto.randomUUID()}-${input.fileName.replace(/[^a-zA-Z0-9._-]/g, "_")}`; const storage = getStorageProvider(); await storage.upload(storageKey, input.bytes, input.mimeType); try { const [document] = await db.insert(employeeDocuments).values({ organizationId: input.organizationId, employeeId: employee.id, documentTypeId: type.id, documentType: type.code, category: type.category, fileName: input.fileName, storageKey, mimeType: input.mimeType, fileSize: input.bytes.byteLength, status: type.verificationRequired ? "pending" : "verified", lifecycleStatus: "active", version, replacedDocumentId: input.replacedDocumentId, uploadedByUserId: input.userId, expiresAt: input.expiresAt }).returning(); await db.insert(documentHistory).values({ organizationId: input.organizationId, documentId: document.id, actorUserId: input.userId, action: "uploaded", newStatus: document.status }); await recordAudit({ actorUserId: input.userId, organizationId: input.organizationId, action: "document_uploaded", resource: "employee_document", resourceId: document.id }); return document; } catch (error) { await storage.delete(storageKey); throw error; } }
export async function getDocumentDownload(input: { organizationId: string; userId: string; documentId: string }) { await authorize({ organizationId: input.organizationId, permission: "document.download" }); const employee = await employeeForUser(input.organizationId, input.userId); const [document] = await db.select().from(employeeDocuments).where(and(eq(employeeDocuments.id, input.documentId), eq(employeeDocuments.organizationId, input.organizationId), eq(employeeDocuments.employeeId, employee.id), eq(employeeDocuments.lifecycleStatus, "active"))); if (!document) throw new AppError("NOT_FOUND", "Document was not found.", 404); await db.insert(documentHistory).values({ organizationId: input.organizationId, documentId: document.id, actorUserId: input.userId, action: "downloaded", previousStatus: document.status }); return { url: await getStorageProvider().getSignedUrl(document.storageKey, 300) }; }
export async function updateDocumentStatus(input: { organizationId: string; actorUserId: string; documentId: string; status: "verified" | "rejected"; comment?: string }) { await authorize({ organizationId: input.organizationId, permission: input.status === "verified" ? "document.verify" : "document.reject" }); const [document] = await db.select().from(employeeDocuments).where(and(eq(employeeDocuments.id, input.documentId), eq(employeeDocuments.organizationId, input.organizationId))); if (!document) throw new AppError("NOT_FOUND", "Document was not found.", 404); const [updated] = await db.update(employeeDocuments).set({ status: input.status, verificationComment: input.comment?.trim(), updatedAt: new Date() }).where(eq(employeeDocuments.id, document.id)).returning(); await db.insert(documentHistory).values({ organizationId: input.organizationId, documentId: document.id, actorUserId: input.actorUserId, action: input.status, previousStatus: document.status, newStatus: input.status, comment: input.comment }); return updated; }
