import { and, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { db } from "@/db/client";
import { workflowDefinitions, workflowSteps, workflowVersions } from "@/db/schema";
import { errorResponse, AppError } from "@/lib/errors";
import { authorize } from "@/modules/tenancy/authorization";
import { resolveTenantContext } from "@/modules/tenancy/context";

export async function GET() { try { const tenant = await resolveTenantContext(); if (!tenant.organization) throw new AppError("FORBIDDEN", "Organization context is required.", 403); await authorize({ organizationId: tenant.organization.id, permission: "workflow.read" }); const definitions = await db.select().from(workflowDefinitions).where(eq(workflowDefinitions.organizationId, tenant.organization.id)); return NextResponse.json({ success: true, definitions }); } catch (error) { return errorResponse(error); } }
export async function POST(request: Request) { try { const tenant = await resolveTenantContext(); if (!tenant.organization) throw new AppError("FORBIDDEN", "Organization context is required.", 403); await authorize({ organizationId: tenant.organization.id, permission: "workflow.manage" }); const body = await request.json() as { name?: string; code?: string; workflowType?: string; steps?: Array<{ name: string; actorType: "reporting_manager" | "specific_user" | "organization_role" | "hr_admin"; actorRoleKey?: string; actorUserId?: string }> }; if (!body.name || !body.code || !body.workflowType || !body.steps?.length) throw new AppError("VALIDATION_ERROR", "Workflow name, code, type, and at least one step are required.", 400); const result = await db.transaction(async (tx) => { await tx.update(workflowDefinitions).set({ active: false, updatedAt: new Date() }).where(and(eq(workflowDefinitions.organizationId, tenant.organization.id), eq(workflowDefinitions.workflowType, body.workflowType!))); const [definition] = await tx.insert(workflowDefinitions).values({ organizationId: tenant.organization.id, name: body.name!, code: body.code!, workflowType: body.workflowType!, active: true, createdByUserId: tenant.user.id }).returning(); const [version] = await tx.insert(workflowVersions).values({ organizationId: tenant.organization.id, definitionId: definition.id, version: 1, active: true }).returning(); await tx.insert(workflowSteps).values(body.steps!.map((step, index) => ({ organizationId: tenant.organization!.id, versionId: version.id, stepOrder: index + 1, name: step.name, actorType: step.actorType, actorRoleKey: step.actorRoleKey, actorUserId: step.actorUserId, mode: "sequential" as const }))); return definition; }); return NextResponse.json({ success: true, definition: result }, { status: 201 }); } catch (error) { return errorResponse(error); } }
