"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

type Note = { id: string; note: string; createdAt: string; createdByUserId?: string | null };
export function OrganizationSupportNotes({ organizationId }: { organizationId: string }) { const [notes, setNotes] = useState<Note[]>([]); const [note, setNote] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const load = useCallback(async () => { try { const response = await fetch(`/api/platform/support?organizationId=${organizationId}`); const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message ?? "Support notes could not be loaded."); setNotes(body.notes ?? []); } catch (cause) { setError(cause instanceof Error ? cause.message : "Support notes could not be loaded."); } }, [organizationId]); useEffect(() => { void load(); }, [load]); async function submit(event: FormEvent) { event.preventDefault(); if (!note.trim()) return; setBusy(true); setError(""); try { const response = await fetch("/api/platform/support", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ organizationId, note: note.trim() }) }); const body = await response.json(); if (!response.ok) throw new Error(body?.error?.message ?? "Support note could not be created."); setNote(""); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Support note could not be created."); } finally { setBusy(false); } } return <Card><CardHeader><CardTitle>Platform support notes</CardTitle></CardHeader><CardContent className="space-y-4">{error && <p role="alert" className="text-sm text-danger">{error}</p>}<form onSubmit={submit} className="flex gap-2"><Input aria-label="Support note" placeholder="Add an operational note…" value={note} onChange={(event) => setNote(event.target.value)} /><Button type="submit" disabled={busy || !note.trim()}>Add note</Button></form>{notes.length ? <div className="space-y-2">{notes.map((item) => <div key={item.id} className="rounded-lg border p-3"><p className="text-sm">{item.note}</p><p className="mt-1 text-xs text-muted">{new Date(item.createdAt).toLocaleString()}</p></div>)}</div> : <p className="text-sm text-muted">No platform notes recorded.</p>}</CardContent></Card>; }
