import { and, desc, eq, ilike, inArray, or, sql } from "drizzle-orm";
import { z } from "zod";
import { db } from "@/db/client";
import { approvalTasks, atsApplicationStageHistory, atsApplications, atsCandidateActivities, atsCandidateNumberCounters, atsCandidates, atsInterviews, atsInterviewFeedback, atsInterviewers, atsJobs, atsPipelineStages, atsPipelines, atsRequisitionNumberCounters, atsRequisitions, atsTalentPoolMembers, atsTalentPools, employees } from "@/db/schema";
import { recordAudit } from "@/lib/audit";
import { AppError } from "@/lib/errors";
import { authorize } from "@/modules/tenancy/authorization";
import { createWorkflowInstance, ensureDefaultWorkflow } from "@/modules/workflows/service";
import { notifyUsers } from "@/modules/notifications/service";

const requisitionSchema = z.object({ title: z.string().trim().min(2).max(180), hiringManagerEmployeeId: z.string().uuid(), recruiterEmployeeId: z.string().uuid().optional(), openings: z.number().int().positive().max(1000).default(1), jobDescription: z.string().trim().min(10), departmentId: z.string().uuid().optional(), designationId: z.string().uuid().optional(), employmentTypeId: z.string().uuid().optional(), locationId: z.string().uuid().optional(), workMode: z.string().max(40).default("onsite"), experienceMin: z.number().min(0).max(60).optional(), experienceMax: z.number().min(0).max(60).optional(), salaryMin: z.number().min(0).optional(), salaryMax: z.number().min(0).optional(), currency: z.string().length(3).default("INR"), requiredSkills: z.string().max(4000).optional(), preferredSkills: z.string().max(4000).optional(), educationRequirements: z.string().max(2000).optional(), responsibilities: z.string().max(4000).optional(), qualifications: z.string().max(4000).optional(), benefits: z.string().max(4000).optional(), priority: z.string().max(30).default("normal"), targetJoiningDate: z.string().optional(), hiringReason: z.string().max(80).optional() });
const candidateSchema = z.object({ firstName: z.string().trim().min(1).max(80), lastName: z.string().trim().min(1).max(80), email: z.string().trim().email().max(320), phone: z.string().trim().max(40).optional(), location: z.string().max(160).optional(), currentCompany: z.string().max(180).optional(), currentDesignation: z.string().max(160).optional(), totalExperience: z.number().min(0).max(80).optional(), expectedSalary: z.number().min(0).optional(), noticePeriodDays: z.number().int().min(0).max(365).optional(), sourceId: z.string().uuid().optional(), sourceDetail: z.string().max(240).optional(), consentStatus: z.string().max(40).optional() });
function slugify(value: string) { return value.toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 150); }
function normalizeEmail(value: string) { return value.trim().toLowerCase(); }
function normalizePhone(value?: string) { return value?.replace(/\D/g, "") || undefined; }
async function nextRequisitionNumber(organizationId: string, year: number) { await db.insert(atsRequisitionNumberCounters).values({ organizationId, year }).onConflictDoNothing(); const [counter] = await db.update(atsRequisitionNumberCounters).set({ nextNumber: sql`${atsRequisitionNumberCounters.nextNumber} + 1`, updatedAt: new Date() }).where(and(eq(atsRequisitionNumberCounters.organizationId, organizationId), eq(atsRequisitionNumberCounters.year, year))).returning(); return `REQ-${year}-${String(counter.nextNumber).padStart(4, "0")}`; }
async function nextCandidateNumber(organizationId: string) { await db.insert(atsCandidateNumberCounters).values({ organizationId }).onConflictDoNothing(); const [counter] = await db.update(atsCandidateNumberCounters).set({ nextNumber: sql`${atsCandidateNumberCounters.nextNumber} + 1`, updatedAt: new Date() }).where(eq(atsCandidateNumberCounters.organizationId, organizationId)).returning(); return `CAN-${String(counter.nextNumber).padStart(6, "0")}`; }

export async function ensureDefaultAtsPipeline(organizationId: string, userId: string) {
  const [existing] = await db.select().from(atsPipelines).where(and(eq(atsPipelines.organizationId, organizationId), eq(atsPipelines.isDefault, true), eq(atsPipelines.active, true)));
  if (existing) return existing;
  const [pipeline] = await db.insert(atsPipelines).values({ organizationId, name: "Default recruitment pipeline", description: "Standard recruitment workflow", active: true, isDefault: true }).returning();
  const stages = [["Applied", "applied", "active", false], ["Screening", "screening", "active", false], ["Shortlisted", "shortlisted", "active", false], ["Interview", "interview", "active", false], ["Assessment", "assessment", "active", false], ["Offer", "offer", "active", false], ["Hired", "hired", "terminal", true]] as const;
  await db.insert(atsPipelineStages).values(stages.map(([name, code, category, terminal], index) => ({ organizationId, pipelineId: pipeline.id, name, code, category, terminal, stageOrder: index + 1 })));
  await recordAudit({ actorUserId: userId, organizationId, action: "ats_pipeline_created", resource: "ats_pipeline", resourceId: pipeline.id });
  return pipeline;
}

export async function createRequisition(input: { organizationId: string; userId: string; data: unknown }) { await authorize({ organizationId: input.organizationId, permission: "ats.requisition.create" }); const data = requisitionSchema.parse(input.data); if (data.experienceMax !== undefined && data.experienceMin !== undefined && data.experienceMax < data.experienceMin) throw new AppError("VALIDATION_ERROR", "Maximum experience cannot be below minimum experience.", 400); const managers = await db.select({ id: employees.id }).from(employees).where(and(eq(employees.organizationId, input.organizationId), inArray(employees.id, [data.hiringManagerEmployeeId, ...(data.recruiterEmployeeId ? [data.recruiterEmployeeId] : [])]))); if (managers.length !== (data.recruiterEmployeeId ? 2 : 1)) throw new AppError("NOT_FOUND", "Hiring manager or recruiter is not part of this organization.", 404); const [requisition] = await db.insert(atsRequisitions).values({ organizationId: input.organizationId, requisitionNumber: await nextRequisitionNumber(input.organizationId, new Date().getUTCFullYear()), ...data, createdByUserId: input.userId }).returning(); await recordAudit({ actorUserId: input.userId, organizationId: input.organizationId, action: "ats_requisition_created", resource: "ats_requisition", resourceId: requisition.id }); return requisition; }

export async function submitRequisition(input: { organizationId: string; userId: string; requisitionId: string }) { await authorize({ organizationId: input.organizationId, permission: "ats.requisition.edit" }); const [requisition] = await db.select().from(atsRequisitions).where(and(eq(atsRequisitions.id, input.requisitionId), eq(atsRequisitions.organizationId, input.organizationId))); if (!requisition) throw new AppError("NOT_FOUND", "Requisition was not found.", 404); if (requisition.status !== "draft") throw new AppError("VALIDATION_ERROR", "Only draft requisitions can be submitted.", 409); await ensureDefaultWorkflow(input.organizationId, "requisition", input.userId); const subjectEmployeeId = requisition.hiringManagerEmployeeId ?? requisition.recruiterEmployeeId; if (!subjectEmployeeId) throw new AppError("VALIDATION_ERROR", "A hiring manager is required for approval.", 422); const workflow = await createWorkflowInstance({ organizationId: input.organizationId, workflowType: "requisition", entityType: "ats_requisition", entityId: requisition.id, subjectEmployeeId, submittedByUserId: input.userId }); const [updated] = await db.update(atsRequisitions).set({ status: "pending_approval", workflowInstanceId: workflow.id, updatedAt: new Date() }).where(eq(atsRequisitions.id, requisition.id)).returning(); const tasks = await db.select().from(approvalTasks).where(eq(approvalTasks.workflowInstanceId, workflow.id)); await notifyUsers({ organizationId: input.organizationId, recipientUserIds: tasks.map((task) => task.approverUserId), category: "approvals", type: "ats.requisition.submitted", title: "Requisition approval required", message: `${requisition.requisitionNumber} is ready for review.`, entityType: "ats_requisition", entityId: requisition.id, actionUrl: "/app/approvals", idempotencyKey: `ats.requisition.submitted:${requisition.id}` }); await recordAudit({ actorUserId: input.userId, organizationId: input.organizationId, action: "ats_requisition_submitted", resource: "ats_requisition", resourceId: requisition.id }); return updated; }

export async function listRequisitions(input: { organizationId: string; userId: string }) { await authorize({ organizationId: input.organizationId, permission: "ats.requisition.view" }); return db.select().from(atsRequisitions).where(eq(atsRequisitions.organizationId, input.organizationId)).orderBy(desc(atsRequisitions.createdAt)); }
export async function createJob(input: { organizationId: string; userId: string; requisitionId: string; data: { publicTitle: string; publicDescription: string; slug?: string; applicationDeadline?: string; location?: string; workMode?: string; employmentType?: string; experience?: string; salaryDisplay?: string; responsibilities?: string; qualifications?: string; skills?: string } }) { await authorize({ organizationId: input.organizationId, permission: "ats.job.create" }); const [requisition] = await db.select().from(atsRequisitions).where(and(eq(atsRequisitions.id, input.requisitionId), eq(atsRequisitions.organizationId, input.organizationId))); if (!requisition || !["approved", "open"].includes(requisition.status)) throw new AppError("VALIDATION_ERROR", "Jobs can only be created from approved requisitions.", 409); const slug = slugify(input.data.slug || input.data.publicTitle); if (!slug) throw new AppError("VALIDATION_ERROR", "A valid job slug is required.", 400); const [existingSlug] = await db.select().from(atsJobs).where(eq(atsJobs.slug, slug)); if (existingSlug) throw new AppError("VALIDATION_ERROR", "That job slug is already in use.", 409); const [job] = await db.insert(atsJobs).values({ organizationId: input.organizationId, requisitionId: requisition.id, jobNumber: `JOB-${Date.now()}`, slug, ...input.data }).returning(); await recordAudit({ actorUserId: input.userId, organizationId: input.organizationId, action: "ats_job_created", resource: "ats_job", resourceId: job.id }); return job; }
export async function publishJob(input: { organizationId: string; userId: string; jobId: string }) { await authorize({ organizationId: input.organizationId, permission: "ats.job.publish" }); const [job] = await db.select().from(atsJobs).where(and(eq(atsJobs.id, input.jobId), eq(atsJobs.organizationId, input.organizationId))); if (!job) throw new AppError("NOT_FOUND", "Job was not found.", 404); const [requisition] = await db.select().from(atsRequisitions).where(eq(atsRequisitions.id, job.requisitionId)); if (!requisition || !["approved", "open"].includes(requisition.status)) throw new AppError("VALIDATION_ERROR", "Only an approved requisition can be published.", 409); const [updated] = await db.update(atsJobs).set({ status: "published", publishedAt: new Date(), updatedAt: new Date() }).where(eq(atsJobs.id, job.id)).returning(); await db.update(atsRequisitions).set({ status: "open", updatedAt: new Date() }).where(eq(atsRequisitions.id, requisition.id)); await recordAudit({ actorUserId: input.userId, organizationId: input.organizationId, action: "ats_job_published", resource: "ats_job", resourceId: job.id }); return updated; }

export async function findOrCreateCandidate(input: { organizationId: string; userId?: string; data: unknown }) { const data = candidateSchema.parse(input.data); const normalizedEmail = normalizeEmail(data.email); const normalizedPhone = normalizePhone(data.phone); const [existing] = await db.select().from(atsCandidates).where(and(eq(atsCandidates.organizationId, input.organizationId), or(eq(atsCandidates.normalizedEmail, normalizedEmail), normalizedPhone ? eq(atsCandidates.normalizedPhone, normalizedPhone) : undefined))); if (existing) return { candidate: existing, duplicate: true }; const [candidate] = await db.insert(atsCandidates).values({ organizationId: input.organizationId, candidateNumber: await nextCandidateNumber(input.organizationId), ...data, fullName: `${data.firstName} ${data.lastName}`.trim(), normalizedEmail, normalizedPhone, createdAt: new Date(), updatedAt: new Date() }).returning(); await recordAudit({ actorUserId: input.userId, organizationId: input.organizationId, action: "ats_candidate_created", resource: "ats_candidate", resourceId: candidate.id }); return { candidate, duplicate: false }; }
export async function createApplication(input: { organizationId: string; userId?: string; jobId: string; candidateData: unknown; coverNote?: string }) { const [job] = await db.select().from(atsJobs).where(and(eq(atsJobs.id, input.jobId), eq(atsJobs.status, "published"))); if (!job) throw new AppError("NOT_FOUND", "Published job was not found.", 404); if (job.applicationDeadline && job.applicationDeadline < new Date().toISOString().slice(0, 10)) throw new AppError("VALIDATION_ERROR", "Applications for this job are closed.", 409); const { candidate, duplicate } = await findOrCreateCandidate({ organizationId: job.organizationId, userId: input.userId, data: input.candidateData }); const pipeline = await ensureDefaultAtsPipeline(job.organizationId, input.userId ?? "00000000-0000-0000-0000-000000000000"); const [stage] = await db.select().from(atsPipelineStages).where(and(eq(atsPipelineStages.pipelineId, pipeline.id), eq(atsPipelineStages.stageOrder, 1))); if (!stage) throw new AppError("PROVISIONING_FAILED", "The default recruitment pipeline has no initial stage.", 422); const [application] = await db.insert(atsApplications).values({ organizationId: job.organizationId, candidateId: candidate.id, jobId: job.id, requisitionId: job.requisitionId, pipelineId: pipeline.id, currentStageId: stage.id, coverNote: input.coverNote }).onConflictDoNothing().returning(); if (!application) throw new AppError("VALIDATION_ERROR", "This candidate has already applied to this job.", 409); await db.insert(atsCandidateActivities).values({ organizationId: job.organizationId, candidateId: candidate.id, applicationId: application.id, activityType: "application_created", createdByUserId: input.userId }); await recordAudit({ actorUserId: input.userId, organizationId: job.organizationId, action: "ats_application_created", resource: "ats_application", resourceId: application.id, metadata: { duplicateCandidate: duplicate } }); return application; }
export async function moveApplication(input: { organizationId: string; userId: string; applicationId: string; stageId: string; reason?: string }) { await authorize({ organizationId: input.organizationId, permission: "ats.application.move" }); return db.transaction(async (tx) => { const [application] = await tx.select().from(atsApplications).where(and(eq(atsApplications.id, input.applicationId), eq(atsApplications.organizationId, input.organizationId))); const [stage] = await tx.select().from(atsPipelineStages).where(and(eq(atsPipelineStages.id, input.stageId), eq(atsPipelineStages.organizationId, input.organizationId), eq(atsPipelineStages.pipelineId, application?.pipelineId ?? ""))); if (!application || !stage) throw new AppError("NOT_FOUND", "Application or pipeline stage was not found.", 404); await tx.update(atsApplications).set({ currentStageId: stage.id, status: stage.code === "hired" ? "hired" : stage.code as typeof application.status, hired: stage.code === "hired", lastActivityAt: new Date(), updatedAt: new Date() }).where(eq(atsApplications.id, application.id)); await tx.insert(atsApplicationStageHistory).values({ organizationId: input.organizationId, applicationId: application.id, fromStageId: application.currentStageId, toStageId: stage.id, movedByUserId: input.userId, reason: input.reason }); await tx.insert(atsCandidateActivities).values({ organizationId: input.organizationId, candidateId: application.candidateId, applicationId: application.id, activityType: "stage_changed", metadata: JSON.stringify({ toStage: stage.code, reason: input.reason }), createdByUserId: input.userId }); return { ...application, currentStageId: stage.id, status: stage.code }; }); }
export async function searchCandidates(input: { organizationId: string; userId: string; query?: string; limit?: number; offset?: number }) { await authorize({ organizationId: input.organizationId, permission: "ats.candidate.view" }); const query = input.query?.trim(); return db.select().from(atsCandidates).where(and(eq(atsCandidates.organizationId, input.organizationId), query ? or(ilike(atsCandidates.fullName, `%${query}%`), ilike(atsCandidates.email, `%${query}%`), ilike(atsCandidates.currentCompany, `%${query}%`), ilike(atsCandidates.currentDesignation, `%${query}%`)) : undefined)).orderBy(desc(atsCandidates.updatedAt)).limit(Math.min(input.limit ?? 50, 100)).offset(input.offset ?? 0); }
export async function scheduleInterview(input: { organizationId: string; userId: string; applicationId: string; interviewerEmployeeIds: string[]; data: { interviewType: string; scheduledAt: string; durationMinutes?: number; timezone: string; mode: string; meetingLink?: string; location?: string } }) { await authorize({ organizationId: input.organizationId, permission: "ats.interview.create" }); const [application] = await db.select().from(atsApplications).where(and(eq(atsApplications.id, input.applicationId), eq(atsApplications.organizationId, input.organizationId))); if (!application) throw new AppError("NOT_FOUND", "Application was not found.", 404); const interviewers = await db.select().from(employees).where(and(eq(employees.organizationId, input.organizationId), inArray(employees.id, input.interviewerEmployeeIds), inArray(employees.status, ["active", "probation", "confirmed"]))); if (interviewers.length !== input.interviewerEmployeeIds.length) throw new AppError("VALIDATION_ERROR", "All interviewers must be active employees in this organization.", 422); const [interview] = await db.insert(atsInterviews).values({ organizationId: input.organizationId, applicationId: application.id, candidateId: application.candidateId, ...input.data, scheduledAt: new Date(input.data.scheduledAt) }).returning(); await db.insert(atsInterviewers).values(interviewers.map((employee) => ({ organizationId: input.organizationId, interviewId: interview.id, employeeId: employee.id }))); await recordAudit({ actorUserId: input.userId, organizationId: input.organizationId, action: "ats_interview_scheduled", resource: "ats_interview", resourceId: interview.id }); return interview; }
export async function submitInterviewFeedback(input: { organizationId: string; userId: string; interviewId: string; interviewerEmployeeId: string; data: { recommendation: string; rating?: number; strengths?: string; concerns?: string; technicalAssessment?: string; communicationAssessment?: string; overallComments?: string } }) { await authorize({ organizationId: input.organizationId, permission: "ats.interview.feedback" }); const [employee] = await db.select().from(employees).where(and(eq(employees.id, input.interviewerEmployeeId), eq(employees.organizationId, input.organizationId), eq(employees.userId, input.userId))); if (!employee) throw new AppError("FORBIDDEN", "Only the assigned interviewer can submit feedback.", 403); const [interview] = await db.select().from(atsInterviews).where(and(eq(atsInterviews.id, input.interviewId), eq(atsInterviews.organizationId, input.organizationId))); if (!interview) throw new AppError("NOT_FOUND", "Interview was not found.", 404); const [feedback] = await db.insert(atsInterviewFeedback).values({ organizationId: input.organizationId, interviewId: interview.id, interviewerEmployeeId: employee.id, ...input.data }).onConflictDoUpdate({ target: [atsInterviewFeedback.interviewId, atsInterviewFeedback.interviewerEmployeeId], set: { ...input.data, updatedAt: new Date() } }).returning(); await db.update(atsInterviews).set({ status: "completed", updatedAt: new Date() }).where(eq(atsInterviews.id, interview.id)); return feedback; }
export async function createTalentPool(input: { organizationId: string; userId: string; name: string; description?: string; ownerEmployeeId?: string }) { await authorize({ organizationId: input.organizationId, permission: "ats.talentpool.manage" }); const [pool] = await db.insert(atsTalentPools).values({ organizationId: input.organizationId, name: input.name.trim(), description: input.description, ownerEmployeeId: input.ownerEmployeeId }).returning(); await recordAudit({ actorUserId: input.userId, organizationId: input.organizationId, action: "ats_talent_pool_created", resource: "ats_talent_pool", resourceId: pool.id }); return pool; }
export async function addCandidateToTalentPool(input: { organizationId: string; userId: string; poolId: string; candidateId: string }) { await authorize({ organizationId: input.organizationId, permission: "ats.talentpool.manage" }); const [pool] = await db.select().from(atsTalentPools).where(and(eq(atsTalentPools.id, input.poolId), eq(atsTalentPools.organizationId, input.organizationId))); const [candidate] = await db.select().from(atsCandidates).where(and(eq(atsCandidates.id, input.candidateId), eq(atsCandidates.organizationId, input.organizationId))); if (!pool || !candidate) throw new AppError("NOT_FOUND", "Talent pool or candidate was not found.", 404); const [membership] = await db.insert(atsTalentPoolMembers).values({ organizationId: input.organizationId, poolId: pool.id, candidateId: candidate.id, addedByUserId: input.userId }).onConflictDoNothing().returning(); return membership ?? { poolId: pool.id, candidateId: candidate.id }; }
export async function publicJobBySlug(slug: string) { const [job] = await db.select({ job: atsJobs, requisition: atsRequisitions }).from(atsJobs).innerJoin(atsRequisitions, eq(atsJobs.requisitionId, atsRequisitions.id)).where(and(eq(atsJobs.slug, slug), eq(atsJobs.status, "published"))); if (!job) throw new AppError("NOT_FOUND", "Job was not found.", 404); return job; }
