import { NextResponse } from "next/server";
import { and, eq } from "drizzle-orm";
import { db } from "@/db/client";
import { employeeHistory, employees, onboarding, onboardingChecklistItems } from "@/db/schema";
import { errorResponse, AppError } from "@/lib/errors";
import { recordAudit } from "@/lib/audit";
import { resolveTenantContext } from "@/modules/tenancy/context";
import { authorize } from "@/modules/tenancy/authorization";
export async function POST(_request: Request, context: { params: Promise<{ employeeId: string }> }) { try { const tenant = await resolveTenantContext(); if (!tenant.organization) throw new AppError("FORBIDDEN", "Organization context is required.", 403); await authorize({ organizationId: tenant.organization.id, permission: "employee.onboard" }); const { employeeId } = await context.params; const [employee] = await db.select().from(employees).where(and(eq(employees.id, employeeId), eq(employees.organizationId, tenant.organization.id))); if (!employee) throw new AppError("NOT_FOUND", "Employee was not found.", 404); const [record] = await db.select().from(onboarding).where(and(eq(onboarding.employeeId, employeeId), eq(onboarding.organizationId, tenant.organization.id))); if (!record) throw new AppError("NOT_FOUND", "Onboarding record was not found.", 404); const pending = await db.select().from(onboardingChecklistItems).where(and(eq(onboardingChecklistItems.onboardingId, record.id), eq(onboardingChecklistItems.status, "pending"))); if (pending.length) throw new AppError("VALIDATION_ERROR", "Complete all onboarding checklist items first.", 400); const [updated] = await db.update(onboarding).set({ status: "completed", completedAt: new Date(), updatedAt: new Date() }).where(eq(onboarding.id, record.id)).returning(); await db.update(employees).set({ status: "active", updatedAt: new Date() }).where(eq(employees.id, employeeId)); await db.insert(employeeHistory).values({ organizationId: tenant.organization.id, employeeId, eventType: "onboarding_completed", previousValue: employee.status, newValue: "active", actorUserId: tenant.user.id }); await recordAudit({ actorUserId: tenant.user.id, organizationId: tenant.organization.id, action: "onboarding_completed", resource: "employee", resourceId: employeeId }); return NextResponse.json({ success: true, onboarding: updated }); } catch (error) { return errorResponse(error); } }
