<script lang="ts">
  import { page } from "$app/state";
  let password = $state(""); let confirmPassword = $state(""); let error = $state(""); let message = $state(""); let loading = $state(false);
  async function submit() { error = ""; if (password !== confirmPassword) { error = "Passwords do not match."; return; } loading = true; try { const response = await fetch("/api/auth/reset-password", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ token: page.url.searchParams.get("token"), password }) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error?.message ?? "Unable to reset password."); message = "Password reset successfully. You can now sign in."; } catch (cause) { error = cause instanceof Error ? cause.message : "Unable to reset password."; } finally { loading = false; } }
</script>
<section class="card"><p class="eyebrow">Account recovery</p><h1>Set a new password</h1><form onsubmit={(event) => { event.preventDefault(); submit(); }}><label>New password<input type="password" bind:value={password} minlength="12" required disabled={loading} /></label><label>Confirm password<input type="password" bind:value={confirmPassword} minlength="12" required disabled={loading} /></label>{#if error}<p class="error" role="alert">{error}</p>{/if}{#if message}<p class="success" role="status">{message}</p><a href="/login">Go to sign in</a>{/if}<button disabled={loading}>{loading ? "Updating…" : "Reset password"}</button></form></section>
<style>
  .card { background: white; border: 1px solid #e1e7f0; border-radius: 1rem; margin: auto; max-width: 32rem; padding: 2rem; } .eyebrow { color: #168f76; font-size: .78rem; font-weight: 800; letter-spacing: .12em; text-transform: uppercase; } form { display: grid; gap: 1rem; margin-top: 1.5rem; } label { display: grid; gap: .4rem; font-weight: 700; } input { border: 1px solid #cfd8e7; border-radius: .55rem; font: inherit; padding: .75rem; } button { background: #168f76; border: 0; border-radius: .55rem; color: white; font: inherit; font-weight: 750; padding: .8rem; } .error, .success { border-radius: .55rem; padding: .75rem; } .error { background: #fff1f1; color: #a52929; } .success { background: #ecfaf5; color: #13775f; }
</style>
