"use client";

import { useCallback, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
type Claim = { id: string; claimNumber: string; title: string; totalAmount: number; status: string; reimbursementStatus: string; description?: string | null };
type Item = { id: string; description: string; amount: number; expenseDate: string };
type Receipt = { id: string; itemId: string; fileName: string; scanStatus: string; verificationStatus: string };
type History = { id: string; action: string; comment?: string | null; createdAt: string };
export function ExpenseDetail({ claimId }: { claimId: string }) { const [claim, setClaim] = useState<Claim | null>(null); const [items, setItems] = useState<Item[]>([]); const [receipts, setReceipts] = useState<Receipt[]>([]); const [history, setHistory] = useState<History[]>([]); const [message, setMessage] = useState("Loading…"); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const response = await fetch(`/api/app/expenses/${claimId}`); const body = await response.json(); if (!response.ok || !body.success) { setMessage(body.error?.message ?? "Unable to load claim."); return; } setClaim(body.claim); setItems(body.items); setReceipts(body.receipts); setHistory(body.history); setMessage(""); }, [claimId]);
  useEffect(() => { void load(); }, [load]);
  const cancel = async () => { if (!window.confirm("Cancel this expense claim?")) return; setBusy(true); const response = await fetch(`/api/app/expenses/${claimId}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "cancel" }) }); const body = await response.json(); setMessage(response.ok && body.success ? "Claim cancelled." : body.error?.message ?? "Unable to cancel claim."); await load(); setBusy(false); };
  if (!claim) return <p className="text-sm text-muted">{message}</p>; return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-4"><div><p className="text-xs uppercase text-muted">Claim</p><p className="font-semibold">{claim.claimNumber}</p></div><div><p className="text-xs uppercase text-muted">Status</p><p className="font-semibold capitalize">{claim.status.replaceAll("_", " ")}</p></div><div><p className="text-xs uppercase text-muted">Reimbursement</p><p className="font-semibold">{claim.reimbursementStatus}</p></div><div><p className="text-xs uppercase text-muted">Total</p><p className="font-semibold">₹{claim.totalAmount}</p></div></div><p className="text-sm text-muted">{claim.title} {claim.description ? `· ${claim.description}` : ""}</p>{["draft", "submitted"].includes(claim.status) && <Button size="sm" variant="secondary" disabled={busy} onClick={cancel}>Cancel claim</Button>}<section><h2 className="font-semibold">Items and receipts</h2><div className="mt-2 space-y-2">{items.map((item) => <div key={item.id} className="rounded-lg border p-3 text-sm"><div className="flex justify-between"><span>{item.expenseDate} · {item.description}</span><span>₹{item.amount}</span></div>{receipts.filter((receipt) => receipt.itemId === item.id).map((receipt) => <p key={receipt.id} className="mt-2 text-xs text-muted">Receipt: {receipt.fileName} · scan: {receipt.scanStatus} · {receipt.verificationStatus}</p>)}</div>)}</div></section><section><h2 className="font-semibold">Claim history</h2><div className="mt-2 space-y-2">{history.map((entry) => <div key={entry.id} className="rounded-lg border p-3 text-sm"><span className="capitalize">{entry.action.replaceAll("_", " ")}</span><span className="ml-2 text-muted">{new Date(entry.createdAt).toLocaleString()}</span>{entry.comment && <p className="mt-1 text-muted">{entry.comment}</p>}</div>)}</div></section></div>; }
