import { and, eq } from "drizzle-orm";
import { db } from "@/db/client";
import { employees, expenseClaims, expenseHistory, expenseItems, expenseReceipts } from "@/db/schema";
import { AppError, errorResponse } from "@/lib/errors";
import { canTransitionExpenseStatus } from "@/modules/expenses/calculator";
import { authorize } from "@/modules/tenancy/authorization";
import { resolveTenantContextForUser } from "@/modules/tenancy/context-core";
import { withSvelteRequestUser } from "$lib/server/request-context";
import type { RequestHandler } from "./$types";

export const GET: RequestHandler = async (event) => { try { return Response.json(await withSvelteRequestUser(event, async (user) => { const tenant = await resolveTenantContextForUser(user); if (!tenant.organization) throw new AppError("FORBIDDEN", "Organization context is required.", 403); await authorize({ organizationId: tenant.organization.id, permission: "expense.read" }); const [employee] = await db.select({ id: employees.id }).from(employees).where(and(eq(employees.organizationId, tenant.organization.id), eq(employees.userId, user.id))); const [claim] = employee ? await db.select().from(expenseClaims).where(and(eq(expenseClaims.id, event.params.claimId), eq(expenseClaims.organizationId, tenant.organization.id), eq(expenseClaims.employeeId, employee.id))) : []; if (!claim) throw new AppError("NOT_FOUND", "Expense claim was not found.", 404); const items = await db.select().from(expenseItems).where(eq(expenseItems.claimId, claim.id)); const receipts = await db.select({ id: expenseReceipts.id, itemId: expenseReceipts.itemId, fileName: expenseReceipts.fileName, scanStatus: expenseReceipts.scanStatus, verificationStatus: expenseReceipts.verificationStatus, uploadedAt: expenseReceipts.uploadedAt }).from(expenseReceipts).where(eq(expenseReceipts.organizationId, tenant.organization.id)); return { success: true, claim, items, receipts: receipts.filter((receipt) => items.some((item) => item.id === receipt.itemId)), history: await db.select().from(expenseHistory).where(eq(expenseHistory.claimId, claim.id)) }; })); } catch (cause) { return errorResponse(cause); } };
export const PATCH: RequestHandler = async (event) => { try { return Response.json(await withSvelteRequestUser(event, async (user) => { const tenant = await resolveTenantContextForUser(user); if (!tenant.organization) throw new AppError("FORBIDDEN", "Organization context is required.", 403); await authorize({ organizationId: tenant.organization.id, permission: "expense.cancel" }); const [claim] = await db.select().from(expenseClaims).where(and(eq(expenseClaims.id, event.params.claimId), eq(expenseClaims.organizationId, tenant.organization.id))); if (!claim) throw new AppError("NOT_FOUND", "Expense claim was not found.", 404); const body = await event.request.json() as { action?: "cancel" }; if (body.action !== "cancel" || !canTransitionExpenseStatus(claim.status, "cancelled")) throw new AppError("VALIDATION_ERROR", "This expense claim cannot be cancelled.", 409); const [updated] = await db.update(expenseClaims).set({ status: "cancelled", cancelledAt: new Date(), updatedAt: new Date() }).where(eq(expenseClaims.id, claim.id)).returning(); await db.insert(expenseHistory).values({ organizationId: tenant.organization.id, claimId: claim.id, actorUserId: user.id, action: "cancelled", previousStatus: claim.status, newStatus: "cancelled" }); return { success: true, claim: updated }; })); } catch (cause) { return errorResponse(cause); } };
