import { describe, expect, it } from "vitest";
import { calculatePayroll } from "@/modules/payroll/calculator";
const base = { periodStart: "2026-04-01", periodEnd: "2026-04-30", calendarDays: 30, workingDays: 22, eligibleCalendarDays: 30, eligibleWorkingDays: 22, paidLeaveDays: 2, unpaidLeaveDays: 0, absentDays: 0, lopDays: 0, prorationBasis: "calendar_days" as const };
describe("payroll calculation engine", () => {
  it("calculates fixed, percentage, deduction and employer contribution lines", () => { const result = calculatePayroll({ ...base, components: [{ code: "BASIC", name: "Basic", type: "earning", method: "fixed", fixedAmount: 40000 }, { code: "HRA", name: "HRA", type: "earning", method: "percentage", percentage: 40, baseCode: "BASIC" }, { code: "PF", name: "PF", type: "deduction", method: "percentage", percentage: 5 }, { code: "PF_ER", name: "PF employer", type: "employer_contribution", method: "percentage", percentage: 5 }], statutory: { pf: { applicable: true, employeeRate: 12, employerRate: 12, wageCeiling: 15000 } } }); expect(result.grossEarnings).toBe(56000); expect(result.totalDeductions).toBe(4600); expect(result.employerContributions).toBe(4600); expect(result.netSalary).toBe(51400); });
  it("prorates joiners and records loss of pay", () => { const result = calculatePayroll({ ...base, eligibleCalendarDays: 15, eligibleWorkingDays: 11, lopDays: 2, components: [{ code: "BASIC", name: "Basic", type: "earning", method: "fixed", fixedAmount: 30000 }] }); expect(result.grossEarnings).toBe(13000); expect(result.lopDays).toBe(2); expect(result.lines.some((line) => line.code === "LOP")).toBe(true); });
  it("handles statutory foundations and formula warnings deterministically", () => { const result = calculatePayroll({ ...base, components: [{ code: "BONUS", name: "Bonus", type: "earning", method: "formula", proratable: false }], statutory: { esi: { applicable: true, employeeRate: 1, employerRate: 3.25 }, professionalTax: { applicable: true, amount: 200 }, tds: { applicable: true, amount: 1000 } } }); expect(result.totalDeductions).toBe(1200); expect(result.employerContributions).toBe(0); expect(result.warnings).toHaveLength(1); });
  it("rejects invalid negative inputs", () => { expect(() => calculatePayroll({ ...base, lopDays: -1, components: [] })).toThrow(); });
  it("supports working-day proration", () => { const result = calculatePayroll({ ...base, prorationBasis: "working_days", eligibleWorkingDays: 11, lopDays: 1, components: [{ code: "BASIC", name: "Basic", type: "earning", method: "fixed", fixedAmount: 22000 }] }); expect(result.grossEarnings).toBe(10000); expect(result.payableDays).toBe(10); });
  it("keeps non-proratable components whole", () => { const result = calculatePayroll({ ...base, eligibleCalendarDays: 15, components: [{ code: "BASIC", name: "Basic", type: "earning", method: "fixed", fixedAmount: 30000 }, { code: "BONUS", name: "Bonus", type: "earning", method: "fixed", fixedAmount: 5000, proratable: false }] }); expect(result.grossEarnings).toBe(20000); });
  it("includes earning and deduction adjustments", () => { const result = calculatePayroll({ ...base, components: [{ code: "BASIC", name: "Basic", type: "earning", method: "fixed", fixedAmount: 10000 }], adjustments: [{ type: "earning", code: "BONUS", name: "Bonus", amount: 1000 }, { type: "deduction", code: "RECOVERY", name: "Recovery", amount: 250 }] }); expect(result.grossEarnings).toBe(11000); expect(result.netSalary).toBe(10750); });
  it("caps statutory bases at configured ceilings", () => { const result = calculatePayroll({ ...base, components: [{ code: "BASIC", name: "Basic", type: "earning", method: "fixed", fixedAmount: 30000 }], statutory: { pf: { applicable: true, employeeRate: 12, employerRate: 12, wageCeiling: 15000 } } }); expect(result.statutoryDeductions).toBe(1800); expect(result.employerContributions).toBe(1800); });
  it("rounds money outputs consistently", () => { const result = calculatePayroll({ ...base, components: [{ code: "BASIC", name: "Basic", type: "earning", method: "fixed", fixedAmount: 10000.555 }] }); expect(result.grossEarnings).toBe(10000.56); expect(result.netSalary).toBe(10000.56); });
});
