import { and, eq } from "drizzle-orm";
import { db } from "@/db/client";
import { employeePayrollProfiles, payrollStatutoryConfigurations, payrollTaxConfigurations, salaryComponents, salaryStructureComponents, salaryStructures } from "@/db/schema";
import { AppError, errorResponse } from "@/lib/errors";
import { authorize } from "@/modules/tenancy/authorization";
import { resolveTenantContextForUser } from "@/modules/tenancy/context-core";
import { withSvelteRequestUser } from "$lib/server/request-context";
import type { RequestHandler } from "./$types";

export const GET: RequestHandler = async (event) => {
  try { return Response.json(await withSvelteRequestUser(event, async (user) => { const tenant = await resolveTenantContextForUser(user); if (!tenant.organization) throw new AppError("FORBIDDEN", "Organization context is required.", 403); await authorize({ organizationId: tenant.organization.id, permission: "payroll.configure" }); const [structures, components, statutory, tax, profiles] = await Promise.all([db.select().from(salaryStructures).where(eq(salaryStructures.organizationId, tenant.organization.id)), db.select().from(salaryComponents).where(eq(salaryComponents.organizationId, tenant.organization.id)), db.select().from(payrollStatutoryConfigurations).where(eq(payrollStatutoryConfigurations.organizationId, tenant.organization.id)), db.select().from(payrollTaxConfigurations).where(eq(payrollTaxConfigurations.organizationId, tenant.organization.id)), db.select().from(employeePayrollProfiles).where(eq(employeePayrollProfiles.organizationId, tenant.organization.id))]); return { success: true, structures, components, statutory, tax, profiles }; })); }
  catch (cause) { return errorResponse(cause); }
};

export const POST: RequestHandler = async (event) => {
  try {
    const body = await event.request.json() as { action?: string; structureId?: string; componentId?: string; name?: string; description?: string; effectiveFrom?: string; effectiveTo?: string; currency?: string; frequency?: string; code?: string; type?: "earning" | "deduction" | "employer_contribution"; calculationMethod?: "fixed" | "percentage" | "formula"; taxable?: boolean; statutory?: boolean; proratable?: boolean; fixedAmount?: number; percentage?: number; formulaReference?: string; displayOrder?: number; stateCode?: string; configuration?: Record<string, unknown>; regime?: "old" | "new"; financialYear?: string };
    return Response.json(await withSvelteRequestUser(event, async (user) => {
      const tenant = await resolveTenantContextForUser(user); if (!tenant.organization) throw new AppError("FORBIDDEN", "Organization context is required.", 403); await authorize({ organizationId: tenant.organization.id, permission: "payroll.configure" }); const organizationId = tenant.organization.id;
      if (body.action === "structure") { if (!body.name || !body.effectiveFrom || !body.currency) throw new AppError("VALIDATION_ERROR", "Structure name, currency, and effective date are required.", 400); const [structure] = await db.insert(salaryStructures).values({ organizationId, name: body.name.trim(), description: body.description?.trim(), effectiveFrom: body.effectiveFrom, effectiveTo: body.effectiveTo, currency: body.currency.toUpperCase(), frequency: body.frequency ?? "monthly", status: "draft" }).returning(); return { success: true, structure }; }
      if (body.action === "component") { if (!body.code || !body.name || !body.type || !body.calculationMethod) throw new AppError("VALIDATION_ERROR", "Component code, name, type, and calculation method are required.", 400); const [component] = await db.insert(salaryComponents).values({ organizationId, code: body.code.trim().toUpperCase(), name: body.name.trim(), type: body.type, calculationMethod: body.calculationMethod, taxable: body.taxable ?? true, statutory: body.statutory ?? false, proratable: body.proratable ?? true }).returning(); return { success: true, component }; }
      if (body.action === "link_component") { if (!body.structureId || !body.componentId) throw new AppError("VALIDATION_ERROR", "Structure and component are required.", 400); const [component] = await db.select({ id: salaryComponents.id }).from(salaryComponents).where(and(eq(salaryComponents.id, body.componentId), eq(salaryComponents.organizationId, organizationId))); const [structure] = await db.select({ id: salaryStructures.id }).from(salaryStructures).where(and(eq(salaryStructures.id, body.structureId), eq(salaryStructures.organizationId, organizationId))); if (!component || !structure) throw new AppError("NOT_FOUND", "Structure or component was not found.", 404); const [link] = await db.insert(salaryStructureComponents).values({ organizationId, structureId: body.structureId, componentId: body.componentId, fixedAmount: body.fixedAmount, percentage: body.percentage, formulaReference: body.formulaReference, displayOrder: body.displayOrder ?? 0 }).returning(); return { success: true, link }; }
      if (body.action === "statutory") { if (!body.code || !body.name || !body.effectiveFrom || !body.configuration) throw new AppError("VALIDATION_ERROR", "Statutory code, name, effective date, and configuration are required.", 400); const [statutory] = await db.insert(payrollStatutoryConfigurations).values({ organizationId, code: body.code.toUpperCase(), name: body.name, stateCode: body.stateCode, effectiveFrom: body.effectiveFrom, effectiveTo: body.effectiveTo, configuration: JSON.stringify(body.configuration), active: true }).returning(); return { success: true, statutory }; }
      if (body.action === "tax") { if (!body.regime || !body.financialYear || !body.effectiveFrom || !body.configuration) throw new AppError("VALIDATION_ERROR", "Tax regime, financial year, effective date, and configuration are required.", 400); const [tax] = await db.insert(payrollTaxConfigurations).values({ organizationId, regime: body.regime, financialYear: body.financialYear, effectiveFrom: body.effectiveFrom, effectiveTo: body.effectiveTo, configuration: JSON.stringify(body.configuration), active: true }).returning(); return { success: true, tax }; }
      throw new AppError("VALIDATION_ERROR", "Unsupported payroll configuration action.", 400);
    }), { status: 201 });
  } catch (cause) { return errorResponse(cause); }
};
