<script lang="ts">
  import { onMount } from "svelte";
  let data = $state<any>({}); let error = $state(""); let message = $state(""); let busy = $state("");
  async function load() { const response = await fetch("/api/app/attendance"); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Unable to load attendance."); data = body; }
  async function punch(type: string) { busy = type; error = ""; message = ""; try { const response = await fetch("/api/app/attendance/punch", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ type }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Unable to record punch."); message = "Attendance updated."; await load(); } catch (cause) { error = cause instanceof Error ? cause.message : "Unable to record punch."; } finally { busy = ""; } }
  onMount(() => load().catch((cause) => error = cause instanceof Error ? cause.message : "Unable to load attendance."));
</script>
<section class="heading"><p class="eyebrow">People operations</p><h1>Attendance</h1><p>Record attendance through the existing tenant-authorized service.</p></section>
<div class="actions">{#each [{type: "clock_in", label: "Clock in"}, {type: "clock_out", label: "Clock out"}, {type: "break_start", label: "Start break"}, {type: "break_end", label: "End break"}] as action}<button onclick={() => punch(action.type)} disabled={!!busy}>{busy === action.type ? "Saving…" : action.label}</button>{/each}</div>{#if error}<p class="error" role="alert">{error}</p>{/if}{#if message}<p class="success" role="status">{message}</p>{/if}<div class="panel"><h2>Attendance records</h2><pre>{JSON.stringify(data, null, 2)}</pre></div>
<style>
  .heading { margin-bottom: 1.5rem; } .eyebrow { color: #168f76; font-size: .75rem; font-weight: 800; letter-spacing: .1em; text-transform: uppercase; } h1 { margin: .4rem 0; } .heading p:last-child { color: #52617b; } .actions { display: flex; flex-wrap: wrap; gap: .7rem; margin-bottom: 1rem; } button { background: #168f76; border: 0; border-radius: .5rem; color: white; cursor: pointer; font-weight: 750; padding: .7rem .9rem; } button:disabled { cursor: wait; opacity: .6; } .panel { background: white; border: 1px solid #e1e7f0; border-radius: 1rem; padding: 1.25rem; } pre { background: #f6f8fb; border-radius: .5rem; max-height: 30rem; overflow: auto; padding: 1rem; white-space: pre-wrap; } .error, .success { border-radius: .5rem; padding: .7rem; } .error { background: #fff1f1; color: #a52929; } .success { background: #ecfaf5; color: #13775f; }
</style>
