<script lang="ts">
  import { onMount } from "svelte";
  type Employee = { id: string; employeeId: string; displayName: string; workEmail?: string; status: string };
  let employees = $state<Employee[]>([]); let firstName = $state(""); let lastName = $state(""); let workEmail = $state(""); let error = $state(""); let message = $state(""); let busy = $state(false); let inviteBusy = $state("");
  async function load() { const response = await fetch("/api/app/employees"); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Unable to load employees."); employees = body.employees ?? []; }
  async function create() { error = ""; message = ""; busy = true; try { const response = await fetch("/api/app/employees", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ firstName, lastName, workEmail, status: "invited" }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Unable to create employee."); message = "Employee created."; firstName = ""; lastName = ""; workEmail = ""; await load(); } catch (cause) { error = cause instanceof Error ? cause.message : "Unable to create employee."; } finally { busy = false; } }
  async function invite(employee: Employee) { inviteBusy = employee.id; error = ""; try { const response = await fetch(`/api/app/employees/${employee.id}/invite`, { method: "POST" }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Unable to send invitation."); message = "Invitation renewed. Use the configured delivery flow or copy-link action."; await load(); } catch (cause) { error = cause instanceof Error ? cause.message : "Unable to send invitation."; } finally { inviteBusy = ""; } }
  onMount(() => load().catch((cause) => error = cause instanceof Error ? cause.message : "Unable to load employees."));
</script>
<section class="heading"><p class="eyebrow">People operations</p><h1>Employees</h1><p>Manage tenant-scoped employee records and invitations.</p></section>
<div class="grid"><form class="panel" onsubmit={(event) => { event.preventDefault(); create(); }}><h2>Add employee</h2><label>First name<input bind:value={firstName} required disabled={busy} /></label><label>Last name<input bind:value={lastName} required disabled={busy} /></label><label>Work email<input type="email" bind:value={workEmail} disabled={busy} /></label><button disabled={busy}>{busy ? "Creating…" : "Create employee"}</button></form><div class="panel"><h2>Employee list</h2>{#if !employees.length}<p class="muted">No employees found.</p>{:else}<div class="list">{#each employees as employee}<article><div><strong>{employee.displayName}</strong><span>{employee.employeeId} · {employee.status}</span></div>{#if employee.status === "invited"}<button onclick={() => invite(employee)} disabled={inviteBusy === employee.id}>{inviteBusy === employee.id ? "Inviting…" : "Invite / resend"}</button>{/if}</article>{/each}</div>{/if}</div></div>{#if error}<p class="error" role="alert">{error}</p>{/if}{#if message}<p class="success" role="status">{message}</p>{/if}
<style>
  .heading { margin-bottom: 1.5rem; } .eyebrow { color: #168f76; font-size: .75rem; font-weight: 800; letter-spacing: .1em; text-transform: uppercase; } h1 { margin: .4rem 0; } .heading p:last-child, .muted { color: #52617b; } .grid { display: grid; gap: 1.25rem; grid-template-columns: minmax(18rem, 24rem) 1fr; } .panel { background: white; border: 1px solid #e1e7f0; border-radius: 1rem; padding: 1.25rem; } form { display: grid; gap: 1rem; align-content: start; } h2 { font-size: 1.1rem; margin-top: 0; } label { display: grid; gap: .4rem; font-size: .88rem; font-weight: 700; } input { border: 1px solid #cfd8e7; border-radius: .5rem; font: inherit; padding: .7rem; } button { background: #168f76; border: 0; border-radius: .5rem; color: white; cursor: pointer; font-weight: 750; padding: .65rem .8rem; } button:disabled { cursor: wait; opacity: .6; } .list { display: grid; gap: .7rem; } article { align-items: center; border: 1px solid #edf0f5; border-radius: .6rem; display: flex; gap: 1rem; justify-content: space-between; padding: .8rem; } article div { display: grid; gap: .25rem; } article span { color: #52617b; font-size: .85rem; } .error, .success { border-radius: .5rem; margin-top: 1rem; padding: .7rem; } .error { background: #fff1f1; color: #a52929; } .success { background: #ecfaf5; color: #13775f; } @media (max-width: 760px) { .grid { grid-template-columns: 1fr; } article { align-items: flex-start; flex-direction: column; } }
</style>
