<script lang="ts">
  import { onMount } from "svelte";
  let claims = $state<any[]>([]); let categories = $state<any[]>([]); let title = $state(""); let expenseDate = $state(""); let categoryId = $state(""); let amount = $state(""); let description = $state(""); let error = $state(""); let message = $state(""); let busy = $state(false);
  async function load() { const [claimsResponse, categoriesResponse] = await Promise.all([fetch("/api/app/expenses"), fetch("/api/app/expenses/categories")]); const claimsBody = await claimsResponse.json(); const categoriesBody = await categoriesResponse.json(); if (!claimsResponse.ok) throw new Error(claimsBody.error?.message ?? "Unable to load expenses."); claims = claimsBody.claims ?? []; categories = categoriesBody.categories ?? []; }
  async function submit() { error = ""; message = ""; busy = true; try { const response = await fetch("/api/app/expenses", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title, expenseDate, items: [{ categoryId, expenseDate, description: description || title, amount: Number(amount), currency: "INR" }] }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Unable to create expense."); message = "Expense claim created."; title = ""; expenseDate = ""; categoryId = ""; amount = ""; description = ""; await load(); } catch (cause) { error = cause instanceof Error ? cause.message : "Unable to create expense."; } finally { busy = false; } }
  onMount(() => load().catch((cause) => error = cause instanceof Error ? cause.message : "Unable to load expenses."));
</script>
<section class="heading"><p class="eyebrow">People operations</p><h1>Expenses</h1><p>Create and review tenant-scoped expense claims.</p></section>
<div class="grid"><form class="panel" onsubmit={(event) => { event.preventDefault(); submit(); }}><h2>New claim</h2><label>Title<input bind:value={title} required disabled={busy} /></label><label>Date<input type="date" bind:value={expenseDate} required disabled={busy} /></label><label>Category<select bind:value={categoryId} required disabled={busy}><option value="">Select a category</option>{#each categories as category}<option value={category.id}>{category.name}</option>{/each}</select></label><label>Amount<input type="number" min="0.01" step="0.01" bind:value={amount} required disabled={busy} /></label><label>Description<textarea bind:value={description} disabled={busy}></textarea></label><button disabled={busy}>{busy ? "Creating…" : "Create claim"}</button></form><div class="panel"><h2>Claims</h2>{#if !claims.length}<p class="muted">No expense claims found.</p>{:else}<div class="list">{#each claims as claim}<article><strong>{claim.title ?? claim.claim?.title}</strong><span>{claim.status ?? claim.claim?.status} · {claim.currency ?? claim.claim?.currency}</span></article>{/each}</div>{/if}</div></div>{#if error}<p class="error" role="alert">{error}</p>{/if}{#if message}<p class="success" role="status">{message}</p>{/if}
<style>
  .heading { margin-bottom: 1.5rem; } .eyebrow { color: #168f76; font-size: .75rem; font-weight: 800; letter-spacing: .1em; text-transform: uppercase; } h1 { margin: .4rem 0; } .heading p:last-child, .muted { color: #52617b; } .grid { display: grid; gap: 1.25rem; grid-template-columns: minmax(18rem, 24rem) 1fr; } .panel { background: white; border: 1px solid #e1e7f0; border-radius: 1rem; padding: 1.25rem; } form { display: grid; gap: 1rem; align-content: start; } h2 { font-size: 1.1rem; margin-top: 0; } label { display: grid; gap: .4rem; font-size: .88rem; font-weight: 700; } input, select, textarea { border: 1px solid #cfd8e7; border-radius: .5rem; font: inherit; padding: .7rem; } textarea { min-height: 5rem; } button { background: #168f76; border: 0; border-radius: .5rem; color: white; font-weight: 750; padding: .7rem; } .list { display: grid; gap: .7rem; } article { border: 1px solid #edf0f5; border-radius: .6rem; display: grid; gap: .3rem; padding: .8rem; } article span { color: #52617b; } .error, .success { border-radius: .5rem; padding: .7rem; } .error { background: #fff1f1; color: #a52929; } .success { background: #ecfaf5; color: #13775f; } @media (max-width: 760px) { .grid { grid-template-columns: 1fr; } }
</style>
