<script lang="ts">
  import { onMount } from "svelte";
  let leaveTypes = $state<any[]>([]); let applications = $state<any[]>([]); let leaveTypeId = $state(""); let startDate = $state(""); let endDate = $state(""); let reason = $state(""); let error = $state(""); let message = $state(""); let busy = $state(false);
  async function load() { const [typesResponse, leaveResponse] = await Promise.all([fetch("/api/app/leave/types"), fetch("/api/app/leave")]); const typesBody = await typesResponse.json(); const leaveBody = await leaveResponse.json(); if (!typesResponse.ok || !leaveResponse.ok) throw new Error(typesBody.error?.message ?? leaveBody.error?.message ?? "Unable to load leave."); leaveTypes = typesBody.leaveTypes ?? []; applications = leaveBody.applications ?? []; }
  async function submit() { error = ""; message = ""; busy = true; try { const response = await fetch("/api/app/leave", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ leaveTypeId, startDate, endDate, reason }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Unable to apply for leave."); message = "Leave application submitted."; startDate = ""; endDate = ""; reason = ""; await load(); } catch (cause) { error = cause instanceof Error ? cause.message : "Unable to apply for leave."; } finally { busy = false; } }
  onMount(() => load().catch((cause) => error = cause instanceof Error ? cause.message : "Unable to load leave."));
</script>
<section class="heading"><p class="eyebrow">People operations</p><h1>Leave</h1><p>Submit and review leave applications through the existing workflow engine.</p></section>
<div class="grid"><form class="panel" onsubmit={(event) => { event.preventDefault(); submit(); }}><h2>Apply for leave</h2><label>Leave type<select bind:value={leaveTypeId} required disabled={busy}><option value="">Select a type</option>{#each leaveTypes as type}<option value={type.id}>{type.name}</option>{/each}</select></label><label>Start date<input type="date" bind:value={startDate} required disabled={busy} /></label><label>End date<input type="date" bind:value={endDate} required disabled={busy} /></label><label>Reason<textarea bind:value={reason} required disabled={busy}></textarea></label><button disabled={busy}>{busy ? "Submitting…" : "Submit application"}</button></form><div class="panel"><h2>Applications</h2>{#if !applications.length}<p class="muted">No leave applications found.</p>{:else}<div class="list">{#each applications as item}<article><strong>{item.application?.startDate} – {item.application?.endDate}</strong><span>{item.typeName ?? "Leave"} · {item.application?.status}</span></article>{/each}</div>{/if}</div></div>{#if error}<p class="error" role="alert">{error}</p>{/if}{#if message}<p class="success" role="status">{message}</p>{/if}
<style>
  .heading { margin-bottom: 1.5rem; } .eyebrow { color: #168f76; font-size: .75rem; font-weight: 800; letter-spacing: .1em; text-transform: uppercase; } h1 { margin: .4rem 0; } .heading p:last-child, .muted { color: #52617b; } .grid { display: grid; gap: 1.25rem; grid-template-columns: minmax(18rem, 24rem) 1fr; } .panel { background: white; border: 1px solid #e1e7f0; border-radius: 1rem; padding: 1.25rem; } form { display: grid; gap: 1rem; align-content: start; } h2 { font-size: 1.1rem; margin-top: 0; } label { display: grid; gap: .4rem; font-size: .88rem; font-weight: 700; } input, select, textarea { border: 1px solid #cfd8e7; border-radius: .5rem; font: inherit; padding: .7rem; } textarea { min-height: 6rem; resize: vertical; } button { background: #168f76; border: 0; border-radius: .5rem; color: white; font-weight: 750; padding: .7rem; } .list { display: grid; gap: .7rem; } article { border: 1px solid #edf0f5; border-radius: .6rem; display: grid; gap: .3rem; padding: .8rem; } article span { color: #52617b; } .error, .success { border-radius: .5rem; padding: .7rem; } .error { background: #fff1f1; color: #a52929; } .success { background: #ecfaf5; color: #13775f; } @media (max-width: 760px) { .grid { grid-template-columns: 1fr; } }
</style>
