<script lang="ts">
  import { onMount } from "svelte";
  let organizations = $state<any[]>([]); let name = $state(""); let legalName = $state(""); let slug = $state(""); let error = $state(""); let message = $state(""); let busy = $state(false);
  async function load() { const response = await fetch("/api/platform/organizations"); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Unable to load organizations."); organizations = body.organizations ?? []; }
  async function create() { error = ""; message = ""; busy = true; try { const response = await fetch("/api/platform/organizations", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, legalName, slug, timezone: "Asia/Kolkata", currency: "INR" }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Unable to create organization."); message = "Organization created and queued for provisioning."; name = ""; legalName = ""; slug = ""; await load(); } catch (cause) { error = cause instanceof Error ? cause.message : "Unable to create organization."; } finally { busy = false; } }
  onMount(() => load().catch((cause) => error = cause instanceof Error ? cause.message : "Unable to load organizations."));
</script>
<section class="heading"><p class="eyebrow">Platform administration</p><h1>Organizations</h1><p>Create tenants and monitor their lifecycle.</p></section>
<div class="grid"><form class="panel" onsubmit={(event) => { event.preventDefault(); create(); }}><h2>Create organization</h2><label>Organization name<input bind:value={name} required disabled={busy} /></label><label>Legal name<input bind:value={legalName} required disabled={busy} /></label><label>Slug<input bind:value={slug} pattern="[a-z0-9-]+" required disabled={busy} /></label><button disabled={busy}>{busy ? "Creating…" : "Create organization"}</button>{#if error}<p class="error" role="alert">{error}</p>{/if}{#if message}<p class="success" role="status">{message}</p>{/if}</form><div class="panel"><h2>Organizations</h2>{#if !organizations.length}<p class="muted">No organizations found.</p>{:else}<div class="list">{#each organizations as organization}<article><strong>{organization.name}</strong><span>{organization.status} · {organization.slug}</span></article>{/each}</div>{/if}</div></div>
<style>
  .heading { margin-bottom: 1.5rem; } .eyebrow { color: #168f76; font-size: .75rem; font-weight: 800; letter-spacing: .1em; text-transform: uppercase; } h1 { margin: .4rem 0; } .heading p:last-child, .muted { color: #52617b; } .grid { display: grid; gap: 1.25rem; grid-template-columns: minmax(18rem, 24rem) 1fr; } .panel { background: white; border: 1px solid #e1e7f0; border-radius: 1rem; padding: 1.25rem; } form { display: grid; gap: 1rem; align-content: start; } h2 { font-size: 1.1rem; margin-top: 0; } label { display: grid; gap: .4rem; font-size: .88rem; font-weight: 700; } input { border: 1px solid #cfd8e7; border-radius: .5rem; font: inherit; padding: .7rem; } button { background: #168f76; border: 0; border-radius: .5rem; color: white; font-weight: 750; padding: .7rem; } .list { display: grid; gap: .7rem; } article { border: 1px solid #edf0f5; border-radius: .6rem; display: grid; gap: .25rem; padding: .8rem; } article span { color: #52617b; font-size: .85rem; } .error, .success { border-radius: .5rem; padding: .7rem; } .error { background: #fff1f1; color: #a52929; } .success { background: #ecfaf5; color: #13775f; } @media (max-width: 760px) { .grid { grid-template-columns: 1fr; } }
</style>
