<script lang="ts">
  import { onMount } from "svelte";
  type Run = { id: string; status: string; periodId: string; grossSalary?: number; deductions?: number; netSalary?: number };
  type Period = { id: string; label?: string; status: string; startDate?: string; endDate?: string };
  let runs = $state<Run[]>([]); let periods = $state<Period[]>([]); let periodId = $state(""); let error = $state(""); let message = $state(""); let busy = $state(false);
  async function load() { const [runsResponse, periodsResponse] = await Promise.all([fetch("/api/app/payroll/runs"), fetch("/api/app/payroll/periods")]); const runsBody = await runsResponse.json(); const periodsBody = await periodsResponse.json(); if (!runsResponse.ok) throw new Error(runsBody.error?.message ?? "Unable to load payroll runs."); runs = runsBody.runs ?? []; periods = periodsBody.periods ?? []; }
  async function calculate() { error = ""; message = ""; busy = true; try { const response = await fetch("/api/app/payroll/runs", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ periodId }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Unable to calculate payroll."); message = "Payroll run calculated."; await load(); } catch (cause) { error = cause instanceof Error ? cause.message : "Unable to calculate payroll."; } finally { busy = false; } }
  onMount(() => load().catch((cause) => error = cause instanceof Error ? cause.message : "Unable to load payroll."));
</script>
<section class="heading"><p class="eyebrow">Payroll operations</p><h1>Payroll</h1><p>Use the server-side payroll calculator and preserve approval/finalization rules.</p></section>
<div class="panel action"><label>Payroll period<select bind:value={periodId} disabled={busy}><option value="">Select a period</option>{#each periods as period}<option value={period.id}>{period.label ?? `${period.startDate ?? ""} – ${period.endDate ?? ""}`} · {period.status}</option>{/each}</select></label><button onclick={calculate} disabled={busy || !periodId}>{busy ? "Calculating…" : "Calculate payroll"}</button></div>
{#if error}<p class="error" role="alert">{error}</p>{/if}{#if message}<p class="success" role="status">{message}</p>{/if}<div class="panel"><h2>Payroll runs</h2>{#if !runs.length}<p class="muted">No payroll runs found.</p>{:else}<div class="list">{#each runs as run}<article><strong>{run.periodId}</strong><span>{run.status}</span><small>Gross: {run.grossSalary ?? "—"} · Deductions: {run.deductions ?? "—"} · Net: {run.netSalary ?? "—"}</small></article>{/each}</div>{/if}</div>
<style>
  .heading { margin-bottom: 1.5rem; } .eyebrow { color: #168f76; font-size: .75rem; font-weight: 800; letter-spacing: .1em; text-transform: uppercase; } h1 { margin: .4rem 0; } .heading p:last-child, .muted { color: #52617b; } .panel { background: white; border: 1px solid #e1e7f0; border-radius: 1rem; margin-bottom: 1rem; padding: 1.25rem; } .action { align-items: end; display: flex; gap: 1rem; max-width: 42rem; } label { display: grid; flex: 1; gap: .4rem; font-weight: 700; } select { border: 1px solid #cfd8e7; border-radius: .5rem; font: inherit; padding: .7rem; } button { background: #168f76; border: 0; border-radius: .5rem; color: white; cursor: pointer; font-weight: 750; padding: .7rem .8rem; } button:disabled { cursor: wait; opacity: .6; } .list { display: grid; gap: .7rem; } article { border: 1px solid #edf0f5; border-radius: .6rem; display: grid; gap: .3rem; padding: .8rem; } article span, article small { color: #52617b; } .error, .success { border-radius: .5rem; padding: .7rem; } .error { background: #fff1f1; color: #a52929; } .success { background: #ecfaf5; color: #13775f; } @media (max-width: 650px) { .action { align-items: stretch; flex-direction: column; } }
</style>
