<script lang="ts">
  import { onMount } from "svelte";
  type Job = { id: string; organizationId: string; jobType: string; status: string; currentStep: string; attempts: number; failureMessage?: string };
  let jobs = $state<Job[]>([]); let loading = $state(true); let busy = $state(""); let error = $state(""); let message = $state("");
  async function load() { loading = true; error = ""; try { const response = await fetch("/api/platform/provisioning"); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Unable to load provisioning jobs."); jobs = body.jobs ?? []; } catch (cause) { error = cause instanceof Error ? cause.message : "Unable to load provisioning jobs."; } finally { loading = false; } }
  async function retry(job: Job) { busy = job.organizationId; error = ""; message = ""; try { const response = await fetch(`/api/platform/provisioning/${job.organizationId}/retry`, { method: "POST", headers: { "content-type": "application/json" }, body: "{}" }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message ?? "Unable to process provisioning."); message = "Provisioning request submitted."; await load(); } catch (cause) { error = cause instanceof Error ? cause.message : "Unable to process provisioning."; } finally { busy = ""; } }
  onMount(load);
</script>
<section class="heading"><p class="eyebrow">Platform operations</p><h1>Provisioning</h1><p>Process pending organization setup jobs and retry failed operations through the existing server workflow.</p></section>
{#if error}<p class="error" role="alert">{error}</p>{/if}{#if message}<p class="success" role="status">{message}</p>{/if}
{#if loading}<p class="state">Loading provisioning jobs…</p>{:else if !jobs.length}<p class="state">No provisioning jobs found.</p>{:else}<div class="table-wrap"><table><thead><tr><th>Organization</th><th>Type</th><th>Status</th><th>Step</th><th>Attempts</th><th>Action</th></tr></thead><tbody>{#each jobs as job}<tr><td>{job.organizationId}</td><td>{job.jobType}</td><td><span class="status">{job.status}</span>{#if job.failureMessage}<small>{job.failureMessage}</small>{/if}</td><td>{job.currentStep}</td><td>{job.attempts}</td><td>{#if job.status !== "completed"}<button onclick={() => retry(job)} disabled={busy === job.organizationId}>{busy === job.organizationId ? "Processing…" : job.status === "failed" ? "Retry" : "Process"}</button>{:else}<span class="complete">Completed</span>{/if}</td></tr>{/each}</tbody></table></div>{/if}
<style>
  .heading { margin-bottom: 1.5rem; } .eyebrow { color: #168f76; font-size: .75rem; font-weight: 800; letter-spacing: .1em; text-transform: uppercase; } h1 { margin: .4rem 0; } .heading p:last-child { color: #52617b; } .table-wrap { background: white; border: 1px solid #e1e7f0; border-radius: 1rem; overflow: auto; } table { border-collapse: collapse; min-width: 760px; width: 100%; } th, td { border-bottom: 1px solid #edf0f5; padding: 1rem; text-align: left; vertical-align: top; } th { color: #52617b; font-size: .78rem; text-transform: uppercase; } small { color: #a52929; display: block; margin-top: .3rem; max-width: 14rem; } button { background: #168f76; border: 0; border-radius: .5rem; color: white; cursor: pointer; font-weight: 700; padding: .55rem .8rem; } button:disabled { cursor: wait; opacity: .6; } .status { background: #eef4ff; border-radius: 999px; display: inline-block; font-size: .8rem; padding: .3rem .55rem; } .complete { color: #13775f; font-weight: 700; } .state, .error, .success { background: white; border-radius: .75rem; padding: 1rem; } .error { background: #fff1f1; color: #a52929; } .success { background: #ecfaf5; color: #13775f; }
</style>
