<script lang="ts">
  import { onMount } from "svelte";
  const kinds = ["dashboard", "employee", "attendance", "leave", "expense", "payroll", "recruitment", "project", "task"];
  let kind = $state("dashboard"); let data = $state<unknown>(); let loading = $state(true); let error = $state(""); let exporting = $state(false);
  const label = (value: string) => value[0].toUpperCase() + value.slice(1);
  async function load() { loading = true; error = ""; try { const response = await fetch(`/api/app/reports?kind=${kind}`); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error?.message ?? "Unable to load report."); data = body.data; } catch (cause) { error = cause instanceof Error ? cause.message : "Unable to load report."; } finally { loading = false; } }
  async function exportCsv() { exporting = true; try { const response = await fetch("/api/app/reports", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ kind, export: true }) }); if (!response.ok) throw new Error("Report export failed."); const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `${kind}-report.csv`; link.click(); URL.revokeObjectURL(url); } catch (cause) { error = cause instanceof Error ? cause.message : "Report export failed."; } finally { exporting = false; } }
  onMount(load);
</script>
<svelte:head><title>Reports · SymphoWork</title></svelte:head>
<section class="heading"><div><p class="eyebrow">Workspace reporting</p><h1>Reports</h1><p>Generate tenant-scoped operational reports using the existing reporting service.</p></div><div class="actions"><select aria-label="Report type" bind:value={kind} onchange={load}>{#each kinds as option}<option value={option}>{label(option)}</option>{/each}</select><button onclick={exportCsv} disabled={exporting || kind === "dashboard"}>{exporting ? "Exporting…" : "Export CSV"}</button></div></section>
{#if loading}<div class="state">Loading report…</div>{:else if error}<div class="state error" role="alert">{error}<button class="secondary" onclick={load}>Try again</button></div>{:else}<div class="state"><h2>{label(kind)} report</h2>{#if data}<pre>{JSON.stringify(data, null, 2)}</pre>{:else}<p>No report data is available for this context.</p>{/if}</div>{/if}
<style>
  .heading { align-items: end; display: flex; gap: 1rem; justify-content: space-between; margin-bottom: 1.5rem; } .eyebrow { color: #168f76; font-size: .75rem; font-weight: 800; letter-spacing: .1em; text-transform: uppercase; } h1 { margin: .4rem 0; } p { color: #52617b; margin: .35rem 0 0; } .actions { display: flex; gap: .5rem; } select, button { border: 1px solid #d7dfeb; border-radius: .55rem; font: inherit; padding: .65rem .8rem; } button { background: #13714f; color: white; cursor: pointer; font-weight: 700; } button:disabled { cursor: wait; opacity: .6; } .secondary { background: white; color: #18304e; } .state { background: white; border: 1px solid #e1e7f0; border-radius: 1rem; color: #52617b; padding: 1.25rem; } .state h2 { color: #18304e; margin-top: 0; } .error { background: #fff7f7; border-color: #f1c4c4; color: #a52929; display: flex; flex-direction: column; gap: .7rem; } pre { background: #f6f8fb; border-radius: .6rem; max-height: 36rem; overflow: auto; padding: 1rem; white-space: pre-wrap; }
  @media (max-width: 700px) { .heading, .actions { align-items: stretch; flex-direction: column; } }
</style>
