<script lang="ts">
  import { goto } from "$app/navigation";
  let currentPassword = $state(""); let password = $state(""); let confirmPassword = $state(""); let error = $state(""); let message = $state(""); let busy = $state(false);
  async function submit() { error = ""; message = ""; if (password !== confirmPassword) { error = "Passwords do not match."; return; } busy = true; try { const response = await fetch("/api/auth/change-password", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ currentPassword, password }) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error?.message ?? "Unable to change password."); message = "Password changed successfully."; setTimeout(() => goto("/app"), 500); } catch (cause) { error = cause instanceof Error ? cause.message : "Unable to change password."; } finally { busy = false; } }
</script>
<section class="card"><p class="eyebrow">Account security</p><h1>Change password</h1><form onsubmit={(event) => { event.preventDefault(); submit(); }}><label>Current password<input type="password" bind:value={currentPassword} required disabled={busy} /></label><label>New password<input type="password" bind:value={password} minlength="12" required disabled={busy} /></label><label>Confirm password<input type="password" bind:value={confirmPassword} minlength="12" required disabled={busy} /></label>{#if error}<p class="error" role="alert">{error}</p>{/if}{#if message}<p class="success" role="status">{message}</p>{/if}<button disabled={busy}>{busy ? "Updating…" : "Change password"}</button></form></section>
<style>
  .card { background: white; border: 1px solid #e1e7f0; border-radius: 1rem; margin: auto; max-width: 32rem; padding: 2rem; } .eyebrow { color: #168f76; font-size: .78rem; font-weight: 800; letter-spacing: .12em; text-transform: uppercase; } form { display: grid; gap: 1rem; margin-top: 1.5rem; } label { display: grid; gap: .4rem; font-weight: 700; } input { border: 1px solid #cfd8e7; border-radius: .5rem; font: inherit; padding: .7rem; } button { background: #168f76; border: 0; border-radius: .5rem; color: white; font-weight: 750; padding: .7rem; } .error, .success { border-radius: .5rem; padding: .7rem; } .error { background: #fff1f1; color: #a52929; } .success { background: #ecfaf5; color: #13775f; }
</style>
