import { describe, expect, it } from "vitest";
import { contentHash, embeddingIdempotencyKey, interpretRecruiterQuery, matchCandidateToJob, normalizeSkill, rankMatchResults } from "./matching";

const candidate = { id: "candidate-1", fullName: "Asha", location: "Chennai", totalExperience: 8, relevantExperience: 4.2, noticePeriodDays: 30, highestEducation: "B.Tech Computer Science", skills: [{ name: "ReactJS", yearsExperience: 4 }, { name: "TypeScript", yearsExperience: 3 }] };
describe("recruiter intelligence matching", () => {
  it("normalizes configured aliases without conflating unrelated skills", () => { expect(normalizeSkill("ReactJS")).toBe("react"); expect(normalizeSkill("Postgres")).toBe("postgresql"); expect(normalizeSkill("Java")).not.toBe("javascript"); });
  it("matches required and preferred skills separately", () => { const result = matchCandidateToJob(candidate, { requiredSkills: ["React"], preferredSkills: ["AWS"], experienceMin: 3 }); expect(result.dimensions.find((item) => item.dimension === "required_skills")?.result).toBe("matched"); expect(result.dimensions.find((item) => item.dimension === "preferred_skills")?.result).toBe("missing"); expect(result.gaps[0]).toContain("AWS"); });
  it("does not treat missing information as failure", () => { const result = matchCandidateToJob({ ...candidate, noticePeriodDays: null, location: null }, { requiredSkills: [], preferredSkills: [], location: "Chennai", noticePeriodMax: 30 }); expect(result.dimensions.every((item) => item.result === "unknown")).toBe(true); expect(result.gaps).toHaveLength(0); });
  it("distinguishes relevant experience from total experience", () => { const result = matchCandidateToJob({ ...candidate, totalExperience: 8, relevantExperience: 2 }, { requiredSkills: [], preferredSkills: [], experienceMin: 5 }); expect(result.dimensions.find((item) => item.dimension === "relevant_experience")?.result).toBe("partial"); });
  it("interprets structured query criteria and keeps vague queries broad", () => { const interpreted = interpretRecruiterQuery("Find React developers with 4+ years in Chennai available within 30 days"); expect(interpreted.skills).toContain("react"); expect(interpreted.experienceMin).toBe(4); expect(interpreted.noticePeriodMax).toBe(30); expect(interpreted.locations).toContain("Chennai"); expect(interpretRecruiterQuery("Good frontend people").ambiguityFlags.length).toBeGreaterThan(0); });
  it("ranks deterministically by indicator then candidate id", () => { const first = matchCandidateToJob(candidate, { requiredSkills: ["React"], preferredSkills: [] }); const second = matchCandidateToJob({ ...candidate, id: "candidate-2", skills: [] }, { requiredSkills: ["React"], preferredSkills: [] }); expect(rankMatchResults([second, first]).map((item) => item.candidateId)).toEqual(["candidate-1", "candidate-2"]); });
  it("creates stable embedding idempotency keys", () => { expect(embeddingIdempotencyKey("candidate", "candidate-1", "React TypeScript", "v1")).toBe(embeddingIdempotencyKey("candidate", "candidate-1", "React TypeScript", "v1")); expect(contentHash("x")).toHaveLength(64); });
});
