import { NextResponse } from "next/server";
import { errorResponse, AppError } from "@/lib/errors";
import { resolveTenantContext } from "@/modules/tenancy/context";
import { assignSalaryStructure } from "@/modules/payroll/service";
import { desc, eq } from "drizzle-orm";
import { db } from "@/db/client";
import { employeeSalaryAssignments, employees, salaryStructures } from "@/db/schema";
import { authorize } from "@/modules/tenancy/authorization";
export async function GET() { try { const tenant = await resolveTenantContext(); if (!tenant.organization) throw new AppError("FORBIDDEN", "Organization context is required.", 403); await authorize({ organizationId: tenant.organization.id, permission: "payroll.configure" }); return NextResponse.json({ success: true, assignments: await db.select({ assignment: employeeSalaryAssignments, employeeName: employees.displayName, structureName: salaryStructures.name }).from(employeeSalaryAssignments).innerJoin(employees, eq(employeeSalaryAssignments.employeeId, employees.id)).innerJoin(salaryStructures, eq(employeeSalaryAssignments.structureId, salaryStructures.id)).where(eq(employeeSalaryAssignments.organizationId, tenant.organization.id)).orderBy(desc(employeeSalaryAssignments.effectiveFrom)) }); } catch (error) { return errorResponse(error); } }
export async function POST(request: Request) { try { const tenant = await resolveTenantContext(); if (!tenant.organization) throw new AppError("FORBIDDEN", "Organization context is required.", 403); const body = await request.json() as { employeeId?: string; structureId?: string; effectiveFrom?: string; effectiveTo?: string; revisionReason?: string; notes?: string }; if (!body.employeeId || !body.structureId || !body.effectiveFrom) throw new AppError("VALIDATION_ERROR", "Employee, structure, and effective start date are required.", 400); return NextResponse.json({ success: true, assignment: await assignSalaryStructure({ organizationId: tenant.organization.id, userId: tenant.user.id, ...body } as Parameters<typeof assignSalaryStructure>[0]) }, { status: 201 }); } catch (error) { return errorResponse(error); } }
