import { and, eq, sql } from "drizzle-orm";
import { db } from "@/db/client";
import { attendanceRecords, atsApplications, collaborationProjects, collaborationTasks, employees, expenseClaims, leaveApplications, payrollRuns } from "@/db/schema";
import { authorize } from "@/modules/tenancy/authorization";
export type ReportFilter = { from?: string; to?: string; departmentId?: string; employeeId?: string; projectId?: string; status?: string };
async function count(table: typeof employees, organizationId: string, filters: ReportFilter = {}) { return db.select({ count: sql<number>`count(*)` }).from(table).where(and(eq(table.organizationId, organizationId), filters.status && "status" in table ? eq((table as typeof employees).status, filters.status as never) : undefined)); }
export async function employeeReport(input: { organizationId: string; userId: string; filters?: ReportFilter }) { await authorize({ organizationId: input.organizationId, permission: "report.employee" }); const [total] = await count(employees, input.organizationId, input.filters); const [active] = await db.select({ count: sql<number>`count(*)` }).from(employees).where(and(eq(employees.organizationId, input.organizationId), eq(employees.status, "active"))); return { report: "employee", metrics: { total: Number(total?.count ?? 0), active: Number(active?.count ?? 0) } }; }
export async function operationalReport(input: { organizationId: string; userId: string; kind: "attendance" | "leave" | "expense" | "payroll" | "recruitment" | "project" | "task"; filters?: ReportFilter }) { const permission = `report.${input.kind}` as "report.attendance" | "report.leave" | "report.expense" | "report.payroll" | "report.recruitment" | "report.project" | "report.task"; await authorize({ organizationId: input.organizationId, permission }); const table = { attendance: attendanceRecords, leave: leaveApplications, expense: expenseClaims, payroll: payrollRuns, recruitment: atsApplications, project: collaborationProjects, task: collaborationTasks }[input.kind]; const [total] = await db.select({ count: sql<number>`count(*)` }).from(table).where(eq(table.organizationId, input.organizationId)); const statusRows = "status" in table ? await db.select({ status: (table as typeof collaborationTasks).status, count: sql<number>`count(*)` }).from(table).where(eq(table.organizationId, input.organizationId)).groupBy((table as typeof collaborationTasks).status) : []; return { report: input.kind, metrics: { total: Number(total?.count ?? 0) }, breakdown: statusRows.map((row) => ({ status: String(row.status), count: Number(row.count) })) }; }
export async function exportReportCsv(input: { organizationId: string; userId: string; kind: "employee" | "attendance" | "leave" | "expense" | "payroll" | "recruitment" | "project" | "task"; filters?: ReportFilter }) { await authorize({ organizationId: input.organizationId, permission: "report.export" }); const report = input.kind === "employee" ? await employeeReport(input) : await operationalReport({ ...input, kind: input.kind }); const rows = ["report,metric,value", ...Object.entries(report.metrics).map(([key, value]) => `${input.kind},${key},${value}`)]; return rows.join("\n"); }
