import { and, count, eq, gte, lte, sql } from "drizzle-orm";
import { db } from "@/db/client";
import { attendanceRecords, atsApplications, atsCandidates, atsInterviews, atsJobs, atsRequisitions, collaborationProjects, collaborationTasks, departments, employees, expenseClaims, leaveApplications, payrollRuns } from "@/db/schema";
import { authorize, can } from "@/modules/tenancy/authorization";

export type ReportFilter = { from?: string; to?: string; departmentId?: string; employeeId?: string; projectId?: string; status?: string };
function dateRange(column: typeof employees.joiningDate | typeof attendanceRecords.attendanceDate | typeof expenseClaims.expenseDate, filters: ReportFilter = {}) { return and(filters.from ? gte(column, filters.from) : undefined, filters.to ? lte(column, filters.to) : undefined); }
function statusFilter(table: { status: unknown }, filters: ReportFilter = {}) { return filters.status ? eq(table.status as never, filters.status as never) : undefined; }
async function scalar<T>(query: Promise<Array<{ value: T }>>, fallback: T) { const [row] = await query; return row?.value ?? fallback; }
async function groupedStatus(table: typeof attendanceRecords | typeof leaveApplications | typeof expenseClaims | typeof payrollRuns, organizationId: string, filters: ReportFilter = {}) { return db.select({ status: table.status, value: count() }).from(table).where(and(eq(table.organizationId, organizationId), statusFilter(table, filters))).groupBy(table.status); }

export async function employeeReport(input: { organizationId: string; userId: string; filters?: ReportFilter }) { await authorize({ organizationId: input.organizationId, permission: "report.employee" }); const filters = input.filters ?? {}; const base = and(eq(employees.organizationId, input.organizationId), filters.departmentId ? eq(employees.departmentId, filters.departmentId) : undefined, filters.employeeId ? eq(employees.id, filters.employeeId) : undefined); const [total, active, inactive, recent] = await Promise.all([scalar(db.select({ value: count() }).from(employees).where(and(base, dateRange(employees.joiningDate, filters))), 0), scalar(db.select({ value: count() }).from(employees).where(and(base, eq(employees.status, "active"))), 0), scalar(db.select({ value: count() }).from(employees).where(and(base, eq(employees.status, "inactive"))), 0), scalar(db.select({ value: count() }).from(employees).where(and(base, gte(employees.joiningDate, filters.from ?? new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().slice(0, 10)))), 0)]); const departmentsRows = await db.select({ department: departments.name, value: count() }).from(employees).leftJoin(departments, eq(employees.departmentId, departments.id)).where(base).groupBy(departments.name); return { report: "employee", metrics: { total: Number(total), active: Number(active), inactive: Number(inactive), newEmployees: Number(recent) }, breakdown: departmentsRows.map((row) => ({ label: row.department ?? "Unassigned", value: Number(row.value) })) }; }

export async function reportDashboard(input: { organizationId: string; userId: string; filters?: ReportFilter }) {
  const filters = input.filters ?? {};
  const available = { employee: await can({ userId: input.userId, organizationId: input.organizationId, permission: "report.employee" }), attendance: await can({ userId: input.userId, organizationId: input.organizationId, permission: "report.attendance" }), leave: await can({ userId: input.userId, organizationId: input.organizationId, permission: "report.leave" }), expense: await can({ userId: input.userId, organizationId: input.organizationId, permission: "report.expense" }), recruitment: await can({ userId: input.userId, organizationId: input.organizationId, permission: "report.recruitment" }), project: await can({ userId: input.userId, organizationId: input.organizationId, permission: "report.project" }), task: await can({ userId: input.userId, organizationId: input.organizationId, permission: "report.task" }), payroll: await can({ userId: input.userId, organizationId: input.organizationId, permission: "report.payroll" }) };
  const result: Record<string, unknown> = { available };
  if (available.employee) result.workforce = await employeeReport(input);
  if (available.attendance) { const rows = await groupedStatus(attendanceRecords, input.organizationId, filters); result.attendance = { total: rows.reduce((sum, row) => sum + Number(row.value), 0), breakdown: rows.map((row) => ({ status: String(row.status), value: Number(row.value) })) }; }
  if (available.leave) { const rows = await groupedStatus(leaveApplications, input.organizationId, filters); result.leave = { total: rows.reduce((sum, row) => sum + Number(row.value), 0), breakdown: rows.map((row) => ({ status: String(row.status), value: Number(row.value) })) }; }
  if (available.expense) { const [claims, amount] = await Promise.all([groupedStatus(expenseClaims, input.organizationId, filters), db.select({ value: sql<number>`coalesce(sum(${expenseClaims.totalAmount}), 0)` }).from(expenseClaims).where(and(eq(expenseClaims.organizationId, input.organizationId), dateRange(expenseClaims.expenseDate, filters)))]); result.expenses = { total: claims.reduce((sum, row) => sum + Number(row.value), 0), amount: Number(amount[0]?.value ?? 0), breakdown: claims.map((row) => ({ status: String(row.status), value: Number(row.value) })) }; }
  if (available.recruitment) { const [requisitions, jobs, applications, candidates, interviews] = await Promise.all([scalar(db.select({ value: count() }).from(atsRequisitions).where(and(eq(atsRequisitions.organizationId, input.organizationId), statusFilter(atsRequisitions, filters))), 0), scalar(db.select({ value: count() }).from(atsJobs).where(and(eq(atsJobs.organizationId, input.organizationId), statusFilter(atsJobs, filters))), 0), scalar(db.select({ value: count() }).from(atsApplications).where(eq(atsApplications.organizationId, input.organizationId)), 0), scalar(db.select({ value: count() }).from(atsCandidates).where(eq(atsCandidates.organizationId, input.organizationId)), 0), scalar(db.select({ value: count() }).from(atsInterviews).where(eq(atsInterviews.organizationId, input.organizationId)), 0)]); result.recruitment = { requisitions: Number(requisitions), jobs: Number(jobs), applications: Number(applications), candidates: Number(candidates), interviews: Number(interviews) }; }
  if (available.project || available.task) { const [projects, tasks, completed, overdue] = await Promise.all([scalar(db.select({ value: count() }).from(collaborationProjects).where(and(eq(collaborationProjects.organizationId, input.organizationId), eq(collaborationProjects.status, "active"))), 0), scalar(db.select({ value: count() }).from(collaborationTasks).where(and(eq(collaborationTasks.organizationId, input.organizationId), filters.projectId ? eq(collaborationTasks.projectId, filters.projectId) : undefined)), 0), scalar(db.select({ value: count() }).from(collaborationTasks).where(and(eq(collaborationTasks.organizationId, input.organizationId), eq(collaborationTasks.status, "completed"), filters.projectId ? eq(collaborationTasks.projectId, filters.projectId) : undefined)), 0), scalar(db.select({ value: count() }).from(collaborationTasks).where(and(eq(collaborationTasks.organizationId, input.organizationId), lte(collaborationTasks.dueDate, new Date().toISOString().slice(0, 10)), sql`${collaborationTasks.status} not in ('completed', 'cancelled')`)), 0)]); result.projectsTasks = { activeProjects: available.project ? Number(projects) : null, totalTasks: available.task ? Number(tasks) : null, completedTasks: available.task ? Number(completed) : null, overdueTasks: available.task ? Number(overdue) : null }; }
  if (available.payroll) { const [runs, totals] = await Promise.all([groupedStatus(payrollRuns, input.organizationId, filters), db.select({ gross: sql<number>`coalesce(sum(${payrollRuns.grossTotal}), 0)`, deductions: sql<number>`coalesce(sum(${payrollRuns.deductionTotal}), 0)`, employer: sql<number>`coalesce(sum(${payrollRuns.employerContributionTotal}), 0)`, net: sql<number>`coalesce(sum(${payrollRuns.netTotal}), 0)` }).from(payrollRuns).where(eq(payrollRuns.organizationId, input.organizationId))]); result.payroll = { runs: runs.map((row) => ({ status: String(row.status), value: Number(row.value) })), totals: totals[0] ?? { gross: 0, deductions: 0, employer: 0, net: 0 } }; }
  return result;
}

export async function operationalReport(input: { organizationId: string; userId: string; kind: "attendance" | "leave" | "expense" | "payroll" | "recruitment" | "project" | "task"; filters?: ReportFilter }) { const permission = `report.${input.kind}` as "report.attendance" | "report.leave" | "report.expense" | "report.payroll" | "report.recruitment" | "report.project" | "report.task"; await authorize({ organizationId: input.organizationId, permission }); const table = { attendance: attendanceRecords, leave: leaveApplications, expense: expenseClaims, payroll: payrollRuns, recruitment: atsApplications, project: collaborationProjects, task: collaborationTasks }[input.kind]; const [total] = await db.select({ count: sql<number>`count(*)` }).from(table).where(eq(table.organizationId, input.organizationId)); const statusRows = "status" in table ? await db.select({ status: (table as typeof collaborationTasks).status, count: sql<number>`count(*)` }).from(table).where(eq(table.organizationId, input.organizationId)).groupBy((table as typeof collaborationTasks).status) : []; return { report: input.kind, metrics: { total: Number(total?.count ?? 0) }, breakdown: statusRows.map((row) => ({ status: String(row.status), count: Number(row.count) })) }; }
export async function exportReportCsv(input: { organizationId: string; userId: string; kind: "employee" | "attendance" | "leave" | "expense" | "payroll" | "recruitment" | "project" | "task"; filters?: ReportFilter }) { await authorize({ organizationId: input.organizationId, permission: "report.export" }); const report = input.kind === "employee" ? await employeeReport(input) : await operationalReport({ ...input, kind: input.kind }); const rows = ["report,metric,value", ...Object.entries(report.metrics).map(([key, value]) => `${input.kind},${key},${value}`)]; return rows.join("\n"); }
