import { boolean, date, index, integer, pgEnum, pgTable, text, time, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";

const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
};

export const userStatus = pgEnum("user_status", ["active", "disabled"]);
export const platformRole = pgEnum("platform_role", ["NONE", "PLATFORM_OWNER"]);
export const organizationStatus = pgEnum("organization_status", ["pending", "active", "suspended", "rejected", "archived"]);
export const membershipStatus = pgEnum("membership_status", ["invited", "active", "suspended", "removed"]);
export const invitationStatus = pgEnum("invitation_status", ["pending", "accepted", "expired", "revoked"]);
export const subscriptionStatus = pgEnum("subscription_status", ["pending", "active", "suspended", "cancelled", "expired"]);
export const provisioningStatus = pgEnum("provisioning_status", ["pending", "running", "completed", "failed", "retrying"]);
export const planCode = pgEnum("plan_code", ["FREE", "STARTER", "PROFESSIONAL", "ENTERPRISE"]);
export const masterDataStatus = pgEnum("master_data_status", ["active", "inactive"]);
export const employeeStatus = pgEnum("employee_status", ["invited", "onboarding", "active", "probation", "confirmed", "notice_period", "inactive", "resigned", "terminated", "exited"]);
export const onboardingStatus = pgEnum("onboarding_status", ["not_started", "invited", "in_progress", "completed", "blocked"]);
export const onboardingItemStatus = pgEnum("onboarding_item_status", ["pending", "completed", "blocked"]);
export const documentStatus = pgEnum("document_status", ["pending", "verified", "rejected", "expired"]);

export const users = pgTable("users", {
  id: uuid("id").defaultRandom().primaryKey(), email: varchar("email", { length: 320 }).notNull().unique(), fullName: varchar("full_name", { length: 160 }).notNull(), passwordHash: text("password_hash").notNull(), status: userStatus("status").default("active").notNull(), platformRole: platformRole("platform_role").default("NONE").notNull(), emailVerifiedAt: timestamp("email_verified_at", { withTimezone: true }), ...timestamps,
}, (table) => [index("users_email_idx").on(table.email)]);

export const organizations = pgTable("organizations", {
  id: uuid("id").defaultRandom().primaryKey(), name: varchar("name", { length: 160 }).notNull(), legalName: varchar("legal_name", { length: 240 }).notNull(), slug: varchar("slug", { length: 80 }).notNull().unique(), status: organizationStatus("status").default("pending").notNull(), timezone: varchar("timezone", { length: 80 }).notNull().default("UTC"), currency: varchar("currency", { length: 3 }).notNull().default("INR"), website: varchar("website", { length: 240 }), contactEmail: varchar("contact_email", { length: 320 }), contactPhone: varchar("contact_phone", { length: 40 }), addressLine1: varchar("address_line_1", { length: 240 }), addressLine2: varchar("address_line_2", { length: 240 }), city: varchar("city", { length: 120 }), state: varchar("state", { length: 120 }), country: varchar("country", { length: 120 }), postalCode: varchar("postal_code", { length: 20 }), dateFormat: varchar("date_format", { length: 40 }).default("dd/MM/yyyy").notNull(), fiscalYearStartMonth: integer("fiscal_year_start_month").default(4).notNull(), employeeIdPrefix: varchar("employee_id_prefix", { length: 20 }).default("EMP").notNull(), employeeIdNext: integer("employee_id_next").default(1).notNull(), employeeIdPadding: integer("employee_id_padding").default(4).notNull(), ...timestamps,
}, (table) => [index("organizations_status_idx").on(table.status)]);

export const roles = pgTable("roles", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").references(() => organizations.id, { onDelete: "cascade" }), name: varchar("name", { length: 80 }).notNull(), key: varchar("key", { length: 80 }).notNull(), description: varchar("description", { length: 240 }), isSystem: boolean("is_system").default(false).notNull(), ...timestamps,
}, (table) => [uniqueIndex("roles_org_key_idx").on(table.organizationId, table.key)]);

export const permissions = pgTable("permissions", { id: uuid("id").defaultRandom().primaryKey(), key: varchar("key", { length: 120 }).notNull().unique(), description: varchar("description", { length: 240 }) });
export const rolePermissions = pgTable("role_permissions", { roleId: uuid("role_id").notNull().references(() => roles.id, { onDelete: "cascade" }), permissionId: uuid("permission_id").notNull().references(() => permissions.id, { onDelete: "cascade" }) }, (table) => [uniqueIndex("role_permissions_pk").on(table.roleId, table.permissionId)]);

export const memberships = pgTable("memberships", {
  id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").notNull().unique().references(() => users.id, { onDelete: "cascade" }), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), roleId: uuid("role_id").notNull().references(() => roles.id), status: membershipStatus("status").default("invited").notNull(), ...timestamps,
}, (table) => [index("memberships_org_idx").on(table.organizationId), index("memberships_user_status_idx").on(table.userId, table.status)]);

export const sessions = pgTable("sessions", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), tokenHash: varchar("token_hash", { length: 64 }).notNull().unique(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).defaultNow().notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (table) => [index("sessions_user_idx").on(table.userId), index("sessions_expiry_idx").on(table.expiresAt)]);
export const emailVerificationTokens = pgTable("email_verification_tokens", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), tokenHash: varchar("token_hash", { length: 64 }).notNull().unique(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), usedAt: timestamp("used_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const passwordResetTokens = pgTable("password_reset_tokens", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), tokenHash: varchar("token_hash", { length: 64 }).notNull().unique(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), usedAt: timestamp("used_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });

export const plans = pgTable("plans", { id: uuid("id").defaultRandom().primaryKey(), code: planCode("code").notNull().unique(), name: varchar("name", { length: 80 }).notNull(), description: varchar("description", { length: 240 }), maxUsers: integer("max_users"), maxStorageBytes: integer("max_storage_bytes"), billingInterval: varchar("billing_interval", { length: 20 }).notNull().default("monthly"), active: boolean("active").default(true).notNull(), ...timestamps });
export const planFeatures = pgTable("plan_features", { id: uuid("id").defaultRandom().primaryKey(), planId: uuid("plan_id").notNull().references(() => plans.id, { onDelete: "cascade" }), featureKey: varchar("feature_key", { length: 120 }).notNull(), enabled: boolean("enabled").default(true).notNull(), limitValue: integer("limit_value") }, (table) => [uniqueIndex("plan_features_key_idx").on(table.planId, table.featureKey)]);
export const subscriptions = pgTable("subscriptions", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().unique().references(() => organizations.id, { onDelete: "cascade" }), planId: uuid("plan_id").notNull().references(() => plans.id), status: subscriptionStatus("status").default("pending").notNull(), startsAt: timestamp("starts_at", { withTimezone: true }), endsAt: timestamp("ends_at", { withTimezone: true }), ...timestamps });

export const invitations = pgTable("invitations", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), employeeId: uuid("employee_id").references(() => employees.id, { onDelete: "set null" }), invitationType: varchar("invitation_type", { length: 40 }).notNull().default("organization_admin"), invitedEmail: varchar("invited_email", { length: 320 }).notNull(), intendedRole: varchar("intended_role", { length: 80 }).notNull(), tokenHash: varchar("token_hash", { length: 64 }).notNull().unique(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), status: invitationStatus("status").default("pending").notNull(), acceptedAt: timestamp("accepted_at", { withTimezone: true }), ...timestamps }, (table) => [index("invitations_email_idx").on(table.invitedEmail), index("invitations_org_status_idx").on(table.organizationId, table.status), index("invitations_employee_idx").on(table.employeeId)]);
export const provisioningJobs = pgTable("provisioning_jobs", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().unique().references(() => organizations.id, { onDelete: "cascade" }), jobType: varchar("job_type", { length: 80 }).notNull().default("organization.provision"), status: provisioningStatus("status").default("pending").notNull(), currentStep: varchar("current_step", { length: 80 }).notNull().default("created"), attempts: integer("attempts").default(0).notNull(), startedAt: timestamp("started_at", { withTimezone: true }), completedAt: timestamp("completed_at", { withTimezone: true }), failureMessage: varchar("failure_message", { length: 1000 }), ...timestamps }, (table) => [index("provisioning_status_idx").on(table.status)]);
export const auditLogs = pgTable("audit_logs", { id: uuid("id").defaultRandom().primaryKey(), actorUserId: uuid("actor_user_id").references(() => users.id, { onDelete: "set null" }), organizationId: uuid("organization_id").references(() => organizations.id, { onDelete: "set null" }), action: varchar("action", { length: 120 }).notNull(), resource: varchar("resource", { length: 120 }).notNull(), resourceId: uuid("resource_id"), requestId: varchar("request_id", { length: 80 }), metadata: text("metadata"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (table) => [index("audit_org_created_idx").on(table.organizationId, table.createdAt), index("audit_actor_created_idx").on(table.actorUserId, table.createdAt)]);
export const systemConfig = pgTable("system_config", { key: varchar("key", { length: 120 }).primaryKey(), value: varchar("value", { length: 2000 }).notNull(), ...timestamps });

export const departments = pgTable("departments", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), name: varchar("name", { length: 120 }).notNull(), code: varchar("code", { length: 40 }).notNull(), description: varchar("description", { length: 500 }), headEmployeeId: uuid("head_employee_id"), status: masterDataStatus("status").default("active").notNull(), ...timestamps }, (table) => [uniqueIndex("departments_org_code_idx").on(table.organizationId, table.code), index("departments_org_status_idx").on(table.organizationId, table.status)]);
export const designations = pgTable("designations", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), name: varchar("name", { length: 120 }).notNull(), code: varchar("code", { length: 40 }).notNull(), description: varchar("description", { length: 500 }), level: integer("level"), status: masterDataStatus("status").default("active").notNull(), ...timestamps }, (table) => [uniqueIndex("designations_org_code_idx").on(table.organizationId, table.code), index("designations_org_status_idx").on(table.organizationId, table.status)]);
export const locations = pgTable("locations", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), name: varchar("name", { length: 120 }).notNull(), code: varchar("code", { length: 40 }).notNull(), addressLine1: varchar("address_line_1", { length: 240 }), addressLine2: varchar("address_line_2", { length: 240 }), city: varchar("city", { length: 120 }), state: varchar("state", { length: 120 }), country: varchar("country", { length: 120 }), postalCode: varchar("postal_code", { length: 20 }), timezone: varchar("timezone", { length: 80 }).default("UTC").notNull(), status: masterDataStatus("status").default("active").notNull(), ...timestamps }, (table) => [uniqueIndex("locations_org_code_idx").on(table.organizationId, table.code), index("locations_org_status_idx").on(table.organizationId, table.status)]);
export const employmentTypes = pgTable("employment_types", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), name: varchar("name", { length: 80 }).notNull(), code: varchar("code", { length: 40 }).notNull(), status: masterDataStatus("status").default("active").notNull(), ...timestamps }, (table) => [uniqueIndex("employment_types_org_code_idx").on(table.organizationId, table.code)]);
export const shifts = pgTable("shifts", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), name: varchar("name", { length: 100 }).notNull(), code: varchar("code", { length: 40 }).notNull(), startTime: time("start_time").notNull(), endTime: time("end_time").notNull(), breakMinutes: integer("break_minutes").default(0).notNull(), graceMinutes: integer("grace_minutes").default(0).notNull(), overnight: boolean("overnight").default(false).notNull(), status: masterDataStatus("status").default("active").notNull(), ...timestamps }, (table) => [uniqueIndex("shifts_org_code_idx").on(table.organizationId, table.code)]);
export const workingDays = pgTable("working_days", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), dayOfWeek: integer("day_of_week").notNull(), isWorkingDay: boolean("is_working_day").default(true).notNull(), ...timestamps }, (table) => [uniqueIndex("working_days_org_day_idx").on(table.organizationId, table.dayOfWeek)]);
export const holidays = pgTable("holidays", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), name: varchar("name", { length: 160 }).notNull(), holidayDate: date("holiday_date").notNull(), category: varchar("category", { length: 60 }).default("public").notNull(), description: varchar("description", { length: 500 }), status: masterDataStatus("status").default("active").notNull(), ...timestamps }, (table) => [uniqueIndex("holidays_org_date_name_idx").on(table.organizationId, table.holidayDate, table.name), index("holidays_org_date_idx").on(table.organizationId, table.holidayDate)]);
export const teams = pgTable("teams", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), departmentId: uuid("department_id").references(() => departments.id, { onDelete: "set null" }), name: varchar("name", { length: 120 }).notNull(), code: varchar("code", { length: 40 }).notNull(), description: varchar("description", { length: 500 }), teamLeadEmployeeId: uuid("team_lead_employee_id"), status: masterDataStatus("status").default("active").notNull(), ...timestamps }, (table) => [uniqueIndex("teams_org_code_idx").on(table.organizationId, table.code), index("teams_org_department_idx").on(table.organizationId, table.departmentId)]);

export const employees = pgTable("employees", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), userId: uuid("user_id").unique().references(() => users.id, { onDelete: "set null" }), employeeId: varchar("employee_id", { length: 40 }).notNull(), firstName: varchar("first_name", { length: 80 }).notNull(), middleName: varchar("middle_name", { length: 80 }), lastName: varchar("last_name", { length: 80 }).notNull(), displayName: varchar("display_name", { length: 180 }).notNull(), profilePhotoKey: varchar("profile_photo_key", { length: 500 }), dateOfBirth: date("date_of_birth"), gender: varchar("gender", { length: 40 }), maritalStatus: varchar("marital_status", { length: 40 }), nationality: varchar("nationality", { length: 80 }), personalEmail: varchar("personal_email", { length: 320 }), workEmail: varchar("work_email", { length: 320 }), phone: varchar("phone", { length: 40 }), alternatePhone: varchar("alternate_phone", { length: 40 }), addressLine1: varchar("address_line_1", { length: 240 }), addressLine2: varchar("address_line_2", { length: 240 }), city: varchar("city", { length: 120 }), state: varchar("state", { length: 120 }), country: varchar("country", { length: 120 }), postalCode: varchar("postal_code", { length: 20 }), joiningDate: date("joining_date"), employmentTypeId: uuid("employment_type_id").references(() => employmentTypes.id), departmentId: uuid("department_id").references(() => departments.id), designationId: uuid("designation_id").references(() => designations.id), reportingManagerId: uuid("reporting_manager_id"), teamId: uuid("team_id").references(() => teams.id), locationId: uuid("location_id").references(() => locations.id), shiftId: uuid("shift_id").references(() => shifts.id), status: employeeStatus("status").default("invited").notNull(), probationStart: date("probation_start"), probationEnd: date("probation_end"), confirmationDate: date("confirmation_date"), ...timestamps }, (table) => [uniqueIndex("employees_org_employee_id_idx").on(table.organizationId, table.employeeId), index("employees_org_status_idx").on(table.organizationId, table.status), index("employees_org_department_idx").on(table.organizationId, table.departmentId), index("employees_org_designation_idx").on(table.organizationId, table.designationId), index("employees_org_manager_idx").on(table.organizationId, table.reportingManagerId), index("employees_org_team_idx").on(table.organizationId, table.teamId), index("employees_org_location_idx").on(table.organizationId, table.locationId), index("employees_joining_date_idx").on(table.organizationId, table.joiningDate)]);
export const employeeHistory = pgTable("employee_history", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), employeeId: uuid("employee_id").notNull().references(() => employees.id, { onDelete: "cascade" }), eventType: varchar("event_type", { length: 80 }).notNull(), previousValue: text("previous_value"), newValue: text("new_value"), reason: varchar("reason", { length: 500 }), actorUserId: uuid("actor_user_id").references(() => users.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (table) => [index("employee_history_idx").on(table.organizationId, table.employeeId, table.createdAt)]);
export const employeeDocuments = pgTable("employee_documents", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), employeeId: uuid("employee_id").notNull().references(() => employees.id, { onDelete: "cascade" }), documentType: varchar("document_type", { length: 80 }).notNull(), fileName: varchar("file_name", { length: 240 }).notNull(), storageKey: varchar("storage_key", { length: 500 }).notNull(), status: documentStatus("status").default("pending").notNull(), uploadedByUserId: uuid("uploaded_by_user_id").references(() => users.id, { onDelete: "set null" }), uploadedAt: timestamp("uploaded_at", { withTimezone: true }).defaultNow().notNull(), expiresAt: date("expires_at") }, (table) => [index("employee_documents_idx").on(table.organizationId, table.employeeId)]);
export const onboarding = pgTable("onboarding", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), employeeId: uuid("employee_id").notNull().unique().references(() => employees.id, { onDelete: "cascade" }), status: onboardingStatus("status").default("not_started").notNull(), startedAt: timestamp("started_at", { withTimezone: true }), completedAt: timestamp("completed_at", { withTimezone: true }), ...timestamps }, (table) => [index("onboarding_org_status_idx").on(table.organizationId, table.status)]);
export const onboardingChecklistItems = pgTable("onboarding_checklist_items", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), onboardingId: uuid("onboarding_id").notNull().references(() => onboarding.id, { onDelete: "cascade" }), title: varchar("title", { length: 160 }).notNull(), status: onboardingItemStatus("status").default("pending").notNull(), completedAt: timestamp("completed_at", { withTimezone: true }), completedByUserId: uuid("completed_by_user_id").references(() => users.id, { onDelete: "set null" }), sortOrder: integer("sort_order").default(0).notNull() }, (table) => [index("onboarding_items_idx").on(table.organizationId, table.onboardingId)]);
