import { boolean, date, index, integer, pgEnum, pgTable, real, text, time, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";

const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
};

export const userStatus = pgEnum("user_status", ["active", "disabled"]);
export const platformRole = pgEnum("platform_role", ["NONE", "PLATFORM_OWNER"]);
export const organizationStatus = pgEnum("organization_status", ["pending", "active", "suspended", "rejected", "archived"]);
export const membershipStatus = pgEnum("membership_status", ["invited", "active", "suspended", "removed"]);
export const invitationStatus = pgEnum("invitation_status", ["pending", "accepted", "expired", "revoked"]);
export const subscriptionStatus = pgEnum("subscription_status", ["pending", "active", "suspended", "cancelled", "expired"]);
export const provisioningStatus = pgEnum("provisioning_status", ["pending", "running", "completed", "failed", "retrying"]);
export const planCode = pgEnum("plan_code", ["FREE", "STARTER", "PROFESSIONAL", "ENTERPRISE"]);
export const masterDataStatus = pgEnum("master_data_status", ["active", "inactive"]);
export const employeeStatus = pgEnum("employee_status", ["invited", "onboarding", "active", "probation", "confirmed", "notice_period", "inactive", "resigned", "terminated", "exited"]);
export const onboardingStatus = pgEnum("onboarding_status", ["not_started", "invited", "in_progress", "completed", "blocked"]);
export const onboardingItemStatus = pgEnum("onboarding_item_status", ["pending", "completed", "blocked"]);
export const documentStatus = pgEnum("document_status", ["pending", "verified", "rejected", "expired"]);
export const attendanceStatus = pgEnum("attendance_status", ["scheduled", "present", "absent", "half_day", "late", "early_departure", "late_and_early", "holiday", "weekend", "leave", "work_from_home", "regularization_pending", "regularized", "missing_punch"]);
export const punchType = pgEnum("punch_type", ["clock_in", "clock_out", "break_start", "break_end"]);
export const regularizationStatus = pgEnum("regularization_status", ["pending", "approved", "rejected", "cancelled"]);
export const leaveApplicationStatus = pgEnum("leave_application_status", ["draft", "pending", "approved", "rejected", "cancelled", "withdrawn"]);
export const leaveTransactionType = pgEnum("leave_transaction_type", ["opening", "accrual", "consumption", "reservation", "reservation_release", "cancellation_reversal", "adjustment", "carry_forward", "expiry"]);
export const workflowStatus = pgEnum("workflow_status", ["pending", "in_progress", "approved", "rejected", "cancelled", "failed"]);
export const workflowStepMode = pgEnum("workflow_step_mode", ["sequential", "parallel"]);
export const workflowActorType = pgEnum("workflow_actor_type", ["reporting_manager", "organization_role", "specific_user", "department_head", "hr_admin"]);
export const approvalTaskStatus = pgEnum("approval_task_status", ["pending", "approved", "rejected", "skipped", "cancelled", "expired"]);
export const approvalAction = pgEnum("approval_action", ["approve", "reject", "cancel", "request_changes"]);
export const expenseClaimStatus = pgEnum("expense_claim_status", ["draft", "submitted", "pending_approval", "approved", "rejected", "cancelled"]);
export const reimbursementStatus = pgEnum("reimbursement_status", ["not_eligible", "pending", "processing", "reimbursed", "failed", "cancelled"]);
export const expenseReceiptStatus = pgEnum("expense_receipt_status", ["pending", "verified", "rejected"]);
export const documentLifecycleStatus = pgEnum("document_lifecycle_status", ["active", "expiring", "expired", "archived"]);
export const notificationCategory = pgEnum("notification_category", ["attendance", "leave", "expense", "documents", "onboarding", "approvals", "system"]);
export const notificationDeliveryStatus = pgEnum("notification_delivery_status", ["pending", "sent", "failed", "skipped"]);
export const notificationChannel = pgEnum("notification_channel", ["in_app", "email"]);

export const users = pgTable("users", {
  id: uuid("id").defaultRandom().primaryKey(), email: varchar("email", { length: 320 }).notNull().unique(), fullName: varchar("full_name", { length: 160 }).notNull(), passwordHash: text("password_hash").notNull(), status: userStatus("status").default("active").notNull(), platformRole: platformRole("platform_role").default("NONE").notNull(), emailVerifiedAt: timestamp("email_verified_at", { withTimezone: true }), ...timestamps,
}, (table) => [index("users_email_idx").on(table.email)]);

export const organizations = pgTable("organizations", {
  id: uuid("id").defaultRandom().primaryKey(), name: varchar("name", { length: 160 }).notNull(), legalName: varchar("legal_name", { length: 240 }).notNull(), slug: varchar("slug", { length: 80 }).notNull().unique(), status: organizationStatus("status").default("pending").notNull(), timezone: varchar("timezone", { length: 80 }).notNull().default("UTC"), currency: varchar("currency", { length: 3 }).notNull().default("INR"), website: varchar("website", { length: 240 }), contactEmail: varchar("contact_email", { length: 320 }), contactPhone: varchar("contact_phone", { length: 40 }), addressLine1: varchar("address_line_1", { length: 240 }), addressLine2: varchar("address_line_2", { length: 240 }), city: varchar("city", { length: 120 }), state: varchar("state", { length: 120 }), country: varchar("country", { length: 120 }), postalCode: varchar("postal_code", { length: 20 }), dateFormat: varchar("date_format", { length: 40 }).default("dd/MM/yyyy").notNull(), fiscalYearStartMonth: integer("fiscal_year_start_month").default(4).notNull(), employeeIdPrefix: varchar("employee_id_prefix", { length: 20 }).default("EMP").notNull(), employeeIdNext: integer("employee_id_next").default(1).notNull(), employeeIdPadding: integer("employee_id_padding").default(4).notNull(), ...timestamps,
}, (table) => [index("organizations_status_idx").on(table.status)]);

export const roles = pgTable("roles", {
  id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").references(() => organizations.id, { onDelete: "cascade" }), name: varchar("name", { length: 80 }).notNull(), key: varchar("key", { length: 80 }).notNull(), description: varchar("description", { length: 240 }), isSystem: boolean("is_system").default(false).notNull(), ...timestamps,
}, (table) => [uniqueIndex("roles_org_key_idx").on(table.organizationId, table.key)]);

export const permissions = pgTable("permissions", { id: uuid("id").defaultRandom().primaryKey(), key: varchar("key", { length: 120 }).notNull().unique(), description: varchar("description", { length: 240 }) });
export const rolePermissions = pgTable("role_permissions", { roleId: uuid("role_id").notNull().references(() => roles.id, { onDelete: "cascade" }), permissionId: uuid("permission_id").notNull().references(() => permissions.id, { onDelete: "cascade" }) }, (table) => [uniqueIndex("role_permissions_pk").on(table.roleId, table.permissionId)]);

export const memberships = pgTable("memberships", {
  id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").notNull().unique().references(() => users.id, { onDelete: "cascade" }), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), roleId: uuid("role_id").notNull().references(() => roles.id), status: membershipStatus("status").default("invited").notNull(), ...timestamps,
}, (table) => [index("memberships_org_idx").on(table.organizationId), index("memberships_user_status_idx").on(table.userId, table.status)]);

export const sessions = pgTable("sessions", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), tokenHash: varchar("token_hash", { length: 64 }).notNull().unique(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).defaultNow().notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (table) => [index("sessions_user_idx").on(table.userId), index("sessions_expiry_idx").on(table.expiresAt)]);
export const emailVerificationTokens = pgTable("email_verification_tokens", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), tokenHash: varchar("token_hash", { length: 64 }).notNull().unique(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), usedAt: timestamp("used_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const passwordResetTokens = pgTable("password_reset_tokens", { id: uuid("id").defaultRandom().primaryKey(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), tokenHash: varchar("token_hash", { length: 64 }).notNull().unique(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), usedAt: timestamp("used_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });

export const plans = pgTable("plans", { id: uuid("id").defaultRandom().primaryKey(), code: planCode("code").notNull().unique(), name: varchar("name", { length: 80 }).notNull(), description: varchar("description", { length: 240 }), maxUsers: integer("max_users"), maxStorageBytes: integer("max_storage_bytes"), billingInterval: varchar("billing_interval", { length: 20 }).notNull().default("monthly"), active: boolean("active").default(true).notNull(), ...timestamps });
export const planFeatures = pgTable("plan_features", { id: uuid("id").defaultRandom().primaryKey(), planId: uuid("plan_id").notNull().references(() => plans.id, { onDelete: "cascade" }), featureKey: varchar("feature_key", { length: 120 }).notNull(), enabled: boolean("enabled").default(true).notNull(), limitValue: integer("limit_value") }, (table) => [uniqueIndex("plan_features_key_idx").on(table.planId, table.featureKey)]);
export const subscriptions = pgTable("subscriptions", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().unique().references(() => organizations.id, { onDelete: "cascade" }), planId: uuid("plan_id").notNull().references(() => plans.id), status: subscriptionStatus("status").default("pending").notNull(), startsAt: timestamp("starts_at", { withTimezone: true }), endsAt: timestamp("ends_at", { withTimezone: true }), ...timestamps });

export const invitations = pgTable("invitations", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), employeeId: uuid("employee_id").references(() => employees.id, { onDelete: "set null" }), invitationType: varchar("invitation_type", { length: 40 }).notNull().default("organization_admin"), invitedEmail: varchar("invited_email", { length: 320 }).notNull(), intendedRole: varchar("intended_role", { length: 80 }).notNull(), tokenHash: varchar("token_hash", { length: 64 }).notNull().unique(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), status: invitationStatus("status").default("pending").notNull(), acceptedAt: timestamp("accepted_at", { withTimezone: true }), ...timestamps }, (table) => [index("invitations_email_idx").on(table.invitedEmail), index("invitations_org_status_idx").on(table.organizationId, table.status), index("invitations_employee_idx").on(table.employeeId)]);
export const provisioningJobs = pgTable("provisioning_jobs", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().unique().references(() => organizations.id, { onDelete: "cascade" }), jobType: varchar("job_type", { length: 80 }).notNull().default("organization.provision"), status: provisioningStatus("status").default("pending").notNull(), currentStep: varchar("current_step", { length: 80 }).notNull().default("created"), attempts: integer("attempts").default(0).notNull(), startedAt: timestamp("started_at", { withTimezone: true }), completedAt: timestamp("completed_at", { withTimezone: true }), failureMessage: varchar("failure_message", { length: 1000 }), ...timestamps }, (table) => [index("provisioning_status_idx").on(table.status)]);
export const auditLogs = pgTable("audit_logs", { id: uuid("id").defaultRandom().primaryKey(), actorUserId: uuid("actor_user_id").references(() => users.id, { onDelete: "set null" }), organizationId: uuid("organization_id").references(() => organizations.id, { onDelete: "set null" }), action: varchar("action", { length: 120 }).notNull(), resource: varchar("resource", { length: 120 }).notNull(), resourceId: uuid("resource_id"), requestId: varchar("request_id", { length: 80 }), metadata: text("metadata"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (table) => [index("audit_org_created_idx").on(table.organizationId, table.createdAt), index("audit_actor_created_idx").on(table.actorUserId, table.createdAt)]);
export const systemConfig = pgTable("system_config", { key: varchar("key", { length: 120 }).primaryKey(), value: varchar("value", { length: 2000 }).notNull(), ...timestamps });

export const departments = pgTable("departments", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), name: varchar("name", { length: 120 }).notNull(), code: varchar("code", { length: 40 }).notNull(), description: varchar("description", { length: 500 }), headEmployeeId: uuid("head_employee_id"), status: masterDataStatus("status").default("active").notNull(), ...timestamps }, (table) => [uniqueIndex("departments_org_code_idx").on(table.organizationId, table.code), index("departments_org_status_idx").on(table.organizationId, table.status)]);
export const designations = pgTable("designations", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), name: varchar("name", { length: 120 }).notNull(), code: varchar("code", { length: 40 }).notNull(), description: varchar("description", { length: 500 }), level: integer("level"), status: masterDataStatus("status").default("active").notNull(), ...timestamps }, (table) => [uniqueIndex("designations_org_code_idx").on(table.organizationId, table.code), index("designations_org_status_idx").on(table.organizationId, table.status)]);
export const locations = pgTable("locations", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), name: varchar("name", { length: 120 }).notNull(), code: varchar("code", { length: 40 }).notNull(), addressLine1: varchar("address_line_1", { length: 240 }), addressLine2: varchar("address_line_2", { length: 240 }), city: varchar("city", { length: 120 }), state: varchar("state", { length: 120 }), country: varchar("country", { length: 120 }), postalCode: varchar("postal_code", { length: 20 }), timezone: varchar("timezone", { length: 80 }).default("UTC").notNull(), status: masterDataStatus("status").default("active").notNull(), ...timestamps }, (table) => [uniqueIndex("locations_org_code_idx").on(table.organizationId, table.code), index("locations_org_status_idx").on(table.organizationId, table.status)]);
export const employmentTypes = pgTable("employment_types", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), name: varchar("name", { length: 80 }).notNull(), code: varchar("code", { length: 40 }).notNull(), status: masterDataStatus("status").default("active").notNull(), ...timestamps }, (table) => [uniqueIndex("employment_types_org_code_idx").on(table.organizationId, table.code)]);
export const shifts = pgTable("shifts", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), name: varchar("name", { length: 100 }).notNull(), code: varchar("code", { length: 40 }).notNull(), startTime: time("start_time").notNull(), endTime: time("end_time").notNull(), breakMinutes: integer("break_minutes").default(0).notNull(), graceMinutes: integer("grace_minutes").default(0).notNull(), overnight: boolean("overnight").default(false).notNull(), status: masterDataStatus("status").default("active").notNull(), ...timestamps }, (table) => [uniqueIndex("shifts_org_code_idx").on(table.organizationId, table.code)]);
export const workingDays = pgTable("working_days", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), dayOfWeek: integer("day_of_week").notNull(), isWorkingDay: boolean("is_working_day").default(true).notNull(), ...timestamps }, (table) => [uniqueIndex("working_days_org_day_idx").on(table.organizationId, table.dayOfWeek)]);
export const holidays = pgTable("holidays", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), name: varchar("name", { length: 160 }).notNull(), holidayDate: date("holiday_date").notNull(), category: varchar("category", { length: 60 }).default("public").notNull(), description: varchar("description", { length: 500 }), status: masterDataStatus("status").default("active").notNull(), ...timestamps }, (table) => [uniqueIndex("holidays_org_date_name_idx").on(table.organizationId, table.holidayDate, table.name), index("holidays_org_date_idx").on(table.organizationId, table.holidayDate)]);
export const teams = pgTable("teams", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), departmentId: uuid("department_id").references(() => departments.id, { onDelete: "set null" }), name: varchar("name", { length: 120 }).notNull(), code: varchar("code", { length: 40 }).notNull(), description: varchar("description", { length: 500 }), teamLeadEmployeeId: uuid("team_lead_employee_id"), status: masterDataStatus("status").default("active").notNull(), ...timestamps }, (table) => [uniqueIndex("teams_org_code_idx").on(table.organizationId, table.code), index("teams_org_department_idx").on(table.organizationId, table.departmentId)]);

export const employees = pgTable("employees", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), userId: uuid("user_id").unique().references(() => users.id, { onDelete: "set null" }), employeeId: varchar("employee_id", { length: 40 }).notNull(), firstName: varchar("first_name", { length: 80 }).notNull(), middleName: varchar("middle_name", { length: 80 }), lastName: varchar("last_name", { length: 80 }).notNull(), displayName: varchar("display_name", { length: 180 }).notNull(), profilePhotoKey: varchar("profile_photo_key", { length: 500 }), dateOfBirth: date("date_of_birth"), gender: varchar("gender", { length: 40 }), maritalStatus: varchar("marital_status", { length: 40 }), nationality: varchar("nationality", { length: 80 }), personalEmail: varchar("personal_email", { length: 320 }), workEmail: varchar("work_email", { length: 320 }), phone: varchar("phone", { length: 40 }), alternatePhone: varchar("alternate_phone", { length: 40 }), addressLine1: varchar("address_line_1", { length: 240 }), addressLine2: varchar("address_line_2", { length: 240 }), city: varchar("city", { length: 120 }), state: varchar("state", { length: 120 }), country: varchar("country", { length: 120 }), postalCode: varchar("postal_code", { length: 20 }), joiningDate: date("joining_date"), employmentTypeId: uuid("employment_type_id").references(() => employmentTypes.id), departmentId: uuid("department_id").references(() => departments.id), designationId: uuid("designation_id").references(() => designations.id), reportingManagerId: uuid("reporting_manager_id"), teamId: uuid("team_id").references(() => teams.id), locationId: uuid("location_id").references(() => locations.id), shiftId: uuid("shift_id").references(() => shifts.id), status: employeeStatus("status").default("invited").notNull(), probationStart: date("probation_start"), probationEnd: date("probation_end"), confirmationDate: date("confirmation_date"), ...timestamps }, (table) => [uniqueIndex("employees_org_employee_id_idx").on(table.organizationId, table.employeeId), index("employees_org_status_idx").on(table.organizationId, table.status), index("employees_org_department_idx").on(table.organizationId, table.departmentId), index("employees_org_designation_idx").on(table.organizationId, table.designationId), index("employees_org_manager_idx").on(table.organizationId, table.reportingManagerId), index("employees_org_team_idx").on(table.organizationId, table.teamId), index("employees_org_location_idx").on(table.organizationId, table.locationId), index("employees_joining_date_idx").on(table.organizationId, table.joiningDate)]);
export const employeeHistory = pgTable("employee_history", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), employeeId: uuid("employee_id").notNull().references(() => employees.id, { onDelete: "cascade" }), eventType: varchar("event_type", { length: 80 }).notNull(), previousValue: text("previous_value"), newValue: text("new_value"), reason: varchar("reason", { length: 500 }), actorUserId: uuid("actor_user_id").references(() => users.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (table) => [index("employee_history_idx").on(table.organizationId, table.employeeId, table.createdAt)]);
export const documentTypes = pgTable("document_types", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), name: varchar("name", { length: 120 }).notNull(), code: varchar("code", { length: 60 }).notNull(), description: varchar("description", { length: 500 }), category: varchar("category", { length: 60 }).default("other").notNull(), active: boolean("active").default(true).notNull(), required: boolean("required").default(false).notNull(), expiryApplicable: boolean("expiry_applicable").default(false).notNull(), verificationRequired: boolean("verification_required").default(true).notNull(), ...timestamps }, (table) => [uniqueIndex("document_types_org_code_idx").on(table.organizationId, table.code)]);
export const employeeDocuments = pgTable("employee_documents", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), employeeId: uuid("employee_id").notNull().references(() => employees.id, { onDelete: "cascade" }), documentTypeId: uuid("document_type_id").references(() => documentTypes.id), documentType: varchar("document_type", { length: 80 }).notNull(), category: varchar("category", { length: 60 }).default("other").notNull(), fileName: varchar("file_name", { length: 240 }).notNull(), storageKey: varchar("storage_key", { length: 500 }).notNull(), mimeType: varchar("mime_type", { length: 120 }), fileSize: integer("file_size"), status: documentStatus("status").default("pending").notNull(), lifecycleStatus: documentLifecycleStatus("lifecycle_status").default("active").notNull(), verificationComment: varchar("verification_comment", { length: 1000 }), version: integer("version").default(1).notNull(), replacedDocumentId: uuid("replaced_document_id"), uploadedByUserId: uuid("uploaded_by_user_id").references(() => users.id, { onDelete: "set null" }), uploadedAt: timestamp("uploaded_at", { withTimezone: true }).defaultNow().notNull(), expiresAt: date("expires_at"), archivedAt: timestamp("archived_at", { withTimezone: true }), ...timestamps }, (table) => [index("employee_documents_idx").on(table.organizationId, table.employeeId), index("employee_documents_type_idx").on(table.organizationId, table.documentTypeId), index("employee_documents_expiry_idx").on(table.organizationId, table.expiresAt)]);
export const documentHistory = pgTable("document_history", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), documentId: uuid("document_id").notNull().references(() => employeeDocuments.id, { onDelete: "cascade" }), actorUserId: uuid("actor_user_id").references(() => users.id, { onDelete: "set null" }), action: varchar("action", { length: 80 }).notNull(), previousStatus: documentStatus("previous_status"), newStatus: documentStatus("new_status"), comment: varchar("comment", { length: 1000 }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (table) => [index("document_history_idx").on(table.organizationId, table.documentId, table.createdAt)]);
export const onboarding = pgTable("onboarding", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), employeeId: uuid("employee_id").notNull().unique().references(() => employees.id, { onDelete: "cascade" }), status: onboardingStatus("status").default("not_started").notNull(), startedAt: timestamp("started_at", { withTimezone: true }), completedAt: timestamp("completed_at", { withTimezone: true }), ...timestamps }, (table) => [index("onboarding_org_status_idx").on(table.organizationId, table.status)]);
export const onboardingChecklistItems = pgTable("onboarding_checklist_items", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), onboardingId: uuid("onboarding_id").notNull().references(() => onboarding.id, { onDelete: "cascade" }), title: varchar("title", { length: 160 }).notNull(), status: onboardingItemStatus("status").default("pending").notNull(), completedAt: timestamp("completed_at", { withTimezone: true }), completedByUserId: uuid("completed_by_user_id").references(() => users.id, { onDelete: "set null" }), sortOrder: integer("sort_order").default(0).notNull() }, (table) => [index("onboarding_items_idx").on(table.organizationId, table.onboardingId)]);

export const attendancePolicies = pgTable("attendance_policies", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), name: varchar("name", { length: 120 }).notNull(), gracePeriodMinutes: integer("grace_period_minutes").default(0).notNull(), lateThresholdMinutes: integer("late_threshold_minutes").default(0).notNull(), earlyDepartureThresholdMinutes: integer("early_departure_threshold_minutes").default(0).notNull(), minimumWorkMinutes: integer("minimum_work_minutes").default(0).notNull(), allowRegularization: boolean("allow_regularization").default(true).notNull(), regularizationApprovalRequired: boolean("regularization_approval_required").default(true).notNull(), active: boolean("active").default(true).notNull(), ...timestamps }, (table) => [uniqueIndex("attendance_policies_org_name_idx").on(table.organizationId, table.name)]);
export const attendanceRecords = pgTable("attendance_records", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), employeeId: uuid("employee_id").notNull().references(() => employees.id, { onDelete: "cascade" }), attendanceDate: date("attendance_date").notNull(), shiftId: uuid("shift_id").references(() => shifts.id), scheduledStart: timestamp("scheduled_start", { withTimezone: true }), scheduledEnd: timestamp("scheduled_end", { withTimezone: true }), actualFirstIn: timestamp("actual_first_in", { withTimezone: true }), actualLastOut: timestamp("actual_last_out", { withTimezone: true }), totalWorkMinutes: integer("total_work_minutes").default(0).notNull(), totalBreakMinutes: integer("total_break_minutes").default(0).notNull(), netWorkMinutes: integer("net_work_minutes").default(0).notNull(), lateMinutes: integer("late_minutes").default(0).notNull(), earlyDepartureMinutes: integer("early_departure_minutes").default(0).notNull(), status: attendanceStatus("status").default("scheduled").notNull(), source: varchar("source", { length: 40 }).default("web").notNull(), notes: varchar("notes", { length: 500 }), ...timestamps }, (table) => [uniqueIndex("attendance_org_employee_date_idx").on(table.organizationId, table.employeeId, table.attendanceDate), index("attendance_org_date_idx").on(table.organizationId, table.attendanceDate), index("attendance_org_status_idx").on(table.organizationId, table.status)]);
export const attendancePunches = pgTable("attendance_punches", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), employeeId: uuid("employee_id").notNull().references(() => employees.id, { onDelete: "cascade" }), attendanceId: uuid("attendance_id").notNull().references(() => attendanceRecords.id, { onDelete: "cascade" }), punchType: punchType("punch_type").notNull(), punchedAt: timestamp("punched_at", { withTimezone: true }).notNull(), source: varchar("source", { length: 40 }).default("web").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (table) => [index("attendance_punches_record_idx").on(table.organizationId, table.attendanceId, table.punchedAt), index("attendance_punches_employee_idx").on(table.organizationId, table.employeeId, table.punchedAt)]);
export const attendanceRegularizationRequests = pgTable("attendance_regularization_requests", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), employeeId: uuid("employee_id").notNull().references(() => employees.id, { onDelete: "cascade" }), attendanceId: uuid("attendance_id").notNull().references(() => attendanceRecords.id, { onDelete: "cascade" }), requestedIn: timestamp("requested_in", { withTimezone: true }), requestedOut: timestamp("requested_out", { withTimezone: true }), reason: varchar("reason", { length: 1000 }).notNull(), status: regularizationStatus("status").default("pending").notNull(), workflowInstanceId: uuid("workflow_instance_id").references(() => workflowInstances.id), submittedAt: timestamp("submitted_at", { withTimezone: true }).defaultNow().notNull(), resolvedAt: timestamp("resolved_at", { withTimezone: true }), resolvedByUserId: uuid("resolved_by_user_id").references(() => users.id, { onDelete: "set null" }), ...timestamps }, (table) => [uniqueIndex("regularization_active_idx").on(table.organizationId, table.attendanceId, table.status), index("regularization_org_status_idx").on(table.organizationId, table.status)]);

export const leaveTypes = pgTable("leave_types", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), name: varchar("name", { length: 120 }).notNull(), code: varchar("code", { length: 40 }).notNull(), description: varchar("description", { length: 500 }), paid: boolean("paid").default(true).notNull(), color: varchar("color", { length: 20 }), minimumDays: integer("minimum_days").default(1).notNull(), maximumDays: integer("maximum_days"), halfDayAllowed: boolean("half_day_allowed").default(true).notNull(), cancellationAllowed: boolean("cancellation_allowed").default(true).notNull(), noticePeriodDays: integer("notice_period_days").default(0).notNull(), active: boolean("active").default(true).notNull(), ...timestamps }, (table) => [uniqueIndex("leave_types_org_code_idx").on(table.organizationId, table.code)]);
export const leavePolicies = pgTable("leave_policies", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), leaveTypeId: uuid("leave_type_id").notNull().references(() => leaveTypes.id, { onDelete: "cascade" }), annualEntitlement: integer("annual_entitlement").default(0).notNull(), accrualEnabled: boolean("accrual_enabled").default(false).notNull(), carryForwardEnabled: boolean("carry_forward_enabled").default(false).notNull(), maximumCarryForward: integer("maximum_carry_forward"), probationEligible: boolean("probation_eligible").default(false).notNull(), negativeBalanceAllowed: boolean("negative_balance_allowed").default(false).notNull(), approvalRequired: boolean("approval_required").default(true).notNull(), ...timestamps }, (table) => [uniqueIndex("leave_policies_org_type_idx").on(table.organizationId, table.leaveTypeId)]);
export const leaveBalances = pgTable("leave_balances", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), employeeId: uuid("employee_id").notNull().references(() => employees.id, { onDelete: "cascade" }), leaveTypeId: uuid("leave_type_id").notNull().references(() => leaveTypes.id, { onDelete: "cascade" }), leaveYear: integer("leave_year").notNull(), openingBalance: real("opening_balance").default(0).notNull(), accrued: real("accrued").default(0).notNull(), consumed: real("consumed").default(0).notNull(), pending: real("pending").default(0).notNull(), adjusted: real("adjusted").default(0).notNull(), ...timestamps }, (table) => [uniqueIndex("leave_balances_employee_type_year_idx").on(table.organizationId, table.employeeId, table.leaveTypeId, table.leaveYear)]);
export const leaveTransactions = pgTable("leave_transactions", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), employeeId: uuid("employee_id").notNull().references(() => employees.id, { onDelete: "cascade" }), leaveTypeId: uuid("leave_type_id").notNull().references(() => leaveTypes.id, { onDelete: "cascade" }), leaveBalanceId: uuid("leave_balance_id").notNull().references(() => leaveBalances.id, { onDelete: "cascade" }), transactionType: leaveTransactionType("transaction_type").notNull(), amount: real("amount").notNull(), referenceId: uuid("reference_id"), reason: varchar("reason", { length: 500 }), actorUserId: uuid("actor_user_id").references(() => users.id, { onDelete: "set null" }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (table) => [index("leave_transactions_balance_idx").on(table.organizationId, table.leaveBalanceId, table.createdAt)]);
export const leaveApplications = pgTable("leave_applications", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), employeeId: uuid("employee_id").notNull().references(() => employees.id, { onDelete: "cascade" }), leaveTypeId: uuid("leave_type_id").notNull().references(() => leaveTypes.id), workflowInstanceId: uuid("workflow_instance_id").references(() => workflowInstances.id), startDate: date("start_date").notNull(), endDate: date("end_date").notNull(), requestedDays: real("requested_days").notNull(), halfDay: boolean("half_day").default(false).notNull(), reason: varchar("reason", { length: 1000 }).notNull(), status: leaveApplicationStatus("status").default("pending").notNull(), submittedAt: timestamp("submitted_at", { withTimezone: true }).defaultNow().notNull(), approvedAt: timestamp("approved_at", { withTimezone: true }), rejectedAt: timestamp("rejected_at", { withTimezone: true }), cancelledAt: timestamp("cancelled_at", { withTimezone: true }), ...timestamps }, (table) => [index("leave_apps_org_employee_idx").on(table.organizationId, table.employeeId, table.startDate), index("leave_apps_org_status_idx").on(table.organizationId, table.status)]);

export const workflowDefinitions = pgTable("workflow_definitions", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), name: varchar("name", { length: 160 }).notNull(), code: varchar("code", { length: 80 }).notNull(), workflowType: varchar("workflow_type", { length: 80 }).notNull(), description: varchar("description", { length: 500 }), active: boolean("active").default(false).notNull(), createdByUserId: uuid("created_by_user_id").references(() => users.id, { onDelete: "set null" }), ...timestamps }, (table) => [uniqueIndex("workflow_defs_org_code_idx").on(table.organizationId, table.code)]);
export const workflowVersions = pgTable("workflow_versions", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), definitionId: uuid("definition_id").notNull().references(() => workflowDefinitions.id, { onDelete: "cascade" }), version: integer("version").notNull(), active: boolean("active").default(false).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (table) => [uniqueIndex("workflow_versions_definition_version_idx").on(table.definitionId, table.version)]);
export const workflowSteps = pgTable("workflow_steps", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), versionId: uuid("version_id").notNull().references(() => workflowVersions.id, { onDelete: "cascade" }), stepOrder: integer("step_order").notNull(), name: varchar("name", { length: 120 }).notNull(), actorType: workflowActorType("actor_type").notNull(), actorRoleKey: varchar("actor_role_key", { length: 80 }), actorUserId: uuid("actor_user_id").references(() => users.id, { onDelete: "set null" }), mode: workflowStepMode("mode").default("sequential").notNull() }, (table) => [uniqueIndex("workflow_steps_version_order_idx").on(table.versionId, table.stepOrder)]);
export const workflowInstances = pgTable("workflow_instances", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), workflowVersionId: uuid("workflow_version_id").notNull().references(() => workflowVersions.id), entityType: varchar("entity_type", { length: 80 }).notNull(), entityId: uuid("entity_id").notNull(), subjectEmployeeId: uuid("subject_employee_id").notNull().references(() => employees.id), status: workflowStatus("status").default("pending").notNull(), currentStepOrder: integer("current_step_order").default(1).notNull(), submittedByUserId: uuid("submitted_by_user_id").references(() => users.id, { onDelete: "set null" }), ...timestamps }, (table) => [index("workflow_instances_entity_idx").on(table.organizationId, table.entityType, table.entityId), index("workflow_instances_status_idx").on(table.organizationId, table.status)]);
export const approvalTasks = pgTable("approval_tasks", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), workflowInstanceId: uuid("workflow_instance_id").notNull().references(() => workflowInstances.id, { onDelete: "cascade" }), workflowStepId: uuid("workflow_step_id").notNull().references(() => workflowSteps.id), approverUserId: uuid("approver_user_id").notNull().references(() => users.id), approverEmployeeId: uuid("approver_employee_id").references(() => employees.id), status: approvalTaskStatus("status").default("pending").notNull(), assignedAt: timestamp("assigned_at", { withTimezone: true }).defaultNow().notNull(), actedAt: timestamp("acted_at", { withTimezone: true }), comments: varchar("comments", { length: 1000 }), dueAt: timestamp("due_at", { withTimezone: true }) }, (table) => [index("approval_tasks_user_status_idx").on(table.organizationId, table.approverUserId, table.status), index("approval_tasks_instance_idx").on(table.organizationId, table.workflowInstanceId)]);
export const approvalHistory = pgTable("approval_history", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), workflowInstanceId: uuid("workflow_instance_id").notNull().references(() => workflowInstances.id, { onDelete: "cascade" }), workflowStepId: uuid("workflow_step_id").references(() => workflowSteps.id), taskId: uuid("task_id").references(() => approvalTasks.id), actorUserId: uuid("actor_user_id").notNull().references(() => users.id), action: approvalAction("action").notNull(), comment: varchar("comment", { length: 1000 }), previousStatus: workflowStatus("previous_status").notNull(), newStatus: workflowStatus("new_status").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (table) => [index("approval_history_instance_idx").on(table.organizationId, table.workflowInstanceId, table.createdAt)]);

export const expenseNumberCounters = pgTable("expense_number_counters", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), claimYear: integer("claim_year").notNull(), nextNumber: integer("next_number").default(0).notNull(), ...timestamps }, (table) => [uniqueIndex("expense_counter_org_year_idx").on(table.organizationId, table.claimYear)]);
export const expenseCategories = pgTable("expense_categories", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), name: varchar("name", { length: 120 }).notNull(), code: varchar("code", { length: 60 }).notNull(), description: varchar("description", { length: 500 }), status: masterDataStatus("status").default("active").notNull(), ...timestamps }, (table) => [uniqueIndex("expense_categories_org_code_idx").on(table.organizationId, table.code)]);
export const expensePolicies = pgTable("expense_policies", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), categoryId: uuid("category_id").references(() => expenseCategories.id, { onDelete: "cascade" }), maximumAmount: real("maximum_amount"), dailyLimit: real("daily_limit"), monthlyLimit: real("monthly_limit"), receiptRequired: boolean("receipt_required").default(false).notNull(), approvalRequired: boolean("approval_required").default(true).notNull(), submissionDeadlineDays: integer("submission_deadline_days"), currency: varchar("currency", { length: 3 }).default("INR").notNull(), eligibleEmployeeTypes: text("eligible_employee_types"), departmentId: uuid("department_id").references(() => departments.id, { onDelete: "set null" }), locationId: uuid("location_id").references(() => locations.id, { onDelete: "set null" }), active: boolean("active").default(true).notNull(), ...timestamps }, (table) => [index("expense_policies_org_category_idx").on(table.organizationId, table.categoryId)]);
export const expenseClaims = pgTable("expense_claims", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), employeeId: uuid("employee_id").notNull().references(() => employees.id, { onDelete: "cascade" }), claimNumber: varchar("claim_number", { length: 40 }).notNull(), title: varchar("title", { length: 180 }).notNull(), description: varchar("description", { length: 1000 }), totalAmount: real("total_amount").default(0).notNull(), currency: varchar("currency", { length: 3 }).notNull(), expenseDate: date("expense_date").notNull(), status: expenseClaimStatus("status").default("draft").notNull(), reimbursementStatus: reimbursementStatus("reimbursement_status").default("pending").notNull(), workflowInstanceId: uuid("workflow_instance_id").references(() => workflowInstances.id), submittedAt: timestamp("submitted_at", { withTimezone: true }), approvedAt: timestamp("approved_at", { withTimezone: true }), rejectedAt: timestamp("rejected_at", { withTimezone: true }), cancelledAt: timestamp("cancelled_at", { withTimezone: true }), ...timestamps }, (table) => [uniqueIndex("expense_claims_org_number_idx").on(table.organizationId, table.claimNumber), index("expense_claims_org_employee_idx").on(table.organizationId, table.employeeId, table.expenseDate), index("expense_claims_org_status_idx").on(table.organizationId, table.status), index("expense_claims_org_reimbursement_idx").on(table.organizationId, table.reimbursementStatus)]);
export const expenseItems = pgTable("expense_items", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), claimId: uuid("claim_id").notNull().references(() => expenseClaims.id, { onDelete: "cascade" }), categoryId: uuid("category_id").notNull().references(() => expenseCategories.id), expenseDate: date("expense_date").notNull(), description: varchar("description", { length: 500 }).notNull(), amount: real("amount").notNull(), currency: varchar("currency", { length: 3 }).notNull(), merchant: varchar("merchant", { length: 180 }), notes: varchar("notes", { length: 500 }), ...timestamps }, (table) => [index("expense_items_claim_idx").on(table.organizationId, table.claimId), index("expense_items_category_idx").on(table.organizationId, table.categoryId)]);
export const expenseReceipts = pgTable("expense_receipts", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), itemId: uuid("item_id").notNull().references(() => expenseItems.id, { onDelete: "cascade" }), fileName: varchar("file_name", { length: 240 }).notNull(), storageKey: varchar("storage_key", { length: 500 }).notNull(), mimeType: varchar("mime_type", { length: 120 }), fileSize: integer("file_size"), uploadedByUserId: uuid("uploaded_by_user_id").references(() => users.id, { onDelete: "set null" }), verificationStatus: expenseReceiptStatus("verification_status").default("pending").notNull(), uploadedAt: timestamp("uploaded_at", { withTimezone: true }).defaultNow().notNull(), ...timestamps }, (table) => [index("expense_receipts_item_idx").on(table.organizationId, table.itemId)]);
export const expenseHistory = pgTable("expense_history", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), claimId: uuid("claim_id").notNull().references(() => expenseClaims.id, { onDelete: "cascade" }), actorUserId: uuid("actor_user_id").references(() => users.id, { onDelete: "set null" }), action: varchar("action", { length: 80 }).notNull(), previousStatus: expenseClaimStatus("previous_status"), newStatus: expenseClaimStatus("new_status"), previousReimbursementStatus: reimbursementStatus("previous_reimbursement_status"), newReimbursementStatus: reimbursementStatus("new_reimbursement_status"), comment: varchar("comment", { length: 1000 }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (table) => [index("expense_history_claim_idx").on(table.organizationId, table.claimId, table.createdAt)]);

export const notifications = pgTable("notifications", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), recipientUserId: uuid("recipient_user_id").notNull().references(() => users.id, { onDelete: "cascade" }), recipientEmployeeId: uuid("recipient_employee_id").references(() => employees.id, { onDelete: "set null" }), category: notificationCategory("category").notNull(), type: varchar("type", { length: 100 }).notNull(), title: varchar("title", { length: 180 }).notNull(), message: varchar("message", { length: 1000 }).notNull(), entityType: varchar("entity_type", { length: 80 }), entityId: uuid("entity_id"), actionUrl: varchar("action_url", { length: 240 }), idempotencyKey: varchar("idempotency_key", { length: 180 }).notNull(), readAt: timestamp("read_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (table) => [uniqueIndex("notifications_org_idempotency_idx").on(table.organizationId, table.idempotencyKey), index("notifications_recipient_idx").on(table.organizationId, table.recipientUserId, table.createdAt), index("notifications_unread_idx").on(table.organizationId, table.recipientUserId, table.readAt)]);
export const notificationPreferences = pgTable("notification_preferences", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), category: notificationCategory("category").notNull(), inAppEnabled: boolean("in_app_enabled").default(true).notNull(), emailEnabled: boolean("email_enabled").default(true).notNull(), ...timestamps }, (table) => [uniqueIndex("notification_prefs_user_category_idx").on(table.organizationId, table.userId, table.category)]);
export const notificationDeliveries = pgTable("notification_deliveries", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), notificationId: uuid("notification_id").notNull().references(() => notifications.id, { onDelete: "cascade" }), channel: notificationChannel("channel").notNull(), status: notificationDeliveryStatus("status").default("pending").notNull(), attemptCount: integer("attempt_count").default(0).notNull(), attemptedAt: timestamp("attempted_at", { withTimezone: true }), sentAt: timestamp("sent_at", { withTimezone: true }), failedAt: timestamp("failed_at", { withTimezone: true }), nextRetryAt: timestamp("next_retry_at", { withTimezone: true }), errorCategory: varchar("error_category", { length: 120 }), ...timestamps }, (table) => [uniqueIndex("notification_delivery_channel_idx").on(table.notificationId, table.channel), index("notification_delivery_retry_idx").on(table.organizationId, table.status, table.nextRetryAt)]);
export const notificationTemplates = pgTable("notification_templates", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), type: varchar("type", { length: 100 }).notNull(), subject: varchar("subject", { length: 180 }).notNull(), bodyTemplate: text("body_template").notNull(), active: boolean("active").default(true).notNull(), ...timestamps }, (table) => [uniqueIndex("notification_templates_org_type_idx").on(table.organizationId, table.type)]);
export const notificationOutbox = pgTable("notification_outbox", { id: uuid("id").defaultRandom().primaryKey(), organizationId: uuid("organization_id").notNull().references(() => organizations.id, { onDelete: "cascade" }), eventType: varchar("event_type", { length: 120 }).notNull(), idempotencyKey: varchar("idempotency_key", { length: 180 }).notNull(), payload: text("payload").notNull(), status: notificationDeliveryStatus("status").default("pending").notNull(), attemptCount: integer("attempt_count").default(0).notNull(), nextRetryAt: timestamp("next_retry_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (table) => [uniqueIndex("notification_outbox_idempotency_idx").on(table.organizationId, table.idempotencyKey), index("notification_outbox_status_idx").on(table.organizationId, table.status, table.nextRetryAt)]);
