import { notFound, redirect } from "next/navigation";
import { eq } from "drizzle-orm";
import { db } from "@/db/client";
import { organizations, provisioningJobs, subscriptions } from "@/db/schema";
import { getSessionUser } from "@/modules/identity/auth";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { OrganizationStatusActions } from "@/components/platform/organization-status-actions";
export default async function OrganizationDetailsPage({ params }: { params: Promise<{ organizationId: string }> }) { const user = await getSessionUser(); if (!user) redirect("/login"); if (user.platformRole !== "PLATFORM_OWNER") redirect("/app"); const { organizationId } = await params; const organization = await db.query.organizations.findFirst({ where: eq(organizations.id, organizationId) }); if (!organization) notFound(); const job = await db.query.provisioningJobs.findFirst({ where: eq(provisioningJobs.organizationId, organizationId) }); const subscription = await db.query.subscriptions.findFirst({ where: eq(subscriptions.organizationId, organizationId) }); return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><Badge>{organization.status}</Badge><h1 className="mt-3 text-3xl font-bold">{organization.name}</h1><p className="mt-2 text-sm text-muted">{organization.legalName} · {organization.slug}</p></div><OrganizationStatusActions organizationId={organization.id} status={organization.status} /></div><div className="grid gap-5 md:grid-cols-2"><Card><CardHeader><CardTitle>Provisioning</CardTitle></CardHeader><CardContent><p className="text-sm text-muted">Status</p><p className="mt-2 font-semibold">{job?.status ?? "Not created"}</p><p className="mt-1 text-sm text-muted">Current step: {job?.currentStep ?? "—"}</p></CardContent></Card><Card><CardHeader><CardTitle>Subscription</CardTitle></CardHeader><CardContent><p className="text-sm text-muted">Foundation entitlement</p><p className="mt-2 font-semibold">{subscription?.status ?? "Not provisioned"}</p><p className="mt-1 text-sm text-muted">Plan assignment is initialized during provisioning.</p></CardContent></Card></div></div>; }
