import { and, desc, eq, isNull } from "drizzle-orm";
import { db } from "@/db/client";
import { employees, notificationDeliveries, notificationPreferences, notifications, notificationOutbox } from "@/db/schema";
import { recordAudit } from "@/lib/audit";
import { AppError } from "@/lib/errors";

export type NotificationInput = { organizationId: string; recipientUserId: string; category: "attendance" | "leave" | "expense" | "documents" | "onboarding" | "approvals" | "system"; type: string; title: string; message: string; entityType?: string; entityId?: string; actionUrl?: string; idempotencyKey: string };

export async function createNotification(input: NotificationInput) { const [preference] = await db.select().from(notificationPreferences).where(and(eq(notificationPreferences.organizationId, input.organizationId), eq(notificationPreferences.userId, input.recipientUserId), eq(notificationPreferences.category, input.category))); if (preference && !preference.inAppEnabled && !preference.emailEnabled) return { skipped: true }; const [recipient] = await db.select({ id: employees.id }).from(employees).where(and(eq(employees.organizationId, input.organizationId), eq(employees.userId, input.recipientUserId))); await db.insert(notificationOutbox).values({ organizationId: input.organizationId, eventType: input.type, idempotencyKey: `${input.idempotencyKey}:event`, payload: JSON.stringify(input) }).onConflictDoNothing({ target: [notificationOutbox.organizationId, notificationOutbox.idempotencyKey] }); const [notification] = await db.insert(notifications).values({ ...input, recipientEmployeeId: recipient?.id }).onConflictDoNothing({ target: [notifications.organizationId, notifications.idempotencyKey] }).returning(); if (!notification) return { duplicate: true }; await db.insert(notificationDeliveries).values({ organizationId: input.organizationId, notificationId: notification.id, channel: "in_app", status: preference?.inAppEnabled === false ? "skipped" : "sent", sentAt: preference?.inAppEnabled === false ? undefined : new Date() }); await db.insert(notificationDeliveries).values({ organizationId: input.organizationId, notificationId: notification.id, channel: "email", status: preference?.emailEnabled === false ? "skipped" : "pending" }); await recordAudit({ organizationId: input.organizationId, action: "notification_created", resource: "notification", resourceId: notification.id, metadata: { type: input.type, recipientUserId: input.recipientUserId } }); return notification; }
export async function notifyUsers(input: Omit<NotificationInput, "recipientUserId" | "idempotencyKey"> & { recipientUserIds: string[]; idempotencyKey: string }) { return Promise.all(input.recipientUserIds.map((recipientUserId) => createNotification({ ...input, recipientUserId, idempotencyKey: `${input.idempotencyKey}:${recipientUserId}` }))); }
export async function listNotifications(input: { organizationId: string; userId: string; unreadOnly?: boolean; limit?: number }) { return db.select().from(notifications).where(and(eq(notifications.organizationId, input.organizationId), eq(notifications.recipientUserId, input.userId), input.unreadOnly ? isNull(notifications.readAt) : undefined)).orderBy(desc(notifications.createdAt)).limit(Math.min(input.limit ?? 50, 100)); }
export async function unreadNotificationCount(organizationId: string, userId: string) { const rows = await db.select({ id: notifications.id }).from(notifications).where(and(eq(notifications.organizationId, organizationId), eq(notifications.recipientUserId, userId), isNull(notifications.readAt))); return rows.length; }
export async function markNotificationRead(organizationId: string, userId: string, notificationId: string) { const [notification] = await db.update(notifications).set({ readAt: new Date() }).where(and(eq(notifications.id, notificationId), eq(notifications.organizationId, organizationId), eq(notifications.recipientUserId, userId))).returning(); if (!notification) throw new AppError("NOT_FOUND", "Notification was not found.", 404); return notification; }
export async function markAllNotificationsRead(organizationId: string, userId: string) { await db.update(notifications).set({ readAt: new Date() }).where(and(eq(notifications.organizationId, organizationId), eq(notifications.recipientUserId, userId), isNull(notifications.readAt))); return { updated: true }; }
export async function updateNotificationPreference(input: { organizationId: string; userId: string; category: "attendance" | "leave" | "expense" | "documents" | "onboarding" | "approvals" | "system"; inAppEnabled?: boolean; emailEnabled?: boolean }) { const [preference] = await db.insert(notificationPreferences).values({ organizationId: input.organizationId, userId: input.userId, category: input.category, inAppEnabled: input.inAppEnabled ?? true, emailEnabled: input.emailEnabled ?? true }).onConflictDoUpdate({ target: [notificationPreferences.organizationId, notificationPreferences.userId, notificationPreferences.category], set: { inAppEnabled: input.inAppEnabled ?? true, emailEnabled: input.emailEnabled ?? true, updatedAt: new Date() } }).returning(); return preference; }
export async function listNotificationPreferences(organizationId: string, userId: string) { return db.select().from(notificationPreferences).where(and(eq(notificationPreferences.organizationId, organizationId), eq(notificationPreferences.userId, userId))); }
