"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
type Period = { id: string; month: number; year: number; status: string };
type Run = { id: string; runNumber: string; status: string; employeeCount: number; grossTotal: number; netTotal: number };
export function PayrollDashboard() {
  const [periods, setPeriods] = useState<Period[]>([]); const [runs, setRuns] = useState<Run[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function load() { const [periodResponse, runResponse] = await Promise.all([fetch("/api/app/payroll/periods"), fetch("/api/app/payroll/runs")]); const periodJson = await periodResponse.json(); const runJson = await runResponse.json(); setPeriods(periodJson.periods ?? []); setRuns(runJson.runs ?? []); }
  useEffect(() => { void load(); }, []);
  async function createPeriod() { setBusy(true); setMessage(""); const now = new Date(); const response = await fetch("/api/app/payroll/periods", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ month: now.getMonth() + 1, year: now.getFullYear() }) }); setMessage(response.ok ? "Payroll period created." : "Could not create the payroll period."); await load(); setBusy(false); }
  async function calculate(periodId: string) { setBusy(true); setMessage(""); const response = await fetch("/api/app/payroll/runs", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ periodId }) }); setMessage(response.ok ? "Payroll run submitted for approval." : "Payroll calculation could not be started."); await load(); setBusy(false); }
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-muted">India payroll</p><h2 className="mt-2 text-2xl font-bold">Payroll control room</h2><p className="mt-1 text-sm text-muted">Create a period, calculate from attendance and approved leave, then route the immutable result for approval.</p></div><Button onClick={createPeriod} disabled={busy}>Create current period</Button></div>{message && <p role="status" className="rounded-lg bg-surface p-3 text-sm">{message}</p>}<Card><CardHeader><CardTitle>Open periods</CardTitle></CardHeader><CardContent className="space-y-3">{periods.length === 0 ? <p className="text-sm text-muted">No payroll periods yet.</p> : periods.map((period) => <div key={period.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-4"><div><p className="font-semibold">{String(period.month).padStart(2, "0")}/{period.year}</p><p className="text-xs text-muted">Status: {period.status}</p></div><Button variant="secondary" onClick={() => calculate(period.id)} disabled={busy || period.status === "finalized"}>Calculate run</Button></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Recent runs</CardTitle></CardHeader><CardContent className="space-y-3">{runs.length === 0 ? <p className="text-sm text-muted">No runs yet.</p> : runs.map((run) => <div key={run.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-4"><div><p className="font-semibold">{run.runNumber}</p><p className="text-xs text-muted">{run.employeeCount} employees · Gross ₹{Number(run.grossTotal).toLocaleString("en-IN")} · Net ₹{Number(run.netTotal).toLocaleString("en-IN")}</p></div><span className="rounded-full bg-surface px-3 py-1 text-xs font-semibold">{run.status}</span></div>)}</CardContent></Card></div>;
}
