import { z } from "zod";

export const confidenceSourceSchema = z.enum(["deterministic", "parser", "ai", "inferred"]);
export const normalizedResumeSchema = z.object({ personal: z.object({ name: z.string().optional(), email: z.string().email().optional(), phone: z.string().optional(), location: z.string().optional() }), summary: z.string().optional(), experience: z.array(z.object({ company: z.string(), designation: z.string(), startDate: z.string().optional(), endDate: z.string().optional(), current: z.boolean().default(false), description: z.string().optional(), skillsUsed: z.array(z.string()).default([]) })).default([]), education: z.array(z.object({ institution: z.string(), degree: z.string().optional(), specialization: z.string().optional(), startYear: z.number().optional(), endYear: z.number().optional(), grade: z.string().optional() })).default([]), skills: z.array(z.object({ name: z.string(), normalizedName: z.string(), category: z.string().optional(), yearsExperience: z.number().optional(), proficiency: z.string().optional(), evidence: z.string().optional(), confidence: z.number().min(0).max(1), confidenceSource: confidenceSourceSchema })).default([]), certifications: z.array(z.object({ name: z.string(), issuer: z.string().optional(), evidence: z.string().optional(), confidence: z.number().min(0).max(1) })).default([]), projects: z.array(z.object({ name: z.string(), description: z.string().optional(), technologies: z.array(z.string()).default([]), evidence: z.string().optional(), confidence: z.number().min(0).max(1) })).default([]), languages: z.array(z.object({ language: z.string(), proficiency: z.string().optional(), evidence: z.string().optional(), confidence: z.number().min(0).max(1) })).default([]), links: z.array(z.object({ kind: z.string(), url: z.string().url(), confidence: z.number().min(0).max(1) })).default([]), metadata: z.object({ extractionMethod: z.string(), parserVersion: z.string(), warnings: z.array(z.string()).default([]) }) });
export type NormalizedResume = z.infer<typeof normalizedResumeSchema>;
export type ExtractedText = { text: string; pageCount?: number; extractorVersion: string; warnings: string[] };
export type ResumeParserProvider = { name: string; version: string; parse(input: { text: ExtractedText }): Promise<NormalizedResume> };
export type ResumeTextExtractor = { name: string; version: string; extract(input: { bytes: Uint8Array; mimeType: string; fileName: string }): Promise<ExtractedText> };
export type SkillExtractionProvider = { name: string; version: string; extract(input: { resume: NormalizedResume }): Promise<NormalizedResume["skills"]> };
export type ExperienceAnalysisProvider = { name: string; version: string; analyze(input: { experiences: NormalizedResume["experience"] }): Promise<{ totalYears: number; gaps: Array<{ startDate: string; endDate: string; durationYears: number }> }> };
export type ResumeIntelligenceProvider = { parser: ResumeParserProvider; skills: SkillExtractionProvider; experience: ExperienceAnalysisProvider };
