import { createHash } from "node:crypto";
import { z } from "zod";
import { normalizedResumeSchema, type ExtractedText, type NormalizedResume } from "./contracts";

export const PROCESSING_VERSION = "v1";
export const EXTRACTION_SCHEMA_VERSION = "v1";
const aliases: Record<string, { canonicalName: string; category: string }> = { reactjs: { canonicalName: "React", category: "Frontend" }, "react.js": { canonicalName: "React", category: "Frontend" }, "react js": { canonicalName: "React", category: "Frontend" }, nodejs: { canonicalName: "Node.js", category: "Backend" }, "node js": { canonicalName: "Node.js", category: "Backend" }, postgres: { canonicalName: "PostgreSQL", category: "Database" }, "postgre sql": { canonicalName: "PostgreSQL", category: "Database" }, javascript: { canonicalName: "JavaScript", category: "Frontend" }, typescript: { canonicalName: "TypeScript", category: "Frontend" } };
export function normalizeSkillName(value: string) { const trimmed = value.trim(); const alias = aliases[trimmed.toLowerCase()]; return alias?.canonicalName ?? trimmed; }
export function skillCategory(value: string) { return aliases[value.trim().toLowerCase()]?.category; }
export function resumeHash(bytes: Uint8Array) { return createHash("sha256").update(bytes).digest("hex"); }
export function sanitizeFileName(value: string) { return (value.trim().replace(/[^a-zA-Z0-9._-]/g, "_").replace(/^\.+_?/, "_").slice(0, 180) || "resume"); }
export function validateResumeFile(file: { fileName: string; mimeType: string; size: number }, maxSize = 10 * 1024 * 1024) { const allowed = new Map([["application/pdf", ".pdf"], ["application/msword", ".doc"], ["application/vnd.openxmlformats-officedocument.wordprocessingml.document", ".docx"]]); const extension = file.fileName.toLowerCase().slice(file.fileName.lastIndexOf(".")); if (!allowed.has(file.mimeType) || allowed.get(file.mimeType) !== extension) throw new Error("Only matching PDF, DOC, or DOCX resume files are supported."); if (file.size <= 0 || file.size > maxSize) throw new Error("Resume file size is outside the configured limit."); }
export function parseDeterministicResume(text: ExtractedText): NormalizedResume { const email = text.text.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)?.[0]; const phone = text.text.match(/(?:\+?\d[\d\s().-]{7,}\d)/)?.[0]?.trim(); const links = [...text.text.matchAll(/https?:\/\/[^\s)]+/gi)].map((match) => match[0].replace(/[.,]+$/, "")).filter((url) => { try { new URL(url); return true; } catch { return false; } }).map((url) => ({ kind: url.includes("linkedin") ? "linkedin" : url.includes("github") ? "github" : "website", url, confidence: 0.98 })); const textLower = text.text.toLowerCase(); const skills = Object.entries(aliases).filter(([alias]) => textLower.includes(alias)).map(([alias, item]) => ({ name: alias, normalizedName: item.canonicalName, category: item.category, evidence: alias, confidence: 0.9, confidenceSource: "deterministic" as const })); return normalizedResumeSchema.parse({ personal: { email, phone }, experience: [], education: [], skills: [...new Map(skills.map((skill) => [skill.normalizedName, skill])).values()], certifications: [], projects: [], languages: [], links, metadata: { extractionMethod: "deterministic", parserVersion: PROCESSING_VERSION, warnings: text.warnings } }); }
export const extractionFieldSchema = z.object({ fieldPath: z.string().min(1), value: z.string().min(1), confidence: z.number().min(0).max(1).optional(), confidenceSource: z.string(), evidence: z.string().optional() });
