import { and, desc, eq, inArray } from "drizzle-orm";
import { db } from "@/db/client";
import { atsCandidateActivities, atsCandidateDocuments, atsCandidateFieldProvenance, atsCandidateLinks, atsCandidateSkills, atsCandidates, atsResumeExtractionFields, atsResumeExtractions, atsResumeProcessingAttempts, atsResumeProcessingConfigs, atsResumeProcessingJobs } from "@/db/schema";
import { recordAudit } from "@/lib/audit";
import { AppError } from "@/lib/errors";
import { getStorageProvider } from "@/lib/storage";
import { authorize } from "@/modules/tenancy/authorization";
import { parseDeterministicResume, PROCESSING_VERSION, resumeHash, sanitizeFileName, validateResumeFile } from "./normalizer";
import type { ExtractedText } from "./contracts";

const MAX_ATTEMPTS = 3;
let textExtractor: ((input: { bytes: Uint8Array; mimeType: string; fileName: string }) => Promise<ExtractedText>) | undefined;
export function configureResumeTextExtractor(extractor: typeof textExtractor) { textExtractor = extractor; }
async function defaultTextExtractor(input: { bytes: Uint8Array; mimeType: string; fileName: string }): Promise<ExtractedText> { const text = new TextDecoder().decode(input.bytes).replace(/\0/g, ""); const printable = text.replace(/[\x09\x0a\x0d\x20-\x7e]/g, ""); if (printable.length > text.length * 0.25 || text.trim().length < 20) throw new Error("No safe local text extractor is configured for this binary resume format."); return { text, extractorVersion: "deterministic-text-v1", warnings: ["Binary PDF/DOC/DOCX extraction requires a configured provider; this result used a text-compatible payload."] }; }
function errorMessage(error: unknown) { return error instanceof Error ? error.message.slice(0, 900) : "Resume processing failed."; }
async function writeAttempt(input: { organizationId: string; jobId: string; stage: string; status: string; startedAt: Date; errorMessage?: string; metadata?: Record<string, unknown> }) { const completedAt = new Date(); await db.insert(atsResumeProcessingAttempts).values({ organizationId: input.organizationId, jobId: input.jobId, stage: input.stage, status: input.status, provider: "deterministic", providerVersion: PROCESSING_VERSION, startedAt: input.startedAt, completedAt, durationMs: completedAt.getTime() - input.startedAt.getTime(), errorMessage: input.errorMessage, metadata: input.metadata ? JSON.stringify(input.metadata) : undefined }); }

export async function uploadResume(input: { organizationId: string; userId: string; candidateId: string; applicationId?: string; fileName: string; mimeType: string; bytes: Uint8Array; source?: string; makePrimary?: boolean; processNow?: boolean }) {
  await authorize({ organizationId: input.organizationId, permission: "ats.candidate.edit" });
  validateResumeFile({ fileName: input.fileName, mimeType: input.mimeType, size: input.bytes.byteLength });
  const [candidate] = await db.select().from(atsCandidates).where(and(eq(atsCandidates.id, input.candidateId), eq(atsCandidates.organizationId, input.organizationId)));
  if (!candidate) throw new AppError("NOT_FOUND", "Candidate was not found.", 404);
  const hash = resumeHash(input.bytes); const [duplicate] = await db.select().from(atsCandidateDocuments).where(and(eq(atsCandidateDocuments.organizationId, input.organizationId), eq(atsCandidateDocuments.candidateId, candidate.id), eq(atsCandidateDocuments.contentHash, hash)));
  if (duplicate) return { document: duplicate, duplicate: true, job: null };
  const previous = await db.select().from(atsCandidateDocuments).where(and(eq(atsCandidateDocuments.organizationId, input.organizationId), eq(atsCandidateDocuments.candidateId, candidate.id))).orderBy(desc(atsCandidateDocuments.version));
  const version = (previous[0]?.version ?? 0) + 1; const storageKey = `${input.organizationId}/candidates/${candidate.id}/resumes/v${version}-${crypto.randomUUID()}-${sanitizeFileName(input.fileName)}`; const storage = getStorageProvider(); await storage.upload(storageKey, input.bytes, input.mimeType);
  try {
    if (input.makePrimary !== false) await db.update(atsCandidateDocuments).set({ isPrimary: false, updatedAt: new Date() }).where(and(eq(atsCandidateDocuments.organizationId, input.organizationId), eq(atsCandidateDocuments.candidateId, candidate.id)));
    const [document] = await db.insert(atsCandidateDocuments).values({ organizationId: input.organizationId, candidateId: candidate.id, applicationId: input.applicationId, fileName: input.fileName, mimeType: input.mimeType, fileSize: input.bytes.byteLength, storageKey, contentHash: hash, source: input.source ?? "recruiter", version, isPrimary: input.makePrimary !== false, parsingStatus: "queued", processingVersion: PROCESSING_VERSION, scanStatus: "not_scanned", uploadedByUserId: input.userId }).returning();
    const idempotencyKey = `${document.id}:${PROCESSING_VERSION}:${hash}`; const [job] = await db.insert(atsResumeProcessingJobs).values({ organizationId: input.organizationId, candidateId: candidate.id, documentId: document.id, status: "queued", processingVersion: PROCESSING_VERSION, idempotencyKey }).onConflictDoNothing().returning(); await recordAudit({ actorUserId: input.userId, organizationId: input.organizationId, action: "ats_resume_uploaded", resource: "ats_candidate_document", resourceId: document.id, metadata: { candidateId: candidate.id, version } });
    if (input.processNow && job) await processResumeJob({ organizationId: input.organizationId, userId: input.userId, jobId: job.id });
    return { document, job, duplicate: false };
  } catch (error) { await storage.delete(storageKey); throw error; }
}
export async function uploadPublicResume(input: { organizationId: string; candidateId: string; applicationId: string; fileName: string; mimeType: string; bytes: Uint8Array }) { validateResumeFile({ fileName: input.fileName, mimeType: input.mimeType, size: input.bytes.byteLength }); const [candidate] = await db.select().from(atsCandidates).where(and(eq(atsCandidates.id, input.candidateId), eq(atsCandidates.organizationId, input.organizationId))); if (!candidate) throw new AppError("NOT_FOUND", "Candidate was not found.", 404); const hash = resumeHash(input.bytes); const [duplicate] = await db.select().from(atsCandidateDocuments).where(and(eq(atsCandidateDocuments.organizationId, input.organizationId), eq(atsCandidateDocuments.candidateId, candidate.id), eq(atsCandidateDocuments.contentHash, hash))); if (duplicate) return { document: duplicate, job: null, duplicate: true }; const previous = await db.select().from(atsCandidateDocuments).where(and(eq(atsCandidateDocuments.organizationId, input.organizationId), eq(atsCandidateDocuments.candidateId, candidate.id))).orderBy(desc(atsCandidateDocuments.version)); const version = (previous[0]?.version ?? 0) + 1; const storageKey = `${input.organizationId}/candidates/${candidate.id}/resumes/v${version}-${crypto.randomUUID()}-${sanitizeFileName(input.fileName)}`; const storage = getStorageProvider(); await storage.upload(storageKey, input.bytes, input.mimeType); try { const [document] = await db.insert(atsCandidateDocuments).values({ organizationId: input.organizationId, candidateId: candidate.id, applicationId: input.applicationId, fileName: input.fileName, mimeType: input.mimeType, fileSize: input.bytes.byteLength, storageKey, contentHash: hash, source: "public_application", version, isPrimary: true, parsingStatus: "queued", processingVersion: PROCESSING_VERSION, scanStatus: "not_scanned" }).returning(); const [job] = await db.insert(atsResumeProcessingJobs).values({ organizationId: input.organizationId, candidateId: candidate.id, documentId: document.id, status: "queued", processingVersion: PROCESSING_VERSION, idempotencyKey: `${document.id}:${PROCESSING_VERSION}:${hash}` }).returning(); await recordAudit({ organizationId: input.organizationId, action: "ats_public_resume_uploaded", resource: "ats_candidate_document", resourceId: document.id, metadata: { candidateId: candidate.id, applicationId: input.applicationId } }); return { document, job, duplicate: false }; } catch (error) { await storage.delete(storageKey); throw error; } }

export async function processResumeJob(input: { organizationId: string; userId?: string; jobId: string }) {
  await authorize({ organizationId: input.organizationId, permission: "ats.candidate.edit" });
  const [job] = await db.select().from(atsResumeProcessingJobs).where(and(eq(atsResumeProcessingJobs.id, input.jobId), eq(atsResumeProcessingJobs.organizationId, input.organizationId))); if (!job) throw new AppError("NOT_FOUND", "Resume processing job was not found.", 404); if (job.attemptCount >= MAX_ATTEMPTS) throw new AppError("VALIDATION_ERROR", "Resume processing retry limit has been reached.", 409);
  const [document] = await db.select().from(atsCandidateDocuments).where(and(eq(atsCandidateDocuments.id, job.documentId), eq(atsCandidateDocuments.organizationId, input.organizationId))); if (!document) throw new AppError("NOT_FOUND", "Resume document was not found.", 404); const [existing] = await db.select().from(atsResumeExtractions).where(eq(atsResumeExtractions.jobId, job.id)); if (existing) return existing;
  await db.update(atsResumeProcessingJobs).set({ status: "text_extracting", attemptCount: job.attemptCount + 1, startedAt: new Date(), updatedAt: new Date() }).where(eq(atsResumeProcessingJobs.id, job.id)); await db.update(atsCandidateDocuments).set({ parsingStatus: "processing", updatedAt: new Date() }).where(eq(atsCandidateDocuments.id, document.id));
  const bytes = await getStorageProvider().download(document.storageKey); const started = new Date();
  try {
    const extracted = await (textExtractor ?? defaultTextExtractor)({ bytes, mimeType: document.mimeType, fileName: document.fileName }); await writeAttempt({ organizationId: input.organizationId, jobId: job.id, stage: "text_extracting", status: "success", startedAt: started, metadata: { extractorVersion: extracted.extractorVersion, warnings: extracted.warnings } });
    await db.update(atsResumeProcessingJobs).set({ status: "parsing", updatedAt: new Date() }).where(eq(atsResumeProcessingJobs.id, job.id)); const normalized = parseDeterministicResume(extracted); await writeAttempt({ organizationId: input.organizationId, jobId: job.id, stage: "parsing", status: "success", startedAt: new Date() });
    await db.update(atsResumeProcessingJobs).set({ status: "normalizing", updatedAt: new Date() }).where(eq(atsResumeProcessingJobs.id, job.id)); await db.update(atsResumeProcessingJobs).set({ status: "skill_extracting", updatedAt: new Date() }).where(eq(atsResumeProcessingJobs.id, job.id)); await writeAttempt({ organizationId: input.organizationId, jobId: job.id, stage: "skill_extracting", status: "success", startedAt: new Date(), metadata: { skillCount: normalized.skills.length } });
    await db.update(atsResumeProcessingJobs).set({ status: "experience_analyzing", updatedAt: new Date() }).where(eq(atsResumeProcessingJobs.id, job.id)); await writeAttempt({ organizationId: input.organizationId, jobId: job.id, stage: "experience_analyzing", status: "success", startedAt: new Date(), metadata: { experienceCount: normalized.experience.length } });
    const [extraction] = await db.insert(atsResumeExtractions).values({ organizationId: input.organizationId, candidateId: job.candidateId, documentId: document.id, jobId: job.id, extractedText: extracted.text, normalizedResume: JSON.stringify(normalized), extractionSchemaVersion: "v1", processingVersion: PROCESSING_VERSION, provider: "deterministic", providerVersion: extracted.extractorVersion, warnings: JSON.stringify(extracted.warnings) }).returning();
    await db.update(atsResumeProcessingJobs).set({ status: "enriching", updatedAt: new Date() }).where(eq(atsResumeProcessingJobs.id, job.id));
    const fieldValues = [...(normalized.personal.email ? [{ fieldPath: "personal.email", value: normalized.personal.email, confidence: 0.98, confidenceSource: "deterministic", evidence: normalized.personal.email }] : []), ...(normalized.personal.phone ? [{ fieldPath: "personal.phone", value: normalized.personal.phone, confidence: 0.9, confidenceSource: "deterministic", evidence: normalized.personal.phone }] : [])]; await db.insert(atsResumeExtractionFields).values(fieldValues.map((field) => ({ organizationId: input.organizationId, extractionId: extraction.id, ...field }))); await db.insert(atsCandidateSkills).values(normalized.skills.map((skill) => ({ organizationId: input.organizationId, candidateId: job.candidateId, skillName: skill.name, normalizedSkillName: skill.normalizedName, category: skill.category, yearsExperience: skill.yearsExperience, proficiency: skill.proficiency, source: "resume", verified: false }))).onConflictDoNothing(); await db.insert(atsCandidateLinks).values(normalized.links.map((link) => ({ organizationId: input.organizationId, candidateId: job.candidateId, kind: link.kind, url: link.url, extractionId: extraction.id, confidence: link.confidence }))).onConflictDoNothing(); await db.insert(atsCandidateFieldProvenance).values(fieldValues.map((field) => ({ organizationId: input.organizationId, candidateId: job.candidateId, fieldPath: field.fieldPath, source: "resume", confidence: field.confidence, extractionId: extraction.id }))).onConflictDoUpdate({ target: [atsCandidateFieldProvenance.candidateId, atsCandidateFieldProvenance.fieldPath], set: { source: "resume", confidence: fieldValues[0]?.confidence, extractionId: extraction.id, updatedAt: new Date() } });
    await db.update(atsResumeProcessingJobs).set({ status: "completed", completedAt: new Date(), updatedAt: new Date() }).where(eq(atsResumeProcessingJobs.id, job.id)); await db.update(atsCandidateDocuments).set({ parsingStatus: "processed", processingVersion: PROCESSING_VERSION, providerMetadata: JSON.stringify({ provider: "deterministic", extractorVersion: extracted.extractorVersion }) }).where(eq(atsCandidateDocuments.id, document.id)); await db.insert(atsCandidateActivities).values({ organizationId: input.organizationId, candidateId: job.candidateId, activityType: "resume_processing_completed", metadata: JSON.stringify({ documentId: document.id, extractionId: extraction.id }), createdByUserId: input.userId }); await recordAudit({ actorUserId: input.userId, organizationId: input.organizationId, action: "ats_resume_processing_completed", resource: "ats_resume_processing_job", resourceId: job.id }); return extraction;
  } catch (error) { const message = errorMessage(error); await writeAttempt({ organizationId: input.organizationId, jobId: job.id, stage: "processing", status: "failed", startedAt: started, errorMessage: message }); await db.update(atsResumeProcessingJobs).set({ status: "processing_failed", failureReason: message, updatedAt: new Date() }).where(eq(atsResumeProcessingJobs.id, job.id)); await db.update(atsCandidateDocuments).set({ parsingStatus: "failed", updatedAt: new Date() }).where(eq(atsCandidateDocuments.id, document.id)); await recordAudit({ actorUserId: input.userId, organizationId: input.organizationId, action: "ats_resume_processing_failed", resource: "ats_resume_processing_job", resourceId: job.id, metadata: { error: message } }); throw new AppError("PROVISIONING_FAILED", "Resume processing failed. Review the processing status and retry when the provider is available.", 422); }
}

export async function retryResumeJob(input: { organizationId: string; userId: string; jobId: string }) { await authorize({ organizationId: input.organizationId, permission: "ats.candidate.edit" }); const [job] = await db.update(atsResumeProcessingJobs).set({ status: "queued", failureReason: null, retryAfter: null, updatedAt: new Date() }).where(and(eq(atsResumeProcessingJobs.id, input.jobId), eq(atsResumeProcessingJobs.organizationId, input.organizationId), inArray(atsResumeProcessingJobs.status, ["processing_failed", "text_extraction_failed", "parsing_failed", "skill_extraction_failed", "experience_analysis_failed"]))).returning(); if (!job) throw new AppError("VALIDATION_ERROR", "This resume job is not currently retryable.", 409); return job; }
export async function getResumeDownload(input: { organizationId: string; userId: string; documentId: string }) { await authorize({ organizationId: input.organizationId, permission: "ats.candidate.view" }); const [document] = await db.select().from(atsCandidateDocuments).where(and(eq(atsCandidateDocuments.id, input.documentId), eq(atsCandidateDocuments.organizationId, input.organizationId))); if (!document) throw new AppError("NOT_FOUND", "Resume was not found.", 404); return { url: await getStorageProvider().getSignedUrl(document.storageKey, 300), document }; }
export async function listResumeJobs(input: { organizationId: string; userId: string; candidateId: string }) { await authorize({ organizationId: input.organizationId, permission: "ats.candidate.view" }); return db.select().from(atsResumeProcessingJobs).where(and(eq(atsResumeProcessingJobs.organizationId, input.organizationId), eq(atsResumeProcessingJobs.candidateId, input.candidateId))).orderBy(desc(atsResumeProcessingJobs.createdAt)); }
export async function reviewExtractionField(input: { organizationId: string; userId: string; fieldId: string; status: "reviewed" | "confirmed" | "rejected" }) { await authorize({ organizationId: input.organizationId, permission: "ats.candidate.edit" }); const [field] = await db.select().from(atsResumeExtractionFields).where(and(eq(atsResumeExtractionFields.id, input.fieldId), eq(atsResumeExtractionFields.organizationId, input.organizationId))); if (!field) throw new AppError("NOT_FOUND", "Extraction field was not found.", 404); const [updated] = await db.update(atsResumeExtractionFields).set({ reviewStatus: input.status, updatedAt: new Date() }).where(eq(atsResumeExtractionFields.id, field.id)).returning(); if (input.status === "confirmed") await db.insert(atsCandidateFieldProvenance).values({ organizationId: input.organizationId, candidateId: (await db.select({ candidateId: atsResumeExtractions.candidateId }).from(atsResumeExtractions).where(eq(atsResumeExtractions.id, field.extractionId)))[0]?.candidateId ?? "", fieldPath: field.fieldPath, source: "recruiter", confidence: 1, confirmedByUserId: input.userId, confirmedAt: new Date(), extractionId: field.extractionId }).onConflictDoUpdate({ target: [atsCandidateFieldProvenance.candidateId, atsCandidateFieldProvenance.fieldPath], set: { source: "recruiter", confidence: 1, confirmedByUserId: input.userId, confirmedAt: new Date(), extractionId: field.extractionId, updatedAt: new Date() } }); await recordAudit({ actorUserId: input.userId, organizationId: input.organizationId, action: `ats_resume_field_${input.status}`, resource: "ats_resume_extraction_field", resourceId: field.id }); return updated; }
export async function updateResumeProcessingConfig(input: { organizationId: string; userId: string; data: { aiResumeProcessingEnabled?: boolean; provider?: string; processingStrategy?: string; maxFileSize?: number; allowedFileTypes?: string; retryLimit?: number } }) { await authorize({ organizationId: input.organizationId, permission: "ats.manage" }); const [config] = await db.insert(atsResumeProcessingConfigs).values({ organizationId: input.organizationId, ...input.data }).onConflictDoUpdate({ target: atsResumeProcessingConfigs.organizationId, set: { ...input.data, updatedAt: new Date() } }).returning(); await recordAudit({ actorUserId: input.userId, organizationId: input.organizationId, action: "ats_resume_processing_config_updated", resource: "ats_resume_processing_config", resourceId: config.id, metadata: { provider: config.provider, aiResumeProcessingEnabled: config.aiResumeProcessingEnabled } }); return config; }
export async function getResumeProcessingConfig(organizationId: string) { const [config] = await db.select().from(atsResumeProcessingConfigs).where(eq(atsResumeProcessingConfigs.organizationId, organizationId)); return config ?? { aiResumeProcessingEnabled: false, provider: "deterministic", processingStrategy: "deterministic_first", maxFileSize: 10 * 1024 * 1024, retryLimit: 2 }; }
export async function getCandidateResumeProfile(input: { organizationId: string; userId: string; candidateId: string }) { await authorize({ organizationId: input.organizationId, permission: "ats.candidate.view" }); const [candidate] = await db.select().from(atsCandidates).where(and(eq(atsCandidates.id, input.candidateId), eq(atsCandidates.organizationId, input.organizationId))); if (!candidate) throw new AppError("NOT_FOUND", "Candidate was not found.", 404); const documents = await db.select().from(atsCandidateDocuments).where(and(eq(atsCandidateDocuments.organizationId, input.organizationId), eq(atsCandidateDocuments.candidateId, candidate.id))).orderBy(desc(atsCandidateDocuments.version)); const jobs = await db.select().from(atsResumeProcessingJobs).where(and(eq(atsResumeProcessingJobs.organizationId, input.organizationId), eq(atsResumeProcessingJobs.candidateId, candidate.id))).orderBy(desc(atsResumeProcessingJobs.createdAt)); const extractions = await db.select().from(atsResumeExtractions).where(and(eq(atsResumeExtractions.organizationId, input.organizationId), eq(atsResumeExtractions.candidateId, candidate.id))).orderBy(desc(atsResumeExtractions.createdAt)); return { candidate, documents, jobs, extractions: extractions.map((item) => ({ ...item, normalizedResume: JSON.parse(item.normalizedResume) as unknown })) }; }
