"use client";

import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
type Notification = { id: string; title: string; message: string; actionUrl?: string | null; readAt?: string | null; createdAt: string };

export function NotificationCenter() { const [items, setItems] = useState<Notification[]>([]); const [unread, setUnread] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const load = async () => { setLoading(true); setError(""); try { const response = await fetch("/api/app/notifications"); const body = await response.json(); if (!response.ok || !body.success) throw new Error(body.error?.message ?? "Unable to load notifications."); setItems(body.notifications); setUnread(body.unreadCount); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load notifications."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const markRead = async (id: string) => { setBusy(true); await fetch(`/api/app/notifications/${id}`, { method: "POST" }); await load(); setBusy(false); };
  const markAll = async () => { setBusy(true); await fetch("/api/app/notifications", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ markAllRead: true }) }); await load(); setBusy(false); };
  return <div className="space-y-4"><div className="flex items-center justify-between"><p className="text-sm text-muted">{unread} unread</p><Button size="sm" variant="secondary" disabled={busy || unread === 0} onClick={markAll}>Mark all read</Button></div>{error && <p role="alert" className="text-sm text-danger">{error}</p>}{loading ? <p className="text-sm text-muted">Loading notifications…</p> : items.length === 0 ? <p className="rounded-xl border border-dashed p-6 text-sm text-muted">You are all caught up.</p> : items.map((item) => <div key={item.id} className={`rounded-xl border p-4 ${item.readAt ? "opacity-70" : "bg-surface"}`}><div className="flex items-start justify-between gap-4"><div><p className="font-medium">{item.title}</p><p className="mt-1 text-sm text-muted">{item.message}</p><p className="mt-2 text-xs text-muted">{new Date(item.createdAt).toLocaleString()}</p></div>{!item.readAt && <Button size="sm" variant="ghost" disabled={busy} onClick={() => markRead(item.id)}>Mark read</Button>}</div>{item.actionUrl && <a className="mt-2 inline-block text-sm font-semibold text-primary" href={item.actionUrl}>Open</a>}</div>)}</div>; }
