export const PERMISSIONS = {
  organizationRead: "organization.read", organizationCreate: "organization.create", organizationUpdate: "organization.update", organizationSuspend: "organization.suspend", organizationManage: "organization.manage",
  membershipRead: "membership.read", membershipInvite: "membership.invite", membershipUpdate: "membership.update", membershipRemove: "membership.remove", roleRead: "role.read", roleManage: "role.manage",
  employeeRead: "employee.read", employeeCreate: "employee.create", employeeUpdate: "employee.update", employeeDelete: "employee.delete", attendanceRead: "attendance.read", attendanceManage: "attendance.manage",
  leaveRead: "leave.read", leaveApply: "leave.apply", leaveApprove: "leave.approve", expenseRead: "expense.read", expenseCreate: "expense.create", expenseApprove: "expense.approve", payrollRead: "payroll.read", payrollManage: "payroll.manage",
  jobRead: "job.read", jobCreate: "job.create", jobUpdate: "job.update", candidateRead: "candidate.read", candidateCreate: "candidate.create", candidateUpdate: "candidate.update", taskRead: "task.read", taskCreate: "task.create", taskAssign: "task.assign", taskUpdate: "task.update", chatRead: "chat.read", chatSend: "chat.send",
  organizationSettingsRead: "organization.settings.read", organizationSettingsUpdate: "organization.settings.update", departmentRead: "department.read", departmentCreate: "department.create", departmentUpdate: "department.update", departmentManage: "department.manage", designationRead: "designation.read", designationCreate: "designation.create", designationUpdate: "designation.update", designationManage: "designation.manage", locationRead: "location.read", locationCreate: "location.create", locationUpdate: "location.update", locationManage: "location.manage", teamRead: "team.read", teamCreate: "team.create", teamUpdate: "team.update", teamManage: "team.manage", employeeManage: "employee.manage", employeeInvite: "employee.invite", employeeOnboard: "employee.onboard", employeeActivate: "employee.activate", employeeDeactivate: "employee.deactivate", employeeSelfRead: "employee.self.read", employeeSelfUpdate: "employee.self.update", documentRead: "document.read", documentUpload: "document.upload",
  attendanceClockIn: "attendance.clockin", attendanceClockOut: "attendance.clockout", attendanceBreak: "attendance.break", attendanceRegularizationCreate: "attendance.regularization.create", attendanceRegularizationRead: "attendance.regularization.read", attendanceRegularizationApprove: "attendance.regularization.approve", leaveCancel: "leave.cancel", leaveManage: "leave.manage", leaveBalanceRead: "leave.balance.read", leaveBalanceAdjust: "leave.balance.adjust", leavePolicyManage: "leave.policy.manage", leaveTypeManage: "leave.type.manage", workflowRead: "workflow.read", workflowCreate: "workflow.create", workflowUpdate: "workflow.update", workflowActivate: "workflow.activate", workflowApprove: "workflow.approve", workflowManage: "workflow.manage",
} as const;
export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
export const ALL_PERMISSION_KEYS = Object.values(PERMISSIONS);
export const SYSTEM_ROLES = ["PLATFORM_OWNER", "ORGANIZATION_OWNER", "ORGANIZATION_ADMIN", "HR_ADMIN", "HR_EXECUTIVE", "RECRUITER", "MANAGER", "TEAM_LEAD", "EMPLOYEE", "FINANCE_ADMIN", "PROJECT_MANAGER"] as const;
export type SystemRole = (typeof SYSTEM_ROLES)[number];

export const ROLE_PERMISSIONS: Record<string, readonly Permission[]> = {
  ORGANIZATION_OWNER: ALL_PERMISSION_KEYS,
  ORGANIZATION_ADMIN: ALL_PERMISSION_KEYS,
  HR_ADMIN: [PERMISSIONS.organizationRead, PERMISSIONS.membershipRead, PERMISSIONS.membershipInvite, PERMISSIONS.membershipUpdate, PERMISSIONS.roleRead, PERMISSIONS.employeeRead, PERMISSIONS.employeeCreate, PERMISSIONS.employeeUpdate, PERMISSIONS.attendanceRead, PERMISSIONS.attendanceManage, PERMISSIONS.attendanceRegularizationRead, PERMISSIONS.attendanceRegularizationApprove, PERMISSIONS.leaveRead, PERMISSIONS.leaveApprove, PERMISSIONS.leaveManage, PERMISSIONS.leaveBalanceRead, PERMISSIONS.leaveBalanceAdjust, PERMISSIONS.leavePolicyManage, PERMISSIONS.leaveTypeManage, PERMISSIONS.workflowRead, PERMISSIONS.workflowManage],
  RECRUITER: [PERMISSIONS.organizationRead, PERMISSIONS.jobRead, PERMISSIONS.jobCreate, PERMISSIONS.jobUpdate, PERMISSIONS.candidateRead, PERMISSIONS.candidateCreate, PERMISSIONS.candidateUpdate],
  MANAGER: [PERMISSIONS.organizationRead, PERMISSIONS.employeeRead, PERMISSIONS.attendanceRead, PERMISSIONS.attendanceRegularizationRead, PERMISSIONS.attendanceRegularizationApprove, PERMISSIONS.leaveRead, PERMISSIONS.leaveApprove, PERMISSIONS.workflowRead, PERMISSIONS.workflowApprove],
  TEAM_LEAD: [PERMISSIONS.organizationRead, PERMISSIONS.employeeRead, PERMISSIONS.attendanceRead, PERMISSIONS.attendanceRegularizationRead, PERMISSIONS.attendanceRegularizationApprove, PERMISSIONS.leaveRead, PERMISSIONS.leaveApprove, PERMISSIONS.workflowRead, PERMISSIONS.workflowApprove],
  EMPLOYEE: [PERMISSIONS.organizationRead, PERMISSIONS.attendanceRead, PERMISSIONS.attendanceClockIn, PERMISSIONS.attendanceClockOut, PERMISSIONS.attendanceBreak, PERMISSIONS.attendanceRegularizationCreate, PERMISSIONS.attendanceRegularizationRead, PERMISSIONS.leaveRead, PERMISSIONS.leaveApply, PERMISSIONS.leaveBalanceRead, PERMISSIONS.expenseRead, PERMISSIONS.expenseCreate, PERMISSIONS.taskRead, PERMISSIONS.taskCreate, PERMISSIONS.taskUpdate, PERMISSIONS.chatRead, PERMISSIONS.chatSend],
};
