export const PERMISSIONS = {
  organizationRead: "organization.read", organizationCreate: "organization.create", organizationUpdate: "organization.update", organizationSuspend: "organization.suspend", organizationManage: "organization.manage",
  membershipRead: "membership.read", membershipInvite: "membership.invite", membershipUpdate: "membership.update", membershipRemove: "membership.remove", roleRead: "role.read", roleManage: "role.manage",
  employeeRead: "employee.read", employeeCreate: "employee.create", employeeUpdate: "employee.update", employeeDelete: "employee.delete", attendanceRead: "attendance.read", attendanceManage: "attendance.manage",
  leaveRead: "leave.read", leaveApply: "leave.apply", leaveApprove: "leave.approve",
  jobRead: "job.read", jobCreate: "job.create", jobUpdate: "job.update", candidateRead: "candidate.read", candidateCreate: "candidate.create", candidateUpdate: "candidate.update", taskRead: "task.read", taskCreate: "task.create", taskAssign: "task.assign", taskUpdate: "task.update", chatRead: "chat.read", chatSend: "chat.send",
  organizationSettingsRead: "organization.settings.read", organizationSettingsUpdate: "organization.settings.update", departmentRead: "department.read", departmentCreate: "department.create", departmentUpdate: "department.update", departmentManage: "department.manage", designationRead: "designation.read", designationCreate: "designation.create", designationUpdate: "designation.update", designationManage: "designation.manage", locationRead: "location.read", locationCreate: "location.create", locationUpdate: "location.update", locationManage: "location.manage", teamRead: "team.read", teamCreate: "team.create", teamUpdate: "team.update", teamManage: "team.manage", employeeManage: "employee.manage", employeeInvite: "employee.invite", employeeOnboard: "employee.onboard", employeeActivate: "employee.activate", employeeDeactivate: "employee.deactivate", employeeSelfRead: "employee.self.read", employeeSelfUpdate: "employee.self.update", documentRead: "document.read", documentUpload: "document.upload",
  attendanceClockIn: "attendance.clockin", attendanceClockOut: "attendance.clockout", attendanceBreak: "attendance.break", attendanceRegularizationCreate: "attendance.regularization.create", attendanceRegularizationRead: "attendance.regularization.read", attendanceRegularizationApprove: "attendance.regularization.approve", leaveCancel: "leave.cancel", leaveManage: "leave.manage", leaveBalanceRead: "leave.balance.read", leaveBalanceAdjust: "leave.balance.adjust", leavePolicyManage: "leave.policy.manage", leaveTypeManage: "leave.type.manage", workflowRead: "workflow.read", workflowCreate: "workflow.create", workflowUpdate: "workflow.update", workflowActivate: "workflow.activate", workflowApprove: "workflow.approve", workflowManage: "workflow.manage",
  expenseRead: "expense.read", expenseCreate: "expense.create", expenseUpdate: "expense.update", expenseSubmit: "expense.submit", expenseCancel: "expense.cancel", expenseApprove: "expense.approve", expenseManage: "expense.manage", expensePolicyManage: "expense.policy.manage", expenseCategoryManage: "expense.category.manage", expenseReimbursementManage: "expense.reimbursement.manage", documentUpdate: "document.update", documentVerify: "document.verify", documentReject: "document.reject", documentManage: "document.manage", documentDownload: "document.download", notificationRead: "notification.read", notificationManage: "notification.manage", notificationPreferenceUpdate: "notification.preference.update",
  payrollView: "payroll.view", payrollManage: "payroll.manage", payrollConfigure: "payroll.configure", payrollCalculate: "payroll.calculate", payrollReview: "payroll.review", payrollApprove: "payroll.approve", payrollFinalize: "payroll.finalize", payrollViewAll: "payroll.viewall", payrollViewSelf: "payroll.viewself", payslipView: "payslip.view", payslipDownload: "payslip.download",
  atsView: "ats.view", atsManage: "ats.manage", atsRequisitionCreate: "ats.requisition.create", atsRequisitionView: "ats.requisition.view", atsRequisitionApprove: "ats.requisition.approve", atsRequisitionEdit: "ats.requisition.edit", atsRequisitionClose: "ats.requisition.close", atsJobCreate: "ats.job.create", atsJobEdit: "ats.job.edit", atsJobPublish: "ats.job.publish", atsJobUnpublish: "ats.job.unpublish", atsJobView: "ats.job.view", atsCandidateCreate: "ats.candidate.create", atsCandidateView: "ats.candidate.view", atsCandidateEdit: "ats.candidate.edit", atsCandidateDelete: "ats.candidate.delete", atsCandidateImport: "ats.candidate.import", atsCandidateExport: "ats.candidate.export", atsApplicationView: "ats.application.view", atsApplicationCreate: "ats.application.create", atsApplicationMove: "ats.application.move", atsInterviewCreate: "ats.interview.create", atsInterviewView: "ats.interview.view", atsInterviewEdit: "ats.interview.edit", atsInterviewFeedback: "ats.interview.feedback", atsAssessmentManage: "ats.assessment.manage", atsTalentPoolManage: "ats.talentpool.manage", atsAnalyticsView: "ats.analytics.view",
} as const;
export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
export const ALL_PERMISSION_KEYS = Object.values(PERMISSIONS);
export const SYSTEM_ROLES = ["PLATFORM_OWNER", "ORGANIZATION_OWNER", "ORGANIZATION_ADMIN", "HR_ADMIN", "HR_EXECUTIVE", "RECRUITER", "MANAGER", "TEAM_LEAD", "EMPLOYEE", "FINANCE_ADMIN", "PROJECT_MANAGER"] as const;
export type SystemRole = (typeof SYSTEM_ROLES)[number];

export const ROLE_PERMISSIONS: Record<string, readonly Permission[]> = {
  ORGANIZATION_OWNER: ALL_PERMISSION_KEYS,
  ORGANIZATION_ADMIN: ALL_PERMISSION_KEYS,
  HR_ADMIN: [PERMISSIONS.organizationRead, PERMISSIONS.membershipRead, PERMISSIONS.membershipInvite, PERMISSIONS.membershipUpdate, PERMISSIONS.roleRead, PERMISSIONS.employeeRead, PERMISSIONS.employeeCreate, PERMISSIONS.employeeUpdate, PERMISSIONS.attendanceRead, PERMISSIONS.attendanceManage, PERMISSIONS.attendanceRegularizationRead, PERMISSIONS.attendanceRegularizationApprove, PERMISSIONS.leaveRead, PERMISSIONS.leaveApprove, PERMISSIONS.leaveManage, PERMISSIONS.leaveBalanceRead, PERMISSIONS.leaveBalanceAdjust, PERMISSIONS.leavePolicyManage, PERMISSIONS.leaveTypeManage, PERMISSIONS.workflowRead, PERMISSIONS.workflowManage, PERMISSIONS.expenseRead, PERMISSIONS.expenseManage, PERMISSIONS.expensePolicyManage, PERMISSIONS.expenseCategoryManage, PERMISSIONS.documentRead, PERMISSIONS.documentUpload, PERMISSIONS.documentVerify, PERMISSIONS.documentReject, PERMISSIONS.documentManage, PERMISSIONS.notificationRead, PERMISSIONS.notificationManage, PERMISSIONS.payrollView, PERMISSIONS.payrollManage, PERMISSIONS.payrollConfigure, PERMISSIONS.payrollCalculate, PERMISSIONS.payrollReview, PERMISSIONS.payrollApprove, PERMISSIONS.payrollFinalize, PERMISSIONS.payrollViewAll, PERMISSIONS.payslipView, PERMISSIONS.payslipDownload],
  RECRUITER: [PERMISSIONS.organizationRead, PERMISSIONS.atsView, PERMISSIONS.atsManage, PERMISSIONS.atsRequisitionCreate, PERMISSIONS.atsRequisitionView, PERMISSIONS.atsRequisitionEdit, PERMISSIONS.atsJobCreate, PERMISSIONS.atsJobEdit, PERMISSIONS.atsJobPublish, PERMISSIONS.atsJobUnpublish, PERMISSIONS.atsJobView, PERMISSIONS.atsCandidateCreate, PERMISSIONS.atsCandidateView, PERMISSIONS.atsCandidateEdit, PERMISSIONS.atsCandidateImport, PERMISSIONS.atsCandidateExport, PERMISSIONS.atsApplicationView, PERMISSIONS.atsApplicationCreate, PERMISSIONS.atsApplicationMove, PERMISSIONS.atsInterviewCreate, PERMISSIONS.atsInterviewView, PERMISSIONS.atsInterviewEdit, PERMISSIONS.atsInterviewFeedback, PERMISSIONS.atsAssessmentManage, PERMISSIONS.atsTalentPoolManage, PERMISSIONS.atsAnalyticsView],
  MANAGER: [PERMISSIONS.organizationRead, PERMISSIONS.employeeRead, PERMISSIONS.attendanceRead, PERMISSIONS.attendanceRegularizationRead, PERMISSIONS.attendanceRegularizationApprove, PERMISSIONS.leaveRead, PERMISSIONS.leaveApprove, PERMISSIONS.expenseRead, PERMISSIONS.expenseApprove, PERMISSIONS.workflowRead, PERMISSIONS.workflowApprove, PERMISSIONS.payrollView, PERMISSIONS.payrollReview, PERMISSIONS.payrollApprove, PERMISSIONS.payslipView],
  TEAM_LEAD: [PERMISSIONS.organizationRead, PERMISSIONS.employeeRead, PERMISSIONS.attendanceRead, PERMISSIONS.attendanceRegularizationRead, PERMISSIONS.attendanceRegularizationApprove, PERMISSIONS.leaveRead, PERMISSIONS.leaveApprove, PERMISSIONS.expenseRead, PERMISSIONS.expenseApprove, PERMISSIONS.workflowRead, PERMISSIONS.workflowApprove, PERMISSIONS.payrollView, PERMISSIONS.payrollReview, PERMISSIONS.payrollApprove, PERMISSIONS.payslipView],
  FINANCE_ADMIN: [PERMISSIONS.organizationRead, PERMISSIONS.expenseRead, PERMISSIONS.expenseApprove, PERMISSIONS.expenseManage, PERMISSIONS.expensePolicyManage, PERMISSIONS.expenseCategoryManage, PERMISSIONS.expenseReimbursementManage, PERMISSIONS.workflowRead, PERMISSIONS.workflowApprove, PERMISSIONS.notificationRead, PERMISSIONS.notificationManage, PERMISSIONS.payrollView, PERMISSIONS.payrollManage, PERMISSIONS.payrollConfigure, PERMISSIONS.payrollCalculate, PERMISSIONS.payrollReview, PERMISSIONS.payrollApprove, PERMISSIONS.payrollFinalize, PERMISSIONS.payrollViewAll, PERMISSIONS.payslipView, PERMISSIONS.payslipDownload],
  EMPLOYEE: [PERMISSIONS.organizationRead, PERMISSIONS.attendanceRead, PERMISSIONS.attendanceClockIn, PERMISSIONS.attendanceClockOut, PERMISSIONS.attendanceBreak, PERMISSIONS.attendanceRegularizationCreate, PERMISSIONS.attendanceRegularizationRead, PERMISSIONS.leaveRead, PERMISSIONS.leaveApply, PERMISSIONS.leaveBalanceRead, PERMISSIONS.expenseRead, PERMISSIONS.expenseCreate, PERMISSIONS.expenseUpdate, PERMISSIONS.expenseSubmit, PERMISSIONS.expenseCancel, PERMISSIONS.documentRead, PERMISSIONS.documentUpload, PERMISSIONS.documentUpdate, PERMISSIONS.documentDownload, PERMISSIONS.notificationRead, PERMISSIONS.notificationPreferenceUpdate, PERMISSIONS.payrollView, PERMISSIONS.payrollViewSelf, PERMISSIONS.payslipView, PERMISSIONS.payslipDownload, PERMISSIONS.taskRead, PERMISSIONS.taskCreate, PERMISSIONS.taskUpdate, PERMISSIONS.chatRead, PERMISSIONS.chatSend],
};
