import { ArrowUpRight, BriefcaseBusiness, Clock3, FileText, UsersRound } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const stats = [{ label: "Team members", value: "—", note: "Ready for Prompt 2", icon: UsersRound }, { label: "Open positions", value: "—", note: "Recruitment not enabled", icon: BriefcaseBusiness }, { label: "Pending approvals", value: "—", note: "Workflows not enabled", icon: Clock3 }];

export function Overview() {
  return <div className="space-y-8"><section className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><Badge>Foundation workspace</Badge><h1 className="mt-3 text-3xl font-bold tracking-tight md:text-4xl">Good morning, Alex.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">Your SymphoWork foundation is ready. This workspace will become the single, clear home for people operations and talent workflows.</p></div><Button variant="secondary">View documentation <ArrowUpRight className="size-4" /></Button></section><section className="grid gap-4 md:grid-cols-3">{stats.map(({ label, value, note, icon: Icon }) => <Card key={label}><CardContent className="flex items-start justify-between pt-5"><div><p className="text-sm text-muted">{label}</p><p className="mt-3 text-3xl font-bold">{value}</p><p className="mt-2 text-xs text-muted">{note}</p></div><div className="rounded-xl bg-[#e9f1ff] p-2.5 text-primary"><Icon className="size-5" /></div></CardContent></Card>)}</section><div className="grid gap-5 lg:grid-cols-[1.25fr_0.75fr]"><Card><CardHeader><CardTitle>Platform foundation</CardTitle><p className="mt-1 text-sm text-muted">What is available in this first milestone.</p></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2">{["Responsive application shell", "Typed environment configuration", "PostgreSQL + Drizzle foundation", "Structured logging and errors", "Provider interfaces for email, storage, AI", "Vitest + Playwright test setup"].map((item) => <div key={item} className="flex items-center gap-3 rounded-xl border bg-[#fbfcfe] p-3 text-sm"><span className="grid size-5 place-items-center rounded-full bg-[#dff7ee] text-xs font-bold text-success">✓</span>{item}</div>)}</div></CardContent></Card><Card><CardHeader><CardTitle>Next milestone</CardTitle><p className="mt-1 text-sm text-muted">Authentication and tenant boundaries.</p></CardHeader><CardContent><div className="rounded-xl bg-[#f0f7ff] p-4"><FileText className="size-5 text-primary" /><p className="mt-3 text-sm font-semibold">Prompt 2 is ready to build on this foundation.</p><p className="mt-1 text-sm leading-6 text-muted">Add authentication, organizations, membership, RBAC, and tenant-aware request context.</p><Button className="mt-4 w-full" size="sm">Read architecture notes</Button></div></CardContent></Card></div></div>;
}
