"use client";

import { useEffect, useState } from "react";
import { ArrowUpRight, Clock3, FileText, UsersRound } from "lucide-react";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

type Metric = { label: string; value: string; note: string; href: string; icon: typeof UsersRound };
export function Overview({ fullName }: { fullName: string }) { const [metrics, setMetrics] = useState<Metric[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { let active = true; const load = async () => { try { const [employeesResponse, approvalsResponse, notificationsResponse] = await Promise.all([fetch("/api/app/employees?limit=1"), fetch("/api/app/approvals"), fetch("/api/app/notifications?unread=true")]); const [employeesBody, approvalsBody, notificationsBody] = await Promise.all([employeesResponse.json(), approvalsResponse.json(), notificationsResponse.json()]); if (!active) return; setMetrics([{ label: "Team members", value: employeesBody.success ? String(employeesBody.total ?? employeesBody.employees?.length ?? 0) : "—", note: employeesBody.success ? "Active directory" : "Unavailable", href: "/app/employees", icon: UsersRound }, { label: "Pending approvals", value: approvalsBody.success ? String(approvalsBody.tasks.filter((task: { status: string }) => task.status === "pending").length) : "—", note: approvalsBody.success ? "Assigned to you" : "Unavailable", href: "/app/approvals", icon: Clock3 }, { label: "Unread notifications", value: notificationsBody.success ? String(notificationsBody.unreadCount) : "—", note: notificationsBody.success ? "Needs attention" : "Unavailable", href: "/app/notifications", icon: FileText }]); } catch (cause) { if (active) setError(cause instanceof Error ? cause.message : "Some workspace metrics are unavailable."); } finally { if (active) setLoading(false); } }; void load(); return () => { active = false; }; }, []);
  return <div className="space-y-8"><section className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><Badge>Workspace</Badge><h1 className="mt-3 text-3xl font-bold tracking-tight md:text-4xl">Good morning, {fullName}.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">Your people-operations workspace, with the latest tasks and activity in one place.</p></div><Button asChild variant="secondary"><Link href="/app/notifications">View notifications <ArrowUpRight className="size-4" /></Link></Button></section>{error && <p role="alert" className="text-sm text-danger">{error}</p>}<section className="grid gap-4 md:grid-cols-3">{loading ? [1, 2, 3].map((item) => <Card key={item}><CardContent className="pt-5"><div className="h-20 animate-pulse rounded bg-surface" /></CardContent></Card>) : metrics.map(({ label, value, note, href, icon: Icon }) => <Link key={label} href={href}><Card className="h-full transition hover:-translate-y-0.5 hover:shadow-sm"><CardContent className="flex items-start justify-between pt-5"><div><p className="text-sm text-muted">{label}</p><p className="mt-3 text-3xl font-bold">{value}</p><p className="mt-2 text-xs text-muted">{note}</p></div><div className="rounded-xl bg-[#e9f1ff] p-2.5 text-primary"><Icon className="size-5" /></div></CardContent></Card></Link>)}</section><div className="grid gap-5 lg:grid-cols-3"><Card><CardHeader><CardTitle>Attendance</CardTitle><p className="text-sm text-muted">Record today’s time and review history.</p></CardHeader><CardContent><Button asChild size="sm"><Link href="/app/attendance">Open attendance</Link></Button></CardContent></Card><Card><CardHeader><CardTitle>Leave</CardTitle><p className="text-sm text-muted">Check balances and submit a request.</p></CardHeader><CardContent><Button asChild size="sm"><Link href="/app/leave">Open leave</Link></Button></CardContent></Card><Card><CardHeader><CardTitle>Expenses</CardTitle><p className="text-sm text-muted">Create and track reimbursement claims.</p></CardHeader><CardContent><Button asChild size="sm"><Link href="/app/expenses">Open expenses</Link></Button></CardContent></Card></div></div>; }
