import { and, eq } from "drizzle-orm";
import { NextResponse } from "next/server";
import { db } from "@/db/client";
import { expenseClaims, expenseHistory, expenseItems, expenseReceipts } from "@/db/schema";
import { errorResponse, AppError } from "@/lib/errors";
import { resolveTenantContext } from "@/modules/tenancy/context";
import { authorize } from "@/modules/tenancy/authorization";
import { canTransitionExpenseStatus } from "@/modules/expenses/calculator";
import { getOrEnsureEmployeeForUser } from "@/modules/employees/service";

export async function GET(_request: Request, context: { params: Promise<{ claimId: string }> }) { try { const tenant = await resolveTenantContext(); if (!tenant.organization) throw new AppError("FORBIDDEN", "Organization context is required.", 403); await authorize({ organizationId: tenant.organization.id, permission: "expense.read" }); const { claimId } = await context.params; const employee = await getOrEnsureEmployeeForUser(tenant.organization.id, tenant.user.id).catch(() => null); const [claim] = employee ? await db.select().from(expenseClaims).where(and(eq(expenseClaims.id, claimId), eq(expenseClaims.organizationId, tenant.organization.id), eq(expenseClaims.employeeId, employee.id))) : []; if (!claim) throw new AppError("NOT_FOUND", "Expense claim was not found.", 404); const items = await db.select().from(expenseItems).where(eq(expenseItems.claimId, claim.id)); const receipts = await db.select({ id: expenseReceipts.id, itemId: expenseReceipts.itemId, fileName: expenseReceipts.fileName, scanStatus: expenseReceipts.scanStatus, verificationStatus: expenseReceipts.verificationStatus, uploadedAt: expenseReceipts.uploadedAt }).from(expenseReceipts).where(eq(expenseReceipts.organizationId, tenant.organization.id)); return NextResponse.json({ success: true, claim, items, receipts: receipts.filter((receipt) => items.some((item) => item.id === receipt.itemId)), history: await db.select().from(expenseHistory).where(eq(expenseHistory.claimId, claim.id)) }); } catch (error) { return errorResponse(error); } }
export async function PATCH(request: Request, context: { params: Promise<{ claimId: string }> }) { try { const tenant = await resolveTenantContext(); if (!tenant.organization) throw new AppError("FORBIDDEN", "Organization context is required.", 403); await authorize({ organizationId: tenant.organization.id, permission: "expense.cancel" }); const { claimId } = await context.params; const [claim] = await db.select().from(expenseClaims).where(and(eq(expenseClaims.id, claimId), eq(expenseClaims.organizationId, tenant.organization.id))); if (!claim) throw new AppError("NOT_FOUND", "Expense claim was not found.", 404); const body = await request.json() as { action?: "cancel" }; if (body.action !== "cancel" || !canTransitionExpenseStatus(claim.status, "cancelled")) throw new AppError("VALIDATION_ERROR", "This expense claim cannot be cancelled.", 409); const [updated] = await db.update(expenseClaims).set({ status: "cancelled", cancelledAt: new Date(), updatedAt: new Date() }).where(eq(expenseClaims.id, claim.id)).returning(); await db.insert(expenseHistory).values({ organizationId: tenant.organization.id, claimId: claim.id, actorUserId: tenant.user.id, action: "cancelled", previousStatus: claim.status, newStatus: "cancelled" }); return NextResponse.json({ success: true, claim: updated }); } catch (error) { return errorResponse(error); } }
