import Link from "next/link";
import { redirect } from "next/navigation";
import { count, desc, eq } from "drizzle-orm";
import { db } from "@/db/client";
import { organizations, provisioningJobs } from "@/db/schema";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { authorizePlatform, PLATFORM_PERMISSIONS } from "@/modules/platform/authorization";
export default async function PlatformPage() { try { await authorizePlatform(PLATFORM_PERMISSIONS.organizationView); } catch { redirect("/platform/login"); } const [total, active, pending, suspended, recent, jobs] = await Promise.all([db.select({ value: count() }).from(organizations), db.select({ value: count() }).from(organizations).where(eq(organizations.status, "active")), db.select({ value: count() }).from(organizations).where(eq(organizations.status, "pending")), db.select({ value: count() }).from(organizations).where(eq(organizations.status, "suspended")), db.select().from(organizations).orderBy(desc(organizations.createdAt)).limit(5), db.select().from(provisioningJobs).orderBy(desc(provisioningJobs.createdAt)).limit(5)]); const cards = [["Total organizations", total[0].value], ["Active", active[0].value], ["Onboarding", pending[0].value], ["Suspended", suspended[0].value]]; return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><Badge>Platform console</Badge><h1 className="mt-3 text-3xl font-bold">Operational overview</h1><p className="mt-2 text-sm text-muted">SaaS organization lifecycle and provisioning activity.</p></div><Button asChild><Link href="/platform/organizations/new">Create organization</Link></Button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value]) => <Card key={label}><CardContent className="p-5"><p className="text-sm text-muted">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></CardContent></Card>)}</div><div className="grid gap-5 xl:grid-cols-2"><Card><CardHeader><CardTitle>Recent organizations</CardTitle></CardHeader><CardContent>{recent.length ? <div className="space-y-3">{recent.map((row) => <Link key={row.id} href={`/platform/organizations/${row.id}`} className="flex items-center justify-between rounded-xl border p-3 hover:bg-muted/30"><span><span className="block font-semibold">{row.name}</span><span className="text-xs text-muted">{row.slug}</span></span><Badge>{row.status}</Badge></Link>)}</div> : <p className="text-sm text-muted">No organizations yet.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Recent provisioning</CardTitle></CardHeader><CardContent>{jobs.length ? <div className="space-y-3">{jobs.map((job) => <div key={job.id} className="flex items-center justify-between rounded-xl border p-3"><span className="text-sm"><span className="block font-semibold">{job.jobType}</span><span className="text-xs text-muted">{job.currentStep}</span></span><Badge>{job.status}</Badge></div>)}</div> : <p className="text-sm text-muted">No provisioning activity yet.</p>}</CardContent></Card></div></div>; }
