import Link from "next/link";
import { redirect } from "next/navigation";
import { desc } from "drizzle-orm";
import { db } from "@/db/client";
import { organizations } from "@/db/schema";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { authorizePlatform, PLATFORM_PERMISSIONS } from "@/modules/platform/authorization";
export default async function PlatformPage() { try { await authorizePlatform(PLATFORM_PERMISSIONS.organizationView); } catch { redirect("/platform/login"); } const rows = await db.select().from(organizations).orderBy(desc(organizations.createdAt)); return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><Badge>Platform console</Badge><h1 className="mt-3 text-3xl font-bold">Organization administration</h1><p className="mt-2 text-sm text-muted">Inspect tenant lifecycle and provisioning without entering customer organization context.</p></div><Button asChild><Link href="/platform/organizations/new">Create organization</Link></Button></div><Card><CardHeader><CardTitle>Organizations <span className="ml-2 text-sm font-normal text-muted">{rows.length}</span></CardTitle></CardHeader><CardContent>{rows.length === 0 ? <p className="rounded-xl border border-dashed p-8 text-center text-sm text-muted">No organizations have been created yet.</p> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-xs uppercase tracking-wide text-muted"><tr><th className="px-3 py-3">Organization</th><th className="px-3 py-3">Slug</th><th className="px-3 py-3">Status</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-b last:border-0"><td className="px-3 py-4 font-semibold"><Link className="hover:text-primary" href={`/platform/organizations/${row.id}`}>{row.name}</Link></td><td className="px-3 py-4 text-muted">{row.slug}</td><td className="px-3 py-4"><Badge>{row.status}</Badge></td></tr>)}</tbody></table></div>}</CardContent></Card></div>; }
