import { and, eq } from "drizzle-orm";
import { db } from "@/db/client";
import { approvalTasks, atsRequisitions, attendanceRecords, attendanceRegularizationRequests, employees, expenseClaims, leaveApplications, payrollRuns, workflowInstances } from "@/db/schema";
import { AppError, errorResponse } from "@/lib/errors";
import { resolveTenantContextForUser } from "@/modules/tenancy/context-core";
import { withSvelteRequestUser } from "$lib/server/request-context";
import type { RequestHandler } from "./$types";

export const GET: RequestHandler = async (event) => { try { return Response.json(await withSvelteRequestUser(event, async (user) => { const tenant = await resolveTenantContextForUser(user); if (!tenant.organization) throw new AppError("FORBIDDEN", "Organization context is required.", 403); const [task] = await db.select({ task: approvalTasks, instance: workflowInstances }).from(approvalTasks).innerJoin(workflowInstances, eq(approvalTasks.workflowInstanceId, workflowInstances.id)).where(and(eq(approvalTasks.id, event.params.taskId), eq(approvalTasks.organizationId, tenant.organization.id), eq(approvalTasks.approverUserId, user.id))); if (!task) throw new AppError("NOT_FOUND", "Approval task was not found.", 404); let detail: unknown = null; if (task.instance.entityType === "expense_claim") [detail] = await db.select().from(expenseClaims).where(and(eq(expenseClaims.id, task.instance.entityId), eq(expenseClaims.organizationId, tenant.organization.id))); else if (task.instance.entityType === "leave_application") [detail] = await db.select({ application: leaveApplications, employeeName: employees.displayName }).from(leaveApplications).innerJoin(employees, eq(leaveApplications.employeeId, employees.id)).where(and(eq(leaveApplications.id, task.instance.entityId), eq(leaveApplications.organizationId, tenant.organization.id))); else if (task.instance.entityType === "attendance_regularization") [detail] = await db.select({ request: attendanceRegularizationRequests, attendance: attendanceRecords, employeeName: employees.displayName }).from(attendanceRegularizationRequests).innerJoin(attendanceRecords, eq(attendanceRegularizationRequests.attendanceId, attendanceRecords.id)).innerJoin(employees, eq(attendanceRegularizationRequests.employeeId, employees.id)).where(and(eq(attendanceRegularizationRequests.id, task.instance.entityId), eq(attendanceRegularizationRequests.organizationId, tenant.organization.id))); else if (task.instance.entityType === "payroll_run") [detail] = await db.select().from(payrollRuns).where(and(eq(payrollRuns.id, task.instance.entityId), eq(payrollRuns.organizationId, tenant.organization.id))); else if (task.instance.entityType === "ats_requisition") [detail] = await db.select().from(atsRequisitions).where(and(eq(atsRequisitions.id, task.instance.entityId), eq(atsRequisitions.organizationId, tenant.organization.id))); return { success: true, task: task.task, instance: task.instance, detail }; })); } catch (cause) { return errorResponse(cause); } };
