import { NextResponse } from "next/server";
import { and, eq } from "drizzle-orm";
import { db, withTenantTransaction } from "@/db/client";
import { employees, invitations, roles } from "@/db/schema";
import { createOpaqueToken, hashToken } from "@/lib/crypto";
import { errorResponse, AppError } from "@/lib/errors";
import { recordAudit } from "@/lib/audit";
import { resolveTenantContext } from "@/modules/tenancy/context";
import { authorize } from "@/modules/tenancy/authorization";
import { sendInvitationEmail } from "@/lib/email";
export async function POST(request: Request, context: { params: Promise<{ employeeId: string }> }) { try { const tenant = await resolveTenantContext(); if (!tenant.organization) throw new AppError("FORBIDDEN", "Organization context is required.", 403); await authorize({ organizationId: tenant.organization.id, permission: "employee.invite" }); const { employeeId } = await context.params; const body = (await request.json().catch(() => ({}))) as { email?: string; resend?: boolean }; const [employee] = await db.select().from(employees).where(and(eq(employees.id, employeeId), eq(employees.organizationId, tenant.organization.id))); if (!employee) throw new AppError("NOT_FOUND", "Employee was not found.", 404); const email = (body.email ?? employee.personalEmail ?? employee.workEmail)?.trim().toLowerCase(); if (!email) throw new AppError("VALIDATION_ERROR", "An employee email is required.", 400); const role = await withTenantTransaction(tenant.organization.id, (tx) => tx.query.roles.findFirst({ where: and(eq(roles.organizationId, tenant.organization!.id), eq(roles.key, "EMPLOYEE")) })); if (!role) throw new AppError("PROVISIONING_FAILED", "The employee role is not provisioned.", 500); const existing = await db.query.invitations.findFirst({ where: and(eq(invitations.employeeId, employee.id), eq(invitations.status, "pending")) }); if (existing && !body.resend) throw new AppError("VALIDATION_ERROR", "An active invitation already exists.", 409); const token = createOpaqueToken(); const invitation = existing ? (await db.update(invitations).set({ invitedEmail: email, tokenHash: hashToken(token), expiresAt: new Date(Date.now() + 7 * 86_400_000), updatedAt: new Date() }).where(eq(invitations.id, existing.id)).returning())[0] : (await db.insert(invitations).values({ organizationId: tenant.organization.id, employeeId: employee.id, invitationType: "employee", invitedEmail: email, intendedRole: role.key, tokenHash: hashToken(token), expiresAt: new Date(Date.now() + 7 * 86_400_000) }).returning())[0]; await db.update(employees).set({ status: "invited", updatedAt: new Date() }).where(eq(employees.id, employee.id)); await recordAudit({ actorUserId: tenant.user.id, organizationId: tenant.organization.id, action: body.resend ? "employee_invitation_resent" : "employee_invited", resource: "employee", resourceId: employee.id }); const delivery = await sendInvitationEmail({ email, token, organizationName: tenant.organization.name }); return NextResponse.json({ success: true, invitation: { id: invitation.id, status: invitation.status, delivery } }); } catch (error) { return errorResponse(error); } }
