"use client";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

const configs = [
  ["Departments", "departments", "department", "Name", "Code"], ["Designations", "designations", "designation", "Name", "Code"], ["Locations", "locations", "location", "Name", "Code"], ["Teams", "teams", "team", "Name", "Code"], ["Employment types", "employment-types", "employmentTypes", "Name", "Code"], ["Shifts", "shifts", "shifts", "Name", "Code"], ["Holidays", "holidays", "holidays", "Name", "Date (YYYY-MM-DD)"], ["Working days", "working-days", "workingDays", "Day (0 Sunday – 6 Saturday)", "Working?"],
] as const;
type Item = { id: string; name?: string; code?: string; holidayDate?: string; dayOfWeek?: number; isWorkingDay?: boolean; status?: string };
export function MasterDataManager() {
  const [items, setItems] = useState<Record<string, Item[]>>({}); const [drafts, setDrafts] = useState<Record<string, { first: string; second: string }>>({}); const [busy, setBusy] = useState<string>(); const [error, setError] = useState<string>();
  async function load() { const responses = await Promise.all(configs.map(([, endpoint]) => fetch(`/api/app/master-data/${endpoint}`))); const values = await Promise.all(responses.map((r) => r.json())); setItems(Object.fromEntries(configs.map(([, endpoint], index) => [endpoint, values[index].items ?? []]))); }
  useEffect(() => { void load().catch(() => setError("Unable to load organization settings.")); }, []);
  async function create(endpoint: string, resource: string) { const draft = drafts[endpoint] ?? { first: "", second: "" }; const payload = resource === "workingDays" ? { dayOfWeek: Number(draft.first), isWorkingDay: draft.second !== "false" } : resource === "holidays" ? { name: draft.first, holidayDate: draft.second } : { name: draft.first, code: draft.second }; setBusy(endpoint); setError(undefined); const response = await fetch(`/api/app/master-data/${endpoint}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); if (!response.ok) { const body = await response.json().catch(() => ({})); setError(body.error?.message ?? `Unable to create ${endpoint}.`); } else { setDrafts({ ...drafts, [endpoint]: { first: "", second: "" } }); await load(); } setBusy(undefined); }
  async function deactivate(endpoint: string, resource: string, id: string) { if (!window.confirm("Deactivate this master-data item? Existing records will keep their references.")) return; setBusy(id); const response = await fetch(`/api/app/master-data/${resource}/${id}`, { method: "DELETE" }); if (!response.ok) setError("Unable to deactivate this item."); else await load(); setBusy(undefined); }
  async function edit(endpoint: string, resource: string, item: Item) { const first = window.prompt("Name", item.name ?? ""); if (first === null) return; const second = resource === "workingDays" ? String(item.isWorkingDay !== false) : window.prompt("Code", item.code ?? item.holidayDate ?? ""); if (second === null) return; const payload = resource === "workingDays" ? { is_working_day: second === "true" } : resource === "holidays" ? { name: first, holiday_date: second } : { name: first, code: second }; setBusy(item.id); const response = await fetch(`/api/app/master-data/${resource}/${item.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); if (!response.ok) setError("Unable to edit this item."); else await load(); setBusy(undefined); }
  return <div className="space-y-5">{error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{configs.map(([label, endpoint, resource, firstLabel, secondLabel]) => { const rows = items[endpoint] ?? []; const draft = drafts[endpoint] ?? { first: "", second: "" }; return <section key={endpoint} className="rounded-xl border bg-surface p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><h2 className="font-semibold">{label}</h2><p className="text-sm text-muted">{rows.length} configured</p></div><div className="flex w-full flex-col gap-2 sm:w-auto sm:flex-row"><Input aria-label={`${label} ${firstLabel}`} placeholder={firstLabel} value={draft.first} onChange={(e) => setDrafts({ ...drafts, [endpoint]: { ...draft, first: e.target.value } })} /><Input aria-label={`${label} ${secondLabel}`} placeholder={secondLabel} value={draft.second} onChange={(e) => setDrafts({ ...drafts, [endpoint]: { ...draft, second: e.target.value } })} /><Button disabled={busy === endpoint || !draft.first || !draft.second} onClick={() => void create(endpoint, resource)}>Add</Button></div></div><div className="mt-4 space-y-2">{rows.length === 0 ? <p className="rounded-lg border border-dashed p-4 text-sm text-muted">No {label.toLowerCase()} configured yet.</p> : rows.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 rounded-lg border p-3 text-sm"><span>{item.name ?? (item.dayOfWeek !== undefined ? ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"][item.dayOfWeek] : item.holidayDate)}<span className="ml-2 text-muted">{item.code ?? (item.isWorkingDay ? "Working day" : "Non-working day")}</span></span><span className="flex gap-2">{item.status !== "inactive" && <Button aria-label={`Edit ${label} item`} variant="ghost" size="sm" disabled={busy === item.id} onClick={() => void edit(endpoint, resource, item)}>Edit</Button>}{resource !== "workingDays" && item.status !== "inactive" && <Button aria-label={`Deactivate ${label} item`} variant="ghost" size="sm" disabled={busy === item.id} onClick={() => void deactivate(endpoint, resource, item.id)}>Deactivate</Button>}</span></div>)}</div></section>; })}</div>;
}
