import { and, eq, sql } from "drizzle-orm";
import { db } from "@/db/client";
import { billingUsage, plans, planFeatures, subscriptions, employees, collaborationProjects, collaborationTasks } from "@/db/schema";
import { authorize } from "@/modules/tenancy/authorization";
import { recordAudit } from "@/lib/audit";
import { billingProviderConfigured } from "@/lib/billing";
import { AppError } from "@/lib/errors";
export async function getBillingOverview(input: { organizationId: string; userId: string }) { await authorize({ organizationId: input.organizationId, permission: "billing.view" }); const [row] = await db.select({ subscription: subscriptions, plan: plans }).from(subscriptions).innerJoin(plans, eq(subscriptions.planId, plans.id)).where(eq(subscriptions.organizationId, input.organizationId)); const usage = await usageSnapshot(input.organizationId); return { subscription: row?.subscription ?? null, plan: row?.plan ?? null, usage, providerConfigured: billingProviderConfigured() }; }
export async function getEntitlement(organizationId: string, feature: string) { const [row] = await db.select({ planId: plans.id }).from(subscriptions).innerJoin(plans, eq(subscriptions.planId, plans.id)).where(and(eq(subscriptions.organizationId, organizationId), eq(subscriptions.billingStatus, "active"))); if (!row) return { enabled: false, limit: null, source: "no_subscription" }; const [featureRow] = await db.select().from(planFeatures).where(and(eq(planFeatures.planId, row.planId), eq(planFeatures.featureKey, feature))); return { enabled: featureRow?.enabled ?? false, limit: featureRow?.limitValue ?? null, source: "plan" }; }
export async function canUseFeature(organizationId: string, feature: string) { const entitlement = await getEntitlement(organizationId, feature); return entitlement.enabled; }
export async function usageSnapshot(organizationId: string) { const [employeeCount] = await db.select({ count: sql<number>`count(*)` }).from(employees).where(eq(employees.organizationId, organizationId)); const [projectCount] = await db.select({ count: sql<number>`count(*)` }).from(collaborationProjects).where(eq(collaborationProjects.organizationId, organizationId)); const [taskCount] = await db.select({ count: sql<number>`count(*)` }).from(collaborationTasks).where(eq(collaborationTasks.organizationId, organizationId)); return { employees: Number(employeeCount?.count ?? 0), projects: Number(projectCount?.count ?? 0), tasks: Number(taskCount?.count ?? 0) }; }
export async function hasCapacity(organizationId: string, feature: string, currentUsage: number, requested = 1) { const entitlement = await getEntitlement(organizationId, feature); if (entitlement.limit === null) return true; if (currentUsage + requested > entitlement.limit) throw new AppError("VALIDATION_ERROR", `${feature} limit reached for the current plan.`, 403); return true; }
export async function recordUsage(organizationId: string, metric: string, value: number) { const today = new Date().toISOString().slice(0, 10); await db.insert(billingUsage).values({ organizationId, metric, usageValue: value, periodStart: today, periodEnd: today }).onConflictDoUpdate({ target: [billingUsage.organizationId, billingUsage.metric, billingUsage.periodStart, billingUsage.periodEnd], set: { usageValue: value, updatedAt: new Date() } }); }
export async function changePlan(input: { organizationId: string; userId: string; planCode: "FREE" | "STARTER" | "PROFESSIONAL" | "ENTERPRISE"; billingCycle?: "monthly" | "annual" }) { await authorize({ organizationId: input.organizationId, permission: "billing.manage" }); const [plan] = await db.select().from(plans).where(eq(plans.code, input.planCode)); if (!plan) throw new AppError("NOT_FOUND", "Plan was not found.", 404); const [subscription] = await db.update(subscriptions).set({ planId: plan.id, billingCycle: input.billingCycle ?? "monthly", billingStatus: "active", updatedAt: new Date() }).where(eq(subscriptions.organizationId, input.organizationId)).returning(); await recordAudit({ actorUserId: input.userId, organizationId: input.organizationId, action: "billing_plan_changed", resource: "subscription", resourceId: subscription?.id, metadata: { planCode: input.planCode } }); return subscription; }
