import { and, eq, gte, lte, ne } from "drizzle-orm";
import { db } from "@/db/client";
import { employees, holidays, leaveApplications, leaveBalances, leaveTransactions, leaveTypes, workingDays } from "@/db/schema";
import { recordAudit } from "@/lib/audit";
import { AppError } from "@/lib/errors";
import { authorize } from "@/modules/tenancy/authorization";
import { availableBalance, calculateLeaveDays, overlaps } from "@/modules/leave/calculator";
import { createWorkflowInstance, ensureDefaultWorkflow } from "@/modules/workflows/service";

function dateRange(start: string, end: string) { const dates: string[] = []; const cursor = new Date(`${start}T00:00:00Z`); const last = new Date(`${end}T00:00:00Z`); while (cursor <= last) { dates.push(cursor.toISOString().slice(0, 10)); cursor.setUTCDate(cursor.getUTCDate() + 1); } return dates; }
async function employeeForUser(organizationId: string, userId: string) { const [employee] = await db.select().from(employees).where(and(eq(employees.organizationId, organizationId), eq(employees.userId, userId))); if (!employee) throw new AppError("NOT_FOUND", "Your employee profile is not linked.", 404); return employee; }

export async function applyLeave(input: { organizationId: string; userId: string; leaveTypeId: string; startDate: string; endDate: string; halfDay: boolean; reason: string }) {
  await authorize({ organizationId: input.organizationId, permission: "leave.apply" }); const employee = await employeeForUser(input.organizationId, input.userId); if (input.endDate < input.startDate) throw new AppError("VALIDATION_ERROR", "Leave end date must be on or after the start date.", 400);
  const [type] = await db.select().from(leaveTypes).where(and(eq(leaveTypes.id, input.leaveTypeId), eq(leaveTypes.organizationId, input.organizationId), eq(leaveTypes.active, true))); if (!type) throw new AppError("NOT_FOUND", "Leave type was not found.", 404); if (!input.reason.trim()) throw new AppError("VALIDATION_ERROR", "A leave reason is required.", 400);
  const year = Number(input.startDate.slice(0, 4)); const days = dateRange(input.startDate, input.endDate); const workingRows = await db.select().from(workingDays).where(eq(workingDays.organizationId, input.organizationId)); const workingByDay = new Map(workingRows.map((row) => [row.dayOfWeek, row.isWorkingDay])); const holidayRows = await db.select({ holidayDate: holidays.holidayDate }).from(holidays).where(and(eq(holidays.organizationId, input.organizationId), gte(holidays.holidayDate, input.startDate), lte(holidays.holidayDate, input.endDate), eq(holidays.status, "active"))); const holidaySet = new Set(holidayRows.map((row) => row.holidayDate)); const configuredDays = days.map((date) => { const day = new Date(`${date}T00:00:00Z`).getUTCDay(); const dayOfWeek = day === 0 ? 7 : day; return { date, isWorkingDay: workingByDay.get(dayOfWeek) ?? dayOfWeek <= 5, isHoliday: holidaySet.has(date) }; }); const requestedDays = calculateLeaveDays(configuredDays, input.halfDay);
  if (requestedDays <= 0) throw new AppError("VALIDATION_ERROR", "The selected dates contain no working days.", 400); if (requestedDays < type.minimumDays || (type.maximumDays !== null && requestedDays > type.maximumDays)) throw new AppError("VALIDATION_ERROR", "The requested leave duration is outside the leave type limits.", 400);
  const existing = await db.select({ startDate: leaveApplications.startDate, endDate: leaveApplications.endDate }).from(leaveApplications).where(and(eq(leaveApplications.organizationId, input.organizationId), eq(leaveApplications.employeeId, employee.id), ne(leaveApplications.status, "cancelled"), ne(leaveApplications.status, "rejected"))); if (overlaps(input.startDate, input.endDate, existing)) throw new AppError("VALIDATION_ERROR", "The selected dates overlap another leave application.", 409);
  const balance = await db.transaction(async (tx) => { await tx.insert(leaveBalances).values({ organizationId: input.organizationId, employeeId: employee.id, leaveTypeId: input.leaveTypeId, leaveYear: year, openingBalance: 0, accrued: 0 }).onConflictDoNothing(); const [row] = await tx.select().from(leaveBalances).where(and(eq(leaveBalances.organizationId, input.organizationId), eq(leaveBalances.employeeId, employee.id), eq(leaveBalances.leaveTypeId, input.leaveTypeId), eq(leaveBalances.leaveYear, year))); if (!row || availableBalance({ opening: row.openingBalance, accrued: row.accrued, adjusted: row.adjusted, consumed: row.consumed, pending: row.pending }) < requestedDays) throw new AppError("VALIDATION_ERROR", "Insufficient leave balance.", 409); const [application] = await tx.insert(leaveApplications).values({ organizationId: input.organizationId, employeeId: employee.id, leaveTypeId: input.leaveTypeId, startDate: input.startDate, endDate: input.endDate, requestedDays, halfDay: input.halfDay, reason: input.reason.trim(), status: "pending" }).returning(); await tx.update(leaveBalances).set({ pending: row.pending + requestedDays, updatedAt: new Date() }).where(eq(leaveBalances.id, row.id)); await tx.insert(leaveTransactions).values({ organizationId: input.organizationId, employeeId: employee.id, leaveTypeId: input.leaveTypeId, leaveBalanceId: row.id, transactionType: "reservation", amount: requestedDays, referenceId: application.id, actorUserId: input.userId }); return { application, balance: row }; });
  try { await ensureDefaultWorkflow(input.organizationId, "leave", input.userId); const workflow = await createWorkflowInstance({ organizationId: input.organizationId, workflowType: "leave", entityType: "leave_application", entityId: balance.application.id, subjectEmployeeId: employee.id, submittedByUserId: input.userId }); await db.update(leaveApplications).set({ workflowInstanceId: workflow.id, updatedAt: new Date() }).where(eq(leaveApplications.id, balance.application.id)); } catch (error) { await db.transaction(async (tx) => { await tx.update(leaveApplications).set({ status: "rejected", updatedAt: new Date() }).where(eq(leaveApplications.id, balance.application.id)); await tx.update(leaveBalances).set({ pending: Math.max(0, balance.balance.pending - requestedDays), updatedAt: new Date() }).where(eq(leaveBalances.id, balance.balance.id)); await tx.insert(leaveTransactions).values({ organizationId: input.organizationId, employeeId: employee.id, leaveTypeId: input.leaveTypeId, leaveBalanceId: balance.balance.id, transactionType: "reservation_release", amount: requestedDays, referenceId: balance.application.id, actorUserId: input.userId }); }); throw error; }
  await recordAudit({ actorUserId: input.userId, organizationId: input.organizationId, action: "leave_submitted", resource: "leave_application", resourceId: balance.application.id }); return balance.application;
}

export async function listLeaveTypes(organizationId: string) { await authorize({ organizationId, permission: "leave.read" }); return db.select().from(leaveTypes).where(eq(leaveTypes.organizationId, organizationId)); }
